### PR TITLE
Avoid FW popup when using non-microsoft FW application

### PR DESCRIPTION
**Pull request by UselessGuru**
https://github.com/aaronsace/MultiPoolMiner/issues/728
https://github.com/aaronsace/MultiPoolMiner/issues/351

Help wanted! Who can teach me how to properly make a pull??? I just wanted to change lines 
254 - 264:
```
    if (Get-Command "Get-MpPreference" -ErrorAction SilentlyContinue) {
        if ((Get-Command "Get-MpComputerStatus" -ErrorAction SilentlyContinue) -and (Get-MpComputerStatus -ErrorAction SilentlyContinue)) {
            if (Get-Command "Get-NetFirewallRule" -ErrorAction SilentlyContinue) {
                if ($MinerFirewalls -eq $null) {$MinerFirewalls = Get-NetFirewallRule | Where-Object DisplayName -EQ "MultiPoolMiner" | Get-NetFirewallApplicationFilter | Select-Object -ExpandProperty Program}
                if (@($AllMiners | Select-Object -ExpandProperty Path -Unique) | Compare-Object @($MinerFirewalls) | Where-Object SideIndicator -EQ "=>") {
                    Start-Process (@{desktop = "powershell"; core = "pwsh"}.$PSEdition) ("-Command Import-Module '$env:Windir\System32\WindowsPowerShell\v1.0\Modules\NetSecurity\NetSecurity.psd1'; ('$(@($AllMiners | Select-Object -ExpandProperty Path -Unique) | Compare-Object @($MinerFirewalls) | Where-Object SideIndicator -EQ '=>' | Select-Object -ExpandProperty InputObject | ConvertTo-Json -Compress)' | ConvertFrom-Json) | ForEach {New-NetFirewallRule -DisplayName 'MultiPoolMiner' -Program `$_}" -replace '"', '\"') -Verb runAs
                    $MinerFirewalls = $null
                }
            }
        }
    }
```

### CODE REVIEW

**Comment by aaronsace** [comment]
Hey, use the app: https://desktop.github.com/

**Comment by UselessGuru** [comment]
What do you think I am doing??? I am usually not all that stupid... but :-)

**Comment by aaronsace** [comment]
LOL, but it says you've changed every line...?

Must be something wrong with your editor... is it messing the indents and/or encoding?

**Comment by UselessGuru** [comment]
> LOL, but it says you've changed every line...?

I think I know what my mistake was... we'll see on my next try :-)

**Comment by UselessGuru** [comment]
@aaronsace 

What editor / dev environment are you using?

**Comment by aaronsace** [comment]
Visual Studio Code: https://code.visualstudio.com/

**Comment by aaronsace** [comment]
Windows PowerShell ISE works but it doesn't have a document formatter which is handy to run before uploading.

**Comment by UselessGuru** [comment]
I am on PowerGUI... VSC is very slow when mining on the same box :-(

**Comment by fonyo** [comment]
@UselessGuru if that helps I am also scared to use the desktop app, it has its own mind! I messed up my own repo with it many times. And I would also like to think I am not that stupid... ;)

**Comment by UselessGuru** [comment]
Any comments on the change itself?
It suppresses the windows FW handling if a 3party FW is installed (at least for Symantec Endpoint Protection 14)

**Comment by fonyo** [comment]
Unfortunately for you, I cannot test it as I always have all FW stuff disabled and would not install 3rd-party firewall apps either. Apologies.

**Comment by UselessGuru** [comment]
Closing this because of conflicts. Will reopen.

**Pull request closed without merging**
