### PR TITLE
Removing unsupported algos from Zealot

### PR DESCRIPTION
**Pull request by Rama-Nujan**
I believe those algos are not supported by Zealot Enemy

### CODE REVIEW

**Comment by mkirov0** [comment]
See thats exactly what I'm trying to avoid. Believing vs knowing.
Its true, maybe its better for the Master not to have them enabled by default, since after a pool adds any of the algos it will suddenly start to benchmark. Which can be confusing for new users. I personally would like to know if a new algo is profitable and which of my miners is top performing asap, but I guess its a personal choice. 
As for how the Master is configured its up to the MPM team to decide.

**Comment by UselessGuru** [comment]
> As for how the Master is configured its up to the MPM team to decide.

I think we should keep all working algorithms in there and let MPM benchmark them once so it knows it's speed.
I agree in removing all non-working ones, but keep all non-profitable ones commented out.

The long list of possible miners in the overview is kind of annoying, but there are planned enhancements in the works which:
- Will shorten the list of miners in the overview
- A GUI which allows you to enable / disable algorithms per miner more easily

**Comment by Rama-Nujan** [comment]
I wonder if the optimization made to some of the base algos involved in chained algos (bmw, echo, sha256, cube, shavite, luffa etc etc) extend to others (ie Zealot/Nevermore intended for X16r, X16s but provides advantages to C11 and X11evo). I think you may be onto something. Good find.

**Comment by grantemsley** [comment]
@UselessGuru My thoughts are:

- If the miner supports it, it should be in the miner file.  Even ones our pools don't (yet support).
- If it's an algo that we know will not ever be profitable on any hardware configuration (so mostly algos with ASICs available), it should be commented out.
- Even if there's another miner that is a bit faster, leave it to the benchmarking to decide.  That faster miner might crash on my system or slow it down too much, and I might disable it.  Unless it's a lot slower (like say half the speed of all the other miners for that algo) - then maybe comment it out.
- Any algos the miner doesn't support at all should be removed entirely - UNLESS the miner's documentation/help messages say it is supported but it really isn't (there's a few miners like that) - then leave it in the file with a comment that is isn't really supported so people don't think it was missed accidentally.

**Comment by Rama-Nujan** [comment]
Ok. Confirmed that X12, JHA and the rest are NOT supported. Only the ones that remain.

**Comment by mkirov0** [comment]
Great! I like it! Makes perfect sense.

**Pull request merged**
