### PR TITLE
Will no longer attempt to run miners for hardware that is not present

### PR DESCRIPTION
**Pull request by UselessGuru**
Fix for:
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1829
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1828
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1848
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1815
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1832

### CODE REVIEW

**Comment by Dewbs** [comment]
Stops my CPU mining. Had noticed my cpu miners before were in Device: {} section before (i.e. don't think it's detecting properly) albeit it did mine. Intel i7-4770k fyi.

**Comment by Dewbs** [comment]
Merged yet as informed not only stops 'not present' hardware running but also 'present' hardware (intel cpu)

**Comment by grantemsley** [comment]
@Dewbs I know what that issue is then 

Your system probably doesn't have CPU OpenCL drivers.

You can download them separate from the AMD graphics drivers. Normally I'd link you right to AMD's site for them (https://developer.amd.com/amd-license-agreement-appsdk/ ), but it's broken right now, so here's a mirror: https://community.amd.com/external-link.jspa?url=http%3A%2F%2Famd-dev.wpengine.netdna-cdn.com%2Fapp-sdk%2Finstallers%2FAPPSDKInstaller%2F3.0.130.135-GA%2Ffull%2FAMD-APP-SDKInstaller-v3.0.130.135-GA-windows-F-x64.exe

**Comment by Dewbs** [comment]
I don't have anything AMD (cpu or gpu) - is that still applicable?

**Comment by grantemsley** [comment]
Yes, that and driver works on both Intel and AMD CPUs.

We shouldn't really require it because the CPU miners don't need OpenCL, but it will fix the issue for now.

**Comment by Dewbs** [comment]
Ok thank you - I wondered if it would start mining on the iGPU (not that I would particularly want that) but it does not

**Comment by grantemsley** [comment]
According to that devices list, it's detecting a 1070TI, a 1080TI, a 1060, and 2 i7-4770K.

I'm going to assume you only actually have 1 CPU in that system...and neither of them is your iGPU.

Interestingly, it's detecting it in 2 different platforms:
```
                       "Platform":  "@{Profile=FULL_PROFILE; Version=OpenCL 1.2 ; Name=Intel(R) OpenCL; Vendor=Intel(R) Corporation; Extensions=System.Object[]}",
                       "Platform":  "@{Profile=FULL_PROFILE; Version=OpenCL 2.1 ; Name=Experimental OpenCL 2.1 CPU Only Platform; Vendor=Intel(R) Corporation; Extensions=System.Object[]}",
```
Also with different extensions and driver versions.

So what I'm guessing is going on, is that you installed the Intel OpenCL drivers, and then also installed the AMD OpenCL drivers...and now both detect your CPU.  Uninstall the AMD thing I told you to install.  Or uninstall the Intel one. Having one or the other should fix it for now.

I'm going to write a fix for CPU detection that should fix that.

**Comment by Dewbs** [comment]
AMD drivers were not installed. 
Initial position: older intel display drivers installed only. 
Installed intel sdk - cpu then detected by mpm. 
Then updated intel display driver to latest version prompting restart, after which 2 cpu reported in mpm (1 physical).

**Comment by UselessGuru** [comment]
Please test https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1868

**Pull request merged**
