### PR TITLE
Update cast.txt for version 130 and add 4 algos

### PR DESCRIPTION
**Pull request by paulpoco**
I cannot test as I have no AMD GPUs, was looking at the CryptoNight algos that is in PR  #1979 , and while looking I came accross the Cast XMR.

### CODE REVIEW

**Comment by UselessGuru** [comment]
I guess we should wait adding this until we have confirmed data in algoriths.txt
At present no MPM supported pool allow to mine any of the new algorithms.

**Comment by paulpoco** [comment]
All the code matches PR #2019

**Comment by paulpoco** [comment]
Somehow hit Delete in error

**Comment by grantemsley** [comment]
This would be a lot easier to read if it were a powershell script like the others.

**Pull request merged**
