### PR TITLE
Add CcminerDelos

### PR DESCRIPTION
**Pull request by UselessGuru**
**Note: This is a brand new closed source miner with 1% fee - use at your own risk!**

Some algorithms have no pool for mining (yet) - therefor I marked them as **_untested_**.

If someone manages to benchmark these then please report your findings here. Thank you!

**Updated to version 1.3**

Devs recommend x86 version with CUDA 9.1. This is what I use in the miner file now.

### CODE REVIEW

**Comment by aloth** [comment]
I also benchmarked Delos (stable release) as fastest for HSR and HMQ1725.

@symalla: just for curiousity, which miner work better for you for HSR and HMQ1725?

**Comment by symalla** [comment]
@aloth for HSR and HMQ1725 I got Nervermore as faster.

**Comment by aloth** [comment]
@symalla Interesting. Maybe some variations depenting on the hardware.

**Comment by grantemsley** [comment]
This miner requires CUDA 9.2, which is only available in the very latest nvidia driver released last week.

**Comment by UselessGuru** [comment]
Implemented a version check:

WARNING: Miner (CcminerDelos) requires CUDA version 9.3.00 or above (installed version is 9.2.81). Please update your Nvidia drivers.

**Comment by grantemsley** [comment]
They also updated to 1.2.1, with 4 different versions - regular and x16r optimized builds, in both 32 and 64 bit.

**Comment by All-in-Miner** [comment]
@grantemsley Someone in the forum was also asking for a CUDA 9.1 release!

What is the general recommendation 32- vs. 64-bit? And all these different CUDA versions?

Or do we neeed to add them all?

**Comment by grantemsley** [comment]
For cuda version usually the latest is good unless there are some driver or hardware compatibility issues.  I only mentioned it because I suspect most people don't update their video card drivers every week.

For bitness, we have usually been using 64 bit versions unless there is a substantial difference between 32 and 64 bit performance.

**Comment by centreece** [comment]
So which version do we get with MPM? 64-bit and CUDA 9.2?

Is there a way to give the lazy updaters the CUDA 9.1 version then?

**Pull request merged**
