### PR TITLE
Move config files to separate 'Configs' folder

### PR DESCRIPTION
**Pull request by UselessGuru**
Instead of storing Config.txt (and other future config files) directly in the MPM folder I suggest storing them separately from the program files.

This make upgrading or moving MPM settings much easier

Proposed folder name: 'Configs'

### CODE REVIEW

**Comment by grantemsley** [comment]
I would have gone with the singular "Config" for the folder name, but I like it.

**Comment by aaronsace** [comment]
I don't want the text file to be hidden. The GUI should be put in a subfolder but the config file should stay in the root directory.

**Comment by UselessGuru** [comment]
@ aaronsace

Why would you keep in in the root? 
A school I was taught to keep programs and data separate :-)

@ grantemsley

> "Config" for the folder name

 If ther will ever be only ONR conplete config file then singulage 'Config' makes sense. But I believe that splitting config files can be beneficial. then 'Configs' would be more appropriate, and we already have plural 'Miner**s**' and 'Pool**s**'

**Comment by UselessGuru** [comment]
> splitting config files can be beneficial

Having separate config files makes more sense to me because:

a) A miner can create it's own default config file -> Setup GUI would just need to do a 'Get-ChildItem "Miners"' and then iterate through 'Configs\Miners\' to get a full list of miner options
b) config parameters are easily locatable. To reset them to default just delete the parameter file

I would even manage a subdir structure for configs like:

Configs\config.txt
Configs\Pools\[poolname].txt
Configs\Miners\[MinerName].txt

The setup GUI could iterate through these two sub folders and generate a tab per file.

**Comment by aaronsace** [comment]
@UselessGuru The miners can just be converted to JSON then finally be done with the PS1 files.

**Comment by UselessGuru** [comment]
> The miners can just be converted to JSON then finally be done with the PS1 files.

I don't undestand. Please elaborate a little bit further ;-) TIA

**Comment by aaronsace** [comment]
The files in the miners folder is the configuration. Now that the PS1 files have become very standard, they can be exported to JSON instead. 

The main config.txt file should be kept simple.

**Comment by UselessGuru** [comment]
I still do not understand.

> they can be exported to JSON instead.

What so you mean by that? What is your strategy for creating miners? Exclusively through json txt files, oder use ps to create them?

I much prefer ps because it gives much more possibilities, and there are scenarios which cannot be met with plain txt json. A few examples of things I cannot imagine with JSON:

e.g.:
- a simplified and easily configurable ONE FILE miner for Claymore Dual (updating 20 JSON files is much more of a hassle than 1 ps1 file - errors are much more likely). Plus if someone wants an extra drci level he has much more work to do than just adding a config item.
- Iterating inside a miner to launch a separate miner instance per GPU device class (as I have implemented in my build)
 -Reading miner options from the miner file (e.g. supported algos)

**Comment by UselessGuru** [comment]
@aaronsace 
Could you make a statement on this? TIA:

I still do not understand.

> they can be exported to JSON instead.

What so you mean by that? What is your strategy for creating miners? Exclusively through json txt files, oder use ps to create them?

I much prefer ps because it gives much more possibilities, and there are scenarios which cannot be met with plain txt json. A few examples of things I cannot imagine with JSON:

e.g.:

- a simplified and easily configurable ONE FILE miner for Claymore Dual (updating 20 JSON files is much more of a hassle than 1 ps1 file - errors are much more likely). Plus if someone wants an extra drci level he has much more work to do than just adding a config item.
- Iterating inside a miner to launch a separate miner instance per GPU device class (as I have implemented in my build)
- Reading miner options from the miner file (e.g. supported algos)

**Comment by aaronsace** [comment]
Apologies, will start pushing this forward after 2.7.3. 

Just a quick update on direction: 
All miners that can be exported to JSON should be ([minerfile.ps1] | convertto-json). 
A string variable called 'variation' should be added to the miners so that Claymore files can be merged together and still have separate stats (stat file name has [name]-[variation] "Claymore-Blake2s20"). 
GPU management will be handle by a function/variable that the JSON config and use.

**Comment by UselessGuru** [comment]
> Just a quick update on direction:

This is too quick / brief for me to fully understand. Maybe we don't speak the same language :-)

I would like to follow a path like [this](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1234) and [this](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1237)

**Comment by UselessGuru** [comment]
@aaronsace 

Could you please air your thoughts on this?

**Pull request closed without merging**
