### PR TITLE
EWBF2 Miner version 0.5 (Nvidia only)

### PR DESCRIPTION
**Pull request by UselessGuru**
**Important: This miner also requires also all the changes listed below:**
- Equihash-BTG Fix in
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2001

- new pool files from 
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1972
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2011

- Algorithms.txt from 
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2018

As of EWBF 0.5 this miner supports --pers auto:
https://bitcointalk.org/index.php?topic=2759935.msg43324268#msg43324268

### CODE REVIEW

**Comment by UselessGuru** [comment]
DL Uri added

**Comment by Dewbs** [comment]
Doesn't download - is there an algo file to use with this? I don't use MPH, only Zergpool. I think they're expecting other values:

For Equihash192 algo use EWBF Equihash miner v0.3 and --algo 192_7 --pers ZERO_PoW 
For Equihash144 algo use EWBF Equihash miner v0.3 and --algo 144_5 --pers sngemPoW

**Comment by UselessGuru** [comment]
@Dewbs 

Problem seen. Each pool has its own representation of the new Equihash stuff. For ZergPool we require a change in the pool file. I'll create a new PR for this.

**Comment by Dewbs** [comment]
Thank you for working on this - however still doesn't initiate download for me
(using this + #2011)

**Comment by UselessGuru** [comment]
@Dewbs 

You need to configure no only the algos, but also a pool that offers to mine the new algorithms. These are currently
- MiningPoolHubCoins
- ZergPool

Please post your start batch and the config.file.

**Comment by Dewbs** [comment]
I mentioned above I'm not using MPH, only ZergPool.
fyi I changed my algo/cfg file to 

    "equihash144":  "Equihash144",
    "equihash96":  "Equihash96",
    "equihash192":  "Equihash192",

and the miner to

    [PSCustomObject]@{Algorithm = "Equihash96"; MinMemGB = 2; Params = ""}
    [PSCustomObject]@{Algorithm = "Equihash144"; MinMemGB = 2; Params = ""}
    [PSCustomObject]@{Algorithm = "Equihash192"; MinMemGB = 3; Params = ""}

just out of interest.

Of course it doesn't mine but it dis download the miner and run it:

from mpm log:
2018-07-17 20:21:37 INFO: Starting miner (EWBF2-GPU#03): 'C:\MPM\Bin\NVIDIA-EWBF2-Equihash\miner.exe --algo Equihash192 --pers ZERO_PoW --eexit 1 --api 127.0.0.1:42104 --server europe.mine.zergpool.com --port 2144 --user 1GD1YxJWzne32MeDLfX5MLV6dGtT5uW4AN --pass multipoolminer,c=BTC --pec --fee 0 --intensity 64 --cuda_devices 2'
2018-07-17 20:21:37 INFO: Starting miner (EWBF2-GPU#02): 'C:\MPM\Bin\NVIDIA-EWBF2-Equihash\miner.exe --algo Equihash192 --pers ZERO_PoW --eexit 1 --api 127.0.0.1:42103 --server europe.mine.zergpool.com --port 2144 --user 1GD1YxJWzne32MeDLfX5MLV6dGtT5uW4AN --pass multipoolminer,c=BTC --pec --fee 0 --intensity 64 --cuda_devices 1'
2018-07-17 20:21:37 INFO: Starting miner (EWBF2-GPU#01): 'C:\MPM\Bin\NVIDIA-EWBF2-Equihash\miner.exe --algo Equihash192 --pers ZERO_PoW --eexit 1 --api 127.0.0.1:42102 --server europe.mine.zergpool.com --port 2144 --user 1GD1YxJWzne32MeDLfX5MLV6dGtT5uW4AN --pass multipoolminer,c=BTC --pec --fee 0 --intensity 64 --cuda_devices 0'
2018-07-17 20:21:37 INFO: Pinging monitoring server. 

from EWBF2 log
+-------------------------------------------------+
|         EWBF's Eqihash CUDA miner. v0.4         |
+-------------------------------------------------+
20:21:37 ERROR: Algorithm not specified or not supported, you need to set the algorithm that you want to use, parameter: --algo
20:21:37 ERROR: No properly configured pool!

**Comment by UselessGuru** [comment]
> [PSCustomObject]@{Algorithm = "Equihash96"; MinMemGB = 2; Params = ""}
[PSCustomObject]@{Algorithm = "Equihash144"; MinMemGB = 2; Params = ""}
[PSCustomObject]@{Algorithm = "Equihash192"; MinMemGB = 3; Params = ""}

You might have the wrong algorithm.txt. See first post.

**Comment by Dewbs** [comment]
"fyi I changed my algo/cfg file to:"

It doesn't 'see' anything from ZergPool with current master algo file (see first report in this pull request.
If I change my algo & config (as stated above) then it will 'see' the algo and download the miner, as reported.
Please see edits in previous post

**Comment by UselessGuru** [comment]
@Dewbs 

Cause found:
zergpool

The miner file filters algorithms with 0 hash rate (line 33):

$ZergPool_Request | Get-Member -MemberType NoteProperty -ErrorAction Ignore | Select-Object -ExpandProperty Name | Where-Object {$ZergPool_Request.$_.hashrate -gt 0} | ForEach-Object {
...

The API seems to have an issue. It SOMETIMES reports 0 hash rate and SOMETIMES 0 workers. 

Out of curiosity:
What pool is giving you Equihash96? I cannot find anything on ZergPool or MiningPoolHub.

**Comment by Dewbs** [comment]
The reason it failed is because of 2 reasons:

1) ZergPool does not see Equihash1927 as a valid algorithm

When I used Equihash192 in algo file and my config then it downloaded the miner and attempted to benchmark it. It fails as the current files do not pass the correct --algo to the miner

2) ZergPool requires --algo 192_7 passing to the miner but instead it passes --algo Equihash192 if Equihash192 is used in algo file to create any activity at all.

I don't think any pool is giving Equi96 - I'm not concerned with that - I'm just wanting to be able to mine the algos on Zergpool

**Comment by UselessGuru** [comment]
@Dewbs 

> to be clear:
ZergPool is looking for algo Equihash144, Equihash192 but miner expects 144_5 & 192_7

> once again (from ZergPool):

> For Equihash192 algo use EWBF Equihash miner v0.3 and --algo 192_7 --pers ZERO_PoW
> For Equihash144 algo use EWBF Equihash miner v0.3 and --algo 144_5 --pers sngemPoW

Just for your understanding how the algo mapping works:

**The pool stuff:**

The pool **exposes** algorithm Equihash144 through the API
This is then mapped by Get-Algorithm to Equihash1445 (ZergPool.ps1 line 37)
The coin name is added (ZergPool.ps1 line 42)
The miner object (http://localhost:3999/allpools) will then have an entry like
```
        "equihash1445":  {
                             "Algorithm":  "Equihash1445",
                             "CoinName":  "SnowGem",
                             "Price":  3.65349E-06,
                             "StablePrice":  3.4701133791415582E-06,
                             "MarginOfError":  0.000734923530797865,
                             "Protocol":  "stratum+tcp",
                             "Host":  "europe.mine.zergpool.com",
                             "Port":  2146,
                             "User":  "aBcDeFgH1234567890",
                             "Pass":  "BlackBox,c=BTC",
                             "Region":  "Europe",
                             "SSL":  false,
                             "Updated":  "\/Date(1531861963113)\/",
                             "Name":  "ZergPool",
                             "Price_Bias":  3.6481199284589306E-06,
                             "Price_Unbias":  3.65349E-06
                         },
```
From now on MPM will only work with the normalized algo name Equihash1445 (the result from Get-Algorithm)

**The miner stuff:**

The miner file iterates through the available algorithms (as defined in EWBF2.ps1 lines 17-20)
During the second iteration $_.Algorithm will be 'Equihash-144_5'.
The variable $Algorithm is then filled with 144_5
`$Algorithm = ($_.Algorithm) -replace "Equihash-"` (EWBF2.ps1 line 43)The algo Equihash-144_5 gets mapped to Equihash1445 (EWBF2.ps1 line 46)
The miner file finds the pool object for Equihash1445 (EWBF2.ps1 lines 17-20) and puts together the command line for the miner. It will then be something like

`miner.exe --algo 144_5 --pers sngemPoW --eexit 1 --api 127.0.0.1:42100 --server europe.mine.zergpool.com --port 2146 --user aBcDeFgHiJ1234567890 --pass WorkerName,c=BTC --pec --fee 0 --intensity 64 --cuda_devices 0`

Note: --algo 144_5

Maybe this helps you find the cause. I have exactly the files running as posted in this tread and it is working beautifully.

**Comment by Dewbs** [comment]
Gone back to posted files
No download No entries in http://localhost:3999/allpools

**Comment by Dewbs** [comment]
Algo file contains
    "equihash":  "Equihash",
    "equihashbtg":  "Equihash1445",
    "equihash1445":  "Equihash1445",
    "equihash965":  "Equihash965",
    "equihash1927":  "Equihash1927",
Config contains:
    "Equihash",
    "Equihash1445",
    "Equihash965",
    "Equihash1927",
Miner from this post, pool file from #2011

**Comment by UselessGuru** [comment]
> Algo file contains

That is your problem

You need more algorithms:
```
     "equihash":  "Equihash",
    "equihash144":  "Equihash1445",
    "equihash1445":  "Equihash1445",
    "equihash192":  "Equihash1927",
    "equihash1927":  "Equihash1927",
    "equihash210":  "Equihash2109",
    "equihash2109":  "Equihash2109",
    "equihash965":  "Equihash965",
    "equihashbtg":  "Equihash1445",
```
These are in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1979

**Comment by Dewbs** [comment]
My first post was " is there an algo file to use with this? "
I'll try that now you've linked it in the edit

**Comment by UselessGuru** [comment]
> My first post was " is there an algo file to use with this? "

Sorry, did see that, but I also remember having Commit 889dc37 in the first post too :-)

**Comment by UselessGuru** [comment]
Important: Requires https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2018

**Comment by paulpoco** [comment]
Trying the 144 and 192 on Zergpool and at least right now it is only using the 2nd GPU while Benchmarking, will have to check what it does on other Algos and report back if other Algos use both my GPUs.  Using all the PRs to do the new Equihash variants.
image

[EWBF2-GPU#00-GPU#01-42101_2018-07-21_14-56-14.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2216564/EWBF2-GPU.00-GPU.01-42101_2018-07-21_14-56-14.txt)
14:56:16 CUDA: Device: 0 GeForce GTX 1070 Not selected.
14:56:16 CUDA: Device: 1 GeForce GTX 1070, 8192 MB i:64

[EWBF2-GPU#00-GPU#01-42101_2018-07-21_15-09-25.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2216561/EWBF2-GPU.00-GPU.01-42101_2018-07-21_15-09-25.txt)
15:09:27 CUDA: Device: 0 GeForce GTX 1070 Not selected.
15:09:27 CUDA: Device: 1 GeForce GTX 1070, 8192 MB i:64



Benchmarking Xevan right now and using both GPUs.  Other non EWBF2 Miners use GPU0 and GPU1 fine. 
 Will try rebooting later to see if that helps.

Rebooted and deleted the hashrate files for 144 and 1932.

image
Still not using GPU 0.

**Comment by paulpoco** [comment]
@UselessGuru found an error in the command line for "--cuda_devices 01" needs to be "--cuda_devices 0 1"

image

**Comment by paulpoco** [comment]
@UselessGuru 
Change Line 57 to this and all GPUs will be used as --cuda_devices 0 1 2 3 4 5 etc:
                Arguments        = ("--algo $Algorithm$Pers --eexit 1 --api 127.0.0.1:$Miner_Port --server $($Pools.$Algorithm_Norm.Host) --port $($Pools.$Algorithm_Norm.Port) --user $($Pools.$Algorithm_Norm.User) --pass $($Pools.$Algorithm_Norm.Pass)$($_.Params)$CommonCommands --cuda_devices $(($Miner_Device | ForEach-Object {'{0:x}' -f ($_.Type_Vendor_Index)}) -join ' ')" -replace "\s+", " ").trim()

**Comment by paulpoco** [comment]
New algo added to Zergpool is equihash144btcz for BitcoinZ.

From Zergpool Discord
"@everyone BitcoinZ was added to  separate mining port. Please use following command line  "miner --algo 144_5 --pers BitcoinZ --server equihash144btcz.mine.zergpool.com --port 2148 --user BTCwallet" "

**Comment by paulpoco** [comment]
@UselessGuru you might want to read this from NemosMiner talking to @pinpin from ZergPool.
https://github.com/nemosminer/NemosMiner/issues/716
They are talking about deciding on names for the different Equihash variants and what @pinin is going to do on ZergPool.

**Comment by UselessGuru** [comment]
@paulpoco 

> Right now it is -join '') and needs to be -join ' ')

Thank you for the solution. I've updated the miner file. (https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2002/commits/701d9665632ce11c8569911294764c97cd846304)
I don't have multiple cards of the same type, so this was an easy to overlook stumbling stone.

**Comment by pinpins** [comment]
Hey folks, I see there is quite some discussion on naming convention. I don't mind we introduce something general. I see some looking for 1445 or 144_5, I do have only equihash144 at the moment.

**Comment by paulpoco** [comment]
@pinpins when i do http://api.zergpool.com:8080/api/status I don't see the "equihash144btcz"

screenshot_2

**Comment by paulpoco** [comment]
@UselessGuru I am trying to add equihash144btcz, this is what I tried so far but I think there is an issue with the ZergPool Api:

Add
	"equihash144btcz":  "Equihash1445BtcZ",
	"equihash1445btcz":  "Equihash1445BtcZ",
to algorithms.txt

Add
    #Define CoinNames for new Equihash algorithms
     ...................
     .........................
    if ($ZergPool_Algorithm -eq "Equihash144btcz") {$ZergPool_Coin = "BitcoinZ"}
to ZergPool.ps1

I get this error in the main MultiPoolMiner log:
INFO: Unable to determine divisor for BitcoinZ using Equihash144btcz algorithm

I am sure you know more, so I'll wait.

**Comment by pinpins** [comment]
BTCZ is in test mode, I have n't added it to API yet. We need to find first block.

Actually I also figured out mc= functionallity for Equihash. Which would make grouping under one Algo/port possible.

But then in Option 1 case. You would need to fetch new parameter "bestcoin" from API/status.

I will keep you informed whenever this will be impemented.

For now it is stratum port per coin

**Comment by grantemsley** [comment]
@pinpins I think, if I understand everything correctly, that leaving them as separate stratum ports might be the best idea for coins that require different settings.

Otherwise, the server will switch coins and everyone will mine with invalid settings, basically throwing away their hashing power, until they make their next API request and see the updated settings.  Right?

That seems bad for a bunch of reasons:
- We only update the pool APIs, at most, once per minute.  Usually a bit longer than that. Some people have it set much longer (like 1 hour).
- Currently, we assume that if the pool API doesn't return any data, but the stratum servers are up, that we can safely keep mining to the pool, and it's just the API that's down.  That wouldn't be the case anymore.
- Once in awhile the script to switch miners freezes or dies, but leaves the miners running.  At least right now, they are still mining and making money.  Wouldn't be the case if the pool switched coins.
- Not related to this project, but it would make it hard for anyone who isn't using an automatic switching program to use the pool.

It's kind of a mess either way, but if I'm understanding the implications correctly, I think it would be better off to list any that require different settings and miners can't seamlessly transition between as separate algorithms.

**Comment by UselessGuru** [comment]
@pinpins / @grantemsley 

> I was also thinking to contact EWBF 

Ideally we could have separate algo names for each variant, similar to CryptoNight.
This --pers just adds unneccessary .complexity.

**Comment by paulpoco** [comment]
@UselessGuru I don have access to EWBF2.ps1 yet because it hasn't been merged.  Ignore the bad spacing, you'll get the idea.

Change this section:

> $Commands = [PSCustomObject[]]@(
    [PSCustomObject]@{Algorithm = "Equihash-96_5"; MinMemGB = 2; Params = ""}
    [PSCustomObject]@{Algorithm = "Equihash-144_5"; MinMemGB = 2; Params = ""}
    [PSCustomObject]@{Algorithm = "Equihash-144_5BtcZ"; MinMemGB = 2; Params = ""}
    [PSCustomObject]@{Algorithm = "Equihash-144_5Zel"; MinMemGB = 2; Params = ""}
    [PSCustomObject]@{Algorithm = "Equihash-192_7"; MinMemGB = 3; Params = ""}
    [PSCustomObject]@{Algorithm = "aion"; MinMemGB = 2; Params = ""} #Aion uses Equihash 210_9. The miner adds pers 'AION0PoW'. Unfortunately --algo 210_9 is not (yet) supported

Then change this section:

> 
    $Coins = [PSCustomObject]@{
    "BitcoinGold" = " --pers BgoldPoW"
    "BitcoinZ"       = " --pers BitcoinZ" #https://twitter.com/bitcoinzteam/status/1008283738999021568?lang=en
    "Minexcoin"   = ""
    "SnowGem"    = " --pers sngemPoW"
    "Zero"             = " --pers ZERO_PoW"
    "ZeroCoin"      = " --pers ZERO_PoW"
    "ZelCash"     = " --pers ZelProof"
}

Then change this section to take off the letters past the 144_5:

>     
        $Algorithm = ($_.Algorithm) -replace "Equihash-" -replace "BtcZ" -replace "Zel"
        $Algorithm_Norm = Get-Algorithm $_.Algorithm
        $MinMemGB = $_.MinMemGB

**Comment by UselessGuru** [comment]
@paulpoco 

Your changes are not the way to go. I'm sorry.
See the changes I applied instead.

**Comment by paulpoco** [comment]
@UselessGuru FYI from Zergpool Discord Announcement channel, Equihash 144_5 going to single port with Auto-switching coin with EWBF version 0.5 August 6.  Not sure what needs to be done?
image

**Comment by pinpins** [comment]
Nothing much, equihash144 will be provided in status API like regular equihash. You just need to get 0.5 EWBF and specify --pers auto. We will be swapping coins as per profitability

**Comment by UselessGuru** [comment]
@pinpins 

> Hey folks, I see there is quite some discussion on naming convention. I don't mind we introduce something general. I see some looking for 1445 or 144_5, I do have only equihash144 at the moment.

Both numbers (before AND after the \_) should be part of the algo naming.
Equihash 144_5 and (hypthetical) 144_6 are totally different when it comes to resulting hash rates.

**Comment by paulpoco** [comment]
Anyone get Equihash-BTG to work with MultiPoolHubCoins?

**Comment by Dewbs** [comment]
EWBF Cuda Equihash Miner v0.6

v0.6
* Fixed situation where the api socket did not close during the exit..
* Increased time-outs during stratum authorization and subscription.
* 144_5, 192_7, 96_5 now faster.
* 144_5 now uses less vram, ~1.63GB (This should be useful for 2GB cards).

Windiws    https://mega.nz/#F!fsAlmZQS!CwVgFfBDduQI-CbwVkUEpQ
Linux        https://mega.nz/#F!3xYlSJDK!kG4kVLg1arbBuq1dd8u9aA

Linux        https://drive.google.com/open?id=1jUhXYysli_x6MH_wQ9lY07c68Ze7WM8g
Windiws   https://drive.google.com/open?id=1anfDRDVc_Fs_NceuZNuDK8HWZgcCdM3A

**Pull request closed without merging**
