### PR TITLE
Add Enemy 1.08 Miner by Zealot

### PR DESCRIPTION
**Pull request by mkirov0**
This miner does not have a GitHub page and has a Mega link instead. Dont know how you guys feel about these...
Please take a look at the algos structure. I started with the Tpruvot structure and tested all algos. Ive commented out the ones that are not supported. There are a few I couldn't test and noted that in the comment, but didn't want to prevent testing in case a pool supports them at some point. 

If you guys like it I can copy that algo structure to all ccminer forks and comment out the unsupported algos for each miner. I also think that renaming the miners to ccminerDevName would help with updates and adding future better miners which could outperform the ones that are algo specific for example. Let me know what you think and I can do that while going through the miners. 

This miner has a 1% fee and I know MPM takes that into account. I remember seeing it into the code, but couldn't find it when i needed it... If someone can help with that I'd appreciate it.

### CODE REVIEW

**Comment by symalla** [comment]
Can confirm it is faster for X16R, X16S and Bitcore. 

2018-04-20 08_51_32-_new 1 - notepad administrator

**Comment by grantemsley** [comment]
For cryptonight, is that only the original pre-monero-fork cryptonight?  Or does it support cryptonight v7 as well?

Having only a mega link where it can't be automatically downloading is irritating, but not a deal breaker - we already have a few miners like that.

At the moment, MPM doesn't take into account the dev fees of the miner.  We're working on that.  Same goes for a better naming scheme for the miners - @UselessGuru has been busy working on that, though it's not quite ready to merge yet.

**Comment by grantemsley** [comment]
Does this miner have a release page on bitcointalk or anywhere else?

**Comment by mkirov0** [comment]
The best I could find:
https://coinguides.org/z-enemy-v1-08/
http://cryptomining-blog.com/9745-new-faster-z-enemy-1-08-x16r-and-x16s-nvidia-gpu-miner-available/

**Comment by grantemsley** [comment]
I'm a little leary about including a miner where we can't even find a discussion thread by the author.  We've had problems before with a miner that was cheating (reporting higher hash rates than it really did), and that was only caught because people on bitcointalk made a big deal about it.  And in the absolute worst case a rogue miner could try to steal wallet files or other important stuff.

I'm not saying no, but I'd like to hear what others think first.  Thoughts @aaronsace and @UselessGuru?

**Comment by mkirov0** [comment]
I get your point, and its really something that hadn't occurred to me before as being possible, so thanks for letting me know its possible!😃 The hash rates are something I can track - compare what is reported by the miner and the pool and make sure they are at least close. As far as reporting hash-rates it performs great, but now after giving what you said a few min to sink in, I realized that reported hash-rates dont mean much... Lets put it on the back-burner for now and I will track hash-rates (pool and miner) and will report my findings. And people who want to test it on their own risk they can.

**Comment by aaronsace** [comment]
Would like to know where the binaries are coming from i.e. who/where is the developer online? Also, some user feedback i.e. is there a forum?

**Comment by grantemsley** [comment]
@mkirov0 It's definitely something to be concerned about - especially when you consider that (thanks to antivirus vendors not distinguishing between actual malicious programs and miners) most systems are running without antivirus or firewalls, or have whitelisted all the miner programs.

So a bad miner could do a lot of damage if it wanted to.

It's mostly up to the community to keep a close eye on miners to make sure they aren't doing anything they shouldn't, aren't lying about their dev fees or hash rates, etc.  So a miner with no community around it is something to be hesitant about.

**Comment by UselessGuru** [comment]
> Thoughts @aaronsace and @UselessGuru?

I do not have access to my rig so I cannot test.
I feel we should be careful with new and unknown miners. When a miner claims to be faster we should see that it is also faster at the pool.

**Comment by symalla** [comment]
They do have a bitcointalk page now

https://bitcointalk.org/index.php?topic=3378390.0;all

**Comment by mkirov0** [comment]
Thanks for adding this!

The 'Not Supported' comments are 100% tested result. I ran a little experiment on my test rig (1070) and discovered some miners did not have all algos enabled, but were performing great on them. I took me a week to do it, but did the following:

- Created an algo template from ccminerTpruvot and enabled all pool supported algos (currently)

- Copied the template to all ccminer forks (nevermore, zealot,klaust, etc.)

- Ran a test which algos they support and how they perform

- Went through logs and disabled all not supported algos for each miner

- Commented out all low performing miners and left top 3 for each algo

- After 3 days (180 sec interval) left the highest performing miners and commented out the rest

Discovered some interesting stuff... For example ccminerXevan and ccminerPolytimos are killing it at Lyra2RE2 😁 Again I'm testing it on a 1070, but can't imagine it would be much different on other NVIDIAs...

**Comment by grantemsley** [comment]
I added a download link on github.

**Comment by grantemsley** [comment]
Tested, miner works well.  Merged.

**Pull request merged**
