### PR TITLE
ClaymoreNvidia: Unified miner

### PR DESCRIPTION
**Pull request by UselessGuru**
## One miner file for all Claymore Dual Nvidia variants

One miner file replaces all individual miner files. The generated miner objects are backwards compatible.

### New dual mining algorithms or custom intensities
- New variants or different intensities can be added to $Commands, one entry = one miner object

Also read: https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1491

### Fixes

- Support for more than 9 devices: deviceIDs > 10 in hex "[Convert]::ToString($DeviceID, 16)"
- Improve pool compatibility: "$(if($Pools.Ethash.Name -eq 'NiceHash'){3}else{2})"

Also read: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1470

### 3gb Limitation

- By default Ethash uses only Cardswith 4GB VRAM, 3GB cards can no longer be used
- Ethash2gb parameter is still supported
- Ethash3gb parameter (future MPM enhncement) will use cards with > 3GB VRAM

Also read: https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1497
 
### Fee Calculation
(as discussed here: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1237)
- Miner fee(s) will be deducted from returned hashrate
- $MinerFeeInPercentSingleMode = 1.0
- $MinerFeeInPercentDualMode = 1.5
- Property 'fees' added to miner (array) so it can be used in core

Also read: https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1152

### CODE REVIEW

**Comment by grantemsley** [comment]
I don't have access to a system with the right hardware to test it at the moment...what happens if your system has 2 nvidia cards, one with >=4GB and one with 3GB?  Looks like it will benchmark them separately, with the 3GB card sitting idle when it tries ones that require more than 3GB, and both running for ethash3gb?

That's probably the best we can do without doing separate miners per card.

**Comment by UselessGuru** [comment]
> a system with the right hardware to test 

Nor do I. I just sold my 3GB 1060 :-)

> Looks like it will benchmark them separately

True, There will be one miner object per line in $Commands.
It is the main algorithm variant defines which cards will be used. 
- Ethash2gb will always use all cards
- Ethash will only use cards > 4000000000 VRAM (I don't wat to use n^2, some cards steal some visible memory), the other cards sit idle

If we go for separate miners per card then this is not an issue.
FYI: All miners in newpoc are already 'separate miners per card' ready :-)

**Comment by aaronsace** [comment]
What about AMD???

Please don't merge any more complex miner files. We should start moving to JSON with a GUI.

**Comment by grantemsley** [comment]
@aaronsace I'm not quite following - how does having the GUI make using JSON files make more sense?  One of the advantages of using scripts for the miners is that those scripts can tell the GUI what configuration they need.  We don't get that flexibility with JSON files.

**Comment by UselessGuru** [comment]
> What about AMD???

AMD is the works.

> We should start moving to JSON

 Grant and me are lost. How would you handle the Claymore miner more efficiently.
Please give us some guidance - are real life example would be best.

**Pull request merged**
