### PR TITLE
Miner Performance Cleanup

### PR DESCRIPTION
**Pull request by Rama-Nujan**
This is built based on the Miner Leaderboard spreadsheet. The sheet allows you to select some miners for each architecture. The miner file tab allows you to see which algos should be present for each of the miner files. 

**I have not benchmarked the latest Alexis and Zealot miners** but figured you might wanna get a head start.

I also don't own AMD cards - so cannot help with those.

What do you think?

### CODE REVIEW

**Comment by mkirov0** [comment]
Personally I love it!

**Comment by jestercore** [comment]
Yes, i think MPM needs cleanup. No more ethminer, eminer, sgminer, and this kind of old or abandoned miners.

**Comment by jestercore** [comment]
For me CcminerSkunk is fastest for some 1060 on Skunk algo

**Comment by Rama-Nujan** [comment]
Ok. We can have a running tally per card if we notice too many discrepancies within the same architecture. But I need to know if the devs are on board with this, otherwise it's to be scrapped.

**Comment by grantemsley** [comment]
Has conflicts with claymore and excavator now, from removing the custom syntax.

This would be a LOT easier to review if you made PRs like this in smaller chunks, just changing 1 or 2 miners at a time.  But I'll see what I can do.

**Comment by Rama-Nujan** [comment]
Hi - I can do that no problem: it's easier for me aswell.

**Pull request closed without merging**
