### PR TITLE
Update Include.psm1, Added Background start script

### PR DESCRIPTION
**Pull request by ifs0001**
fix Get-Balance , it shows  values not correctly  when -ShowPoolBalances and -ShowPoolBalancesDetails options are enabled.

Split start.bat in two scripts, for run multipoolminer automatically at startup without to  have to login or autologin.  
To run multipoolminer at Windows startup also with user with password:
-Add Start_background.bat to task scheduler in order to automatically run multipoolminer at windows startup.
-Add Start_log.bat in shell:startup to see logs when log in the user account.

### CODE REVIEW

**Comment by UselessGuru** [comment]
> fix Get-Balance , it shows values not correctly when -ShowPoolBalances and -ShowPoolBalancesDetails options are enabled.

With what version did you have this issue?

**Comment by ifs0001** [comment]
> 
> 
> > fix Get-Balance , it shows values not correctly when -ShowPoolBalances and -ShowPoolBalancesDetails options are enabled.
> 
> With what version did you have this issue?

MultiPoolMiner 3.0.1a and previous 3.0.1 , but I see that the code is always the same in the repository.
I use PowerShell 6 , but also with stock Windows 10 powershell it happens.

**Comment by UselessGuru** [comment]
@ifs0001 

Does the issue still happen with 3.1.0 Beta 11?
What currency settings do you have configured in Windows and for MPM. Would you mind posting your MPM config file?

**Comment by ifs0001** [comment]
The Issue is still present in 3.1.0a
immagine

**Comment by UselessGuru** [comment]
@ifs0001 

I think the formatting gets mixed up because your rig uses a comma (,) as decimal separator. The running code expects a dot (.)
A (possible) fix will be implemented in the next version (3.2.0 Beta 3)

**Pull request closed without merging**
