### PR TITLE
GUI for MultiPoolMiner. DO NOT MERGE. For feedback only.

### PR DESCRIPTION
**Pull request by grantemsley**
Don't merge this.  The setup GUI and logging need to be merged first and this rebased off those first.  But I want to get some feedback on it now.

This is the GUI launcher I've created:

gui

## Features

- Written entirely in powershell
- Gets and displays balances from pools, and shows them in up to 3 different currencies.
- Shows which miners are active and their stats.
- Can launch the GUI setup program, show the table of benchmarks for all miners, and reset benchmark and profit data.
- Can start mining when the system is idle.  This was my main motivation for writing this - coming from NiceHash to MultiPoolMiner, that was the biggest feature I missed.  If you manually click the start mining button, it will continue mining no matter what.  But if Start when idle is checked, it will automatically start mining when you leave the computer (after the preset delay) and stop when you come back.
- Shows current exchange rates
- I figured out how to hide the powershell window that launches it!

## Known Issues
- I have only written balance checking scripts for 4 of the pools.
- MultiPoolHub is special for balances in that it gives you an amount in the altcoin you are mining, not the equivelent BTC like the other pools do.  To fix that, I have the script get and cache exchange rates from Bittrex.  This covers most of the coins MPH does, but not all of them.

Aside from my other pull requests (#853 and #802) this requires very little change to MultiPoolMiner.ps1 - just a few lines for exporting some of the variables on each loop, and a few added functions in Include.psm1 for balance checking.

So please, test it out, let me know what you think of it, if anything is broken, and any other features you'd like to see!

### CODE REVIEW

**Comment by UselessGuru** [comment]
Hi Grant

Looks very good! But the following things do not work for me (yet):

I dld your zip into an empty folder (c:\Program Files\CryptoMining\MultiPoolMiner-patch-gui\) - I DO have full access here!

- Setup-Button: I quickly see a minimized PS session, nada!
- Start mining: I quickly see a minimized PS session, nada! But it says running :-(

I didn't dare resetting either stats nor profit. Will there be a confirmation dialog?

I very much like the benchmark overview which brings me to an interesting possible feature for the future:
We need a way to disable all but the fastest miner per algo.
One possible solution: use your GUI, and allow user to disable algo per miner.
Or even better: have a button that does it all.
Implementation: when user click disable add a 'disabled' flag to the stat file. MPM will then not use them
The disabled benchmarks should of course still remain visible (flagged 'disabled') and the must be an option to re-enable them.

What edition of Visual Studio do I need to edit the GUI?

**Comment by grantemsley** [comment]
Try it in a directory with no spaces.  Might have not escaped things right.

Yes, there is a confirmation before resetting anything.

I like the idea for editing which miners to use.

I sometimes use visual studio 2017 community edition to edit the gui's xaml file.  Start a new WPF project and copy/paste the entire xaml file in.  Edit then copy back.  Mostly I just edit in a text editor though.  VS just does the interface, the coding behind it is all in the PowerShell script.

**Comment by UselessGuru** [comment]
Regarding Visual Studio
I ment which workloads or individual components do I need to install?

**Comment by grantemsley** [comment]
.Net Desktop development.

**Comment by Sniffle** [comment]
as an idea for maybe a separate tab, maybe list the algorithms and what was calculated as most profitable.  so that we can possibly have a bit of accountability and visual double checking, instead of just blind trust that the math is correct without any question.  

as an example currently, I'm currently mining musicoin on my 2 rx580, when ethereum you would think would technically be more profitable as the value of musicoin has dropped roughly .03 or 22%% in the last 3 days, while today ethereum has risen 61.81 or 5.19% as of the time of writing this post.  

even with the keep mining algorithm weight helping musicoin to continue mining at some point you would think that eth would be the coin i would by mining by the 3rd day.  thus some type of visual accountability would be nice.

**Comment by fonyo** [comment]
What is your idle trigger based on and what is the threshold?

**Comment by grantemsley** [comment]
@fonyo I'm not sure if I understand the question.  It uses the same idle timer windows uses for the screensaver and such.  You set the delay in the GUI under the buttons.

**Comment by kevharper** [comment]
Looks really nice!  Looking forward to giving it a try!

**Comment by robl45** [comment]
Is it possible to test this and if so, where do I get the zip file?

**Comment by grantemsley** [comment]
@robl45 it's still a work in progress, and not yet compatible with the current release.  But it will be soon.

You could download the branch this PR is based on, but it would be missing a lot of new features and fixes so I wouldn't recommend it just yet.

**Comment by JimKnightster** [comment]
Suggestion:  Have it refresh the Show Benchmarking Info screen when it starts a new benchmark?

**Comment by JimKnightster** [comment]
Really like the direction here.  Please but a button on your GUI to show the miners while they mine, I use the Miner window to tune the miner and I know there are a lot of folks that would like to see them as well.

**Comment by grantemsley** [comment]
@JimKnightster showing the miner's logs in the GUI is definitely in the works.  You won't be able to interact with the miner windows though.  They run as PowerShell jobs now and there is no longer any way to show their actual window, just the text they output.

**Comment by JimKnightster** [comment]
Thats a bummer, I knew they were converted to Jobs, but thought it was being added back in version 3, I used them when I first started with MPM to tune the DCRI values in the claymore miners and then created another mining config for a specific dual mining command line.  Oh well cant have everything I guess, still like the gui and setup.

**Pull request closed without merging**
