### PR TITLE
NVIDIA-Bminer version 10.4.0: enable per device mining, support for 144,5 coins

### PR DESCRIPTION
**Pull request by paulpoco**
Release notes

10.2.0

Support all the other Equihash 144,5 based coins besides BTG, using equihash1445 scheme and -pers config.

10.1.0

Fix performance regression in BTM mining.

10.0.0

Support mining Zhash (Equihash with parameter set 144,5) based coins.
Substantially increase BTM mining speed again (up to another 30%).
Support reported hashrate feature on ETH pools.

### CODE REVIEW

**Comment by Dewbs** [comment]
Requires mod for equihash1445 coins as per ewbf2 ? ps1 as it stands only supports Zhash

**Comment by paulpoco** [comment]
@UselessGuru some info from the "Bin" folder for Bminer.

REM ================================================================
REM Change pers according to the coin you want to mine. For example:
REM Coin:         Pers
REM BitcoinZ:     BitcoinZ
REM Safe Coin:    Safecoin
REM ZelCash:      ZelProof
REM SnowGem:      sngemPoW
REM Bitcoin Gold: BgoldPoW
REM ================================================================

**Comment by UselessGuru** [comment]
@paulpoco 

Added -pers config. Please test and report back. Thank you very much!

**Comment by Dewbs** [comment]
Hmmm:


[INFO] [2018-09-04T18:14:31+01:00] Accepted share #5                            
[INFO] [2018-09-04T18:14:36+01:00] Received new job d0a9                        
[INFO] [2018-09-04T18:14:38+01:00] Received new job d0dc                        
[INFO] [2018-09-04T18:14:38+01:00] Subscribed to stratum server                 
[WARN] [2018-09-04T18:14:38+01:00] Get error: Invalid response from the stratum server: true, resetting in 5 seconds 
[INFO] [2018-09-04T18:14:43+01:00] Connected to equihash144.mine.zergpool.com:2146 
[INFO] [2018-09-04T18:14:43+01:00] Subscribed to stratum server                 
[INFO] [2018-09-04T18:14:43+01:00] Set nonce to 7fffff06                        
[INFO] [2018-09-04T18:14:43+01:00] Set target to 0000000000000000000000000000000000000000000000000000000000001000 
[INFO] [2018-09-04T18:14:43+01:00] Received new job d0a9                        
[INFO] [2018-09-04T18:14:43+01:00] Authorized                                   
[INFO] [2018-09-04T18:14:47+01:00] [GPU 2] Speed: 21.39 Sol/s 10.69 Nonce/s Temp: 74C Fan: 74% Power: 79W 0.27 Sol/J 
[INFO] [2018-09-04T18:14:48+01:00] Total 21.39 Sol/s 10.69 Nonce/s Accepted shares 1 Rejected shares 0 
[INFO] [2018-09-04T18:15:08+01:00] Received new job d0dc                        
[INFO] [2018-09-04T18:15:08+01:00] Subscribed to stratum server                 
[WARN] [2018-09-04T18:15:08+01:00] Get error: Invalid response from the stratum server: true, resetting in 5 seconds 
[INFO] [2018-09-04T18:15:13+01:00] Received new job d0dd                        
[INFO] [2018-09-04T18:15:13+01:00] Connected to equihash144.mine.zergpool.com:2146 
[INFO] [2018-09-04T18:15:13+01:00] Subscribed to stratum server                 
[INFO] [2018-09-04T18:15:13+01:00] Set nonce to 18000107                        
[INFO] [2018-09-04T18:15:13+01:00] Set target to 0000000000000000000000000000000000000000000000000000000000001000 
[INFO] [2018-09-04T18:15:13+01:00] Received new job d0a9                        
[INFO] [2018-09-04T18:15:13+01:00] Authorized                                   
[INFO] [2018-09-04T18:15:17+01:00] [GPU 2] Speed: 20.97 Sol/s 10.66 Nonce/s Temp: 73C Fan: 74% Power: 61W 0.34 Sol/J 
[INFO] [2018-09-04T18:15:18+01:00] Total 20.97 Sol/s 10.66 Nonce/s Accepted shares 1 Rejected shares 0

**Comment by Dewbs** [comment]
...along with:

image

**Comment by UselessGuru** [comment]
@Dewbs 

As much as would like to help you :-)
This is a miner problem (which I have not noticed yet) and needs to be reported to the miner authors.

**Comment by paulpoco** [comment]
Works fine. 

Was only able to test with 2x1070:
Bminer-Ethash-Nicehash and PhoniexMiner(about 2 others too) is faster.
Bminer-Equihash-Zergpool is the fastest of Equihash miners.

Bminer-Equihash1445 benchmarked with 75 as the value but later is not showing up on the list of miners.  Deleting the hashrate file to try again.

**Comment by UselessGuru** [comment]
@paulpoco 

??? Why should it bench anything with 75? There is no reference to that in the code. I've disabled all DualMining with statically set secondary intensity.
However I left DualMining with auto dual solver and intensity enabled.

**Comment by paulpoco** [comment]
@uselessguru when said 75 I meant the hashrate was 75MH/s and that I deleted the Bminer-Equihash1445 hashrate file.  And that never got benchmarked again even after restarting MPM

**Comment by Kettoch** [comment]
There is something not being passed right and I get an overall hashrate but no actual hashrates inside the file.  So it comes back with zero profit.
[MultiPoolMiner_2018-09-25.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2417107/MultiPoolMiner_2018-09-25.txt)
[NVIDIA-Bminer-Equihash1445-GPU#00-GPU#01-4000_2018-09-25_17-10-03.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2417108/NVIDIA-Bminer-Equihash1445-GPU.00-GPU.01-4000_2018-09-25_17-10-03.txt)
[MultiPoolMiner_2018-09-25_17-09-29.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2417109/MultiPoolMiner_2018-09-25_17-09-29.txt)
[NVIDIA-Bminer-Equihash1445-GPU#00-GPU#01_Equihash1445_HashRate.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2417112/NVIDIA-Bminer-Equihash1445-GPU.00-GPU.01_Equihash1445_HashRate.txt)

**Comment by Dewbs** [comment]
Release notes

10.4.0

Add `-pers auto` option to support pools (e.g. zergpool.com) to automatically switch personalization string for equihash144,5 mining.

https://bitcointalk.org/index.php?topic=2519271.0

**Comment by Dewbs** [comment]
Just tried this update - downloaded but is only benching Ethash, none of the Equi varients ?

**Comment by UselessGuru** [comment]
@Dewbs 

There was a bug... can you please try the updated version:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2147/files

**Comment by Dewbs** [comment]
Treid https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2147/files
Still nothing other than Ethash (?)

**Comment by UselessGuru** [comment]
Included in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2189

**Pull request closed without merging**
