### PR TITLE
Excavator: Fix device enumeration

### PR DESCRIPTION
**Pull request by UselessGuru**
Fix for https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1840 and https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1851

### CODE REVIEW

**Comment by grantemsley** [comment]
This should work...but may not be the right way to fix it.  It'll work for most people, but might break with some device combinations.

I'd be really interested in seeing the devices output from someone who has this problem.

**Comment by grantemsley** [comment]
Ok, based amolitor's devices.txt from #1851, Type_PlatformId_Index isn't being generated properly.  It's being reset to 0 for each card.

Lets fix that instead, since it will definitely affect other miners where getting the Type_PlatformId_Index right is essential (AMD miners, where CPUs are sometimes under the AMD platform).

**Comment by UselessGuru** [comment]
> I don't think this fix is correct; 'Type_PlatformId_Index' excludes the CPUs but 'PlatformId_Index' does not.

Type_PlatformId_Index is broken.

**Comment by grantemsley** [comment]
#1867 fixes Type_PlatformId_Index

**Comment by UselessGuru** [comment]
Fix is in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1870

**Pull request closed without merging**
