### PR TITLE
ExcavatorNHMP (Excavator version 1.5.5a for Nicehash only)

### PR DESCRIPTION
**Pull request by UselessGuru**
Replaces #1845

### CODE REVIEW

**Comment by Kettoch** [comment]
This version is giving me all kinds of CUDA errors.

[Excavator-5400_2018-06-23_20-03-49.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2130342/Excavator-5400_2018-06-23_20-03-49.txt)
[Excavator-5400_2018-06-23_20-05-06.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2130343/Excavator-5400_2018-06-23_20-05-06.txt)

[Excavator-5400_2018-06-23_20-06-22.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2130345/Excavator-5400_2018-06-23_20-06-22.txt)

**Comment by UselessGuru** [comment]
@Kettoch 

Could you please post http://localhost:3999/devices?

Note:  you need all these fixes for the device enumeration to work properly:

https://github.com/MultiPoolMiner/MultiPoolMiner/commit/4eee162154cca37aa83a014df8ab857b84b82dbd
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/525aeb175a3af8a9a226b777731a039b1cbee979
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/eff4f4a81bc9cab1356771cd4998c3e74eb2a1c5

**Comment by Kettoch** [comment]
[devices.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2131037/devices.txt)

The changes in the first one had been applied.  The changes from the second one had not fully been applied and the third one had not, however it is for a completely different miner.  I have not seen changes in it outside of its miner.  So it may not be relevant but it is now there.

With all of this work towards version three, it can be difficult finding a cohesive set of changes being made to some of the core files.

TBH, there would be too many changes to be made if took a current master and just plopped in my current config.txt.

However, I do the best I can as people point things out.  I am testing now.  I will let you know shortly.

**Comment by Kettoch** [comment]
With all of these changes, I have had some new things.  Some of the new miners works, a pascal failed another pascal cause a BSOD.
Here is the devices.txt after all of those changes
[devices.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2131061/devices.txt)
This is the first miner.
[Excavator-5400_2018-06-24_13-52-05.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2131063/Excavator-5400_2018-06-24_13-52-05.txt)
Here are the logs at the time of the BSOD.
[Excavator-5400_2018-06-24_14-02-48.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2131064/Excavator-5400_2018-06-24_14-02-48.txt)
[MultiPoolMiner_2018-06-24.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2131065/MultiPoolMiner_2018-06-24.txt)

Since it cause a BSOD. I am saving my comment now and adding the logs of any other miners that fail as edits.

**Comment by Kettoch** [comment]
Ok, with 1.5.5a downloaded this is much more stable.  Giving it some more time, now.

**Comment by UselessGuru** [comment]
@kettoch:

Devices look OK now.
BSOD errors are not related to MPM code. All parameters passed to the miner look OK.

**Comment by Kettoch** [comment]
I am using the files from this pull request. and it does have that line.  And it still runs and receives the out of memory error.

**Comment by UselessGuru** [comment]
I cannot reproduce your problem. I take the input of the supplied Devices.txt, and the miner file will NOT mine CryptonightV2 in dual thread mode???

Did you restart MPM after replacing the miner file?

Please do this:
1. Stop MPM
2. Move all miners files except ExcavatorNHMP to a different folder
3. Start MPM
4. When it start mining please fetch 
 - http://localhost:3999/miners

**Comment by Dewbs** [comment]
Sorry now confused as to how to get this working.
Using branch UselessGuru-ExcavatorNHMP the miner doesn't start (diff version of mpm ps1 required?)

**Comment by UselessGuru** [comment]
The miner works well with the current latest zip file of MPM.
All thats needed are the two files (1x API & 1x MinersLegacy).

If it does not start then you have a local problem.

**Comment by Dewbs** [comment]
Eh I'm not sure then - I think that's what I was effectively on but have just replaced MultiPoolMiner.ps1, include & nicehash pool file from current master. Still no action

**Comment by UselessGuru** [comment]
@Dewbs 
You are actually right, this miner also need a changed nicehash pool file. I'll rework this change - stay posted.

**Comment by DarenDaigle** [comment]
Is this a dead change, @uselessguru?

**Comment by Kettoch** [comment]
With the latest version of master (as of today) I am unable to integrate this change into the master code.

I had great success with this.  Will you be reworking this soon?

**Pull request closed without merging**
