### PR TITLE
Algorithm.txt for CryptoNight & Equihash variants

### PR DESCRIPTION
**Pull request by UselessGuru**
### **Help appreciated!!!**

I tried to put together a list of all available CryptoNight algo variants and put them together in one file. XmRig & FireIce, SRB-miner, as well as other CryptoNight miners use different algo names for the same algos which make a common algorithm.txt a hell of a task :-(

**Important: A complete algorithm.txt with all cryptonight variants is a prerequisite to get new miners working properly.**

I tried NOT to include coin names, since the pools should always return an algo name and an optional coin name as separate property.

I am looking for assistance to verify:
- the completeness of all available variants in algorithm.txt
- the correctness of the mapping of all variants, we must make sure that we end up with as few normalized algorithms (Get-Algorithm) as possible

Relevant links:
https://github.com/xmrig/xmrig-proxy/blob/master/doc/STRATUM_EXT.md#14-algorithm-names-and-variants
https://github.com/fireice-uk/xmr-stak
https://bitcointalk.to/index.php?topic=3167363.0

**Available algos per miner and what they get mappet to by Get-Algorithm**

SRB miner
```
alloy #CryptoNightAlloy
artocash #CryptoNightArto
b2n #CryptoNightB2N
bittubev2 #CryptoNightBitTubeV2
fast #CryptoNightFast
lite #CryptoNightLite
haven #CryptoNightHaven
heavy #CryptoNightHeavy
italo #CryptoNightItalo
marketcash #CryptoNightMarketCash
normalv7 #CryptoNightV7
stellitev4 #CryptoNightXtl
```
The code in SRBMiner uses 'Get-Algorithm "cryptonight$($Algorithm)"' to build the algo names, e.g. normalV7 -> cryptonightnormalv7 -> CryptoNightV7

XmRig (CPU/AMD/NVIDIA)
```
cryptonight/1 #CryptoNightV7; Also known as monero7 and CryptoNightV7
"cryptonight/xtl #CryptoNightXtl; Stellite (XTL)
cryptonight/msr #CryptoNightFast; also known as cryptonight-masari
cryptonight/xao #CryptoNightAlloy; XAO
cryptonight/rto #CryptoNightArto; RTO
cryptonight-lite #CryptoNightLite; Autodetect works only for Aeon
cryptonight-lite/0 #CryptoNightLite; Original/old CryptoNight-Lite
cryptonight-lite/1 #CryptoNightLiteV7; Also known as aeon7
cryptonight-lite/ipbc #CryptoNightIpbc; IPBC variant, obsolete
cryptonight-heavy #CryptoNightHeavy; Ryo and Loki
cryptonight-heavy/xhv #CryptoNightHaven; Haven Protocol
cryptonight-heavy/tube #CryptoNightHeavyTube; BitTube (TUBE)
```

FireIce (CPU/AMD/NVIDIA)

```
cryptonight_v7" #CryptoNightV7
cryptonight_v7_stellite" #CryptoNightXtl
cryptonight_haven" #CryptoNightHaven
cryptonight_heavy" #CryptoNightHeavy
cryptonight_lite" #CryptoNightLite
cryptonight_lite_v7 #CryptoNightLiteV7
cryptonight_lite_v7_xor #CryptoNightLiteIpbc
cryptonight_masari #CryptoNightFast
```

### CODE REVIEW

**Comment by paulpoco** [comment]
"cryptonightb2n":  "CryptoNightB2N",
"cryptonightv3":  "CryptoNightV3",
"cryptonightv8":  "CryptoNightV8",
"graft": "CryptoNightV8",
"cryptonightfast":  "CryptoNightFast",

Not sure if the above is valid?

**Comment by paulpoco** [comment]
"cryptonightlitev7":  "CryptoNightLiteV7", [is there right now]

Cast XMR calls it CryptoNightV7-Lite.
So add this too: "cryptonightv7lite":  "CryptoNightV7Lite",  ?

CryptoNightV7Lite makes more sense as it is CryptoNightV7 subset Lite.

**Comment by paulpoco** [comment]
"cryptonightxhvheavy":  "CryptoNightHeavyXhv", [is there right now]

Cast XMR calls it CryptoNightXHV-Heavy.
So add this too or instead: "cryptonightxhvheavy":  "CryptoNightXhvHeavy", ?

CryptoNightXhvHeavy makes more sense as it is used that way in Cast XMR?

**Comment by paulpoco** [comment]
I am working on MultiPoolMiner/MinersLegacy/Cast.txt and am using the names used in cast_xmr-vega.

So my code needs these:
Algo 1 "cryptonightv7":  "CryptoNightV7",
Algo 2 "cryptonightheavy":  "CryptoNightHeavy",
Algo 3 "cryptonightlite":  "CryptoNightLite",
Algo 4 "cryptonightv7lite":  "CryptoNightV7Lite",
Algo 5 "cryptonighttubeheavy":  "CryptoNightTubeHeavy",
Algo 6 "cryptonightv7stellitev4":  "CryptoNightXtl",
Algo 7 "cryptonightxhvheavy":  "CryptoNightXhvHeavy",
Algo 8 "cryptonightfast":  "CryptoNightFast",

**Comment by angelics** [comment]
imo. algorithm.txt is too bloated with unused, unsupported(in pool/miner). why do we need to add them now?
eg. `"anime":  "Anime",
    "animecoin":  "Anime",
    "argon2crds":  "Argon2dCRDS",
    "argon2DYN":  "Argon2dDYN",
    "argon2UIS":  "Argon2dUIS",
    "argon2":  "Argon2",
    "argon2coin":  "Argon2",
    "argon2d250":  "Argon2dCRDS",
    "argon2d4096":  "Argon2dUIS",
    "argon2d500":  "Argon2dDYN",
    "axiom":  "Axiom",`

**Comment by paulpoco** [comment]
"cryptonightheavytube":  "CryptoNightHeavyTube"

**Comment by mkirov0** [comment]
please consider adding aergo: AeriumX to Algorithms.txt

**Comment by paulpoco** [comment]
XmRig (CPU/AMD/NVIDIA) is now 2.6.4 from 3 days ago. [ipbc now replaced by tube]

Changes
#700 cryptonight-lite/ipbc replaced to cryptonight-heavy/tube for Bittube (TUBE).
Added cryptonight/rto (cryptonight variant 1 with IPBC/TUBE mod) variant for Arto (RTO) coin.
Added cryptonight/xao (original cryptonight with bigger iteration count) variant for Alloy (XAO) coin.
Better variant detection for nicehash.com and minergate.com.
#692 Added support for specify both algorithm and variant via single algo option.

And rto and xao look like original crptonight variants will only be good for ASIC.

**Comment by UselessGuru** [comment]
To be continued in 
- https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2018 (Equihash)
- https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2019 (CryptoNight)

**Pull request closed without merging**
