### PR TITLE
Add YiiMP Pool and Keccakc Algo

### PR DESCRIPTION
**Pull request by jakewarren81**
Added Keccakc algo.

Added support for mining at YiiMP.  It is fully functioning and I'm currently using it on multiple rigs.  It works well with the SwitchingPrevention adjustments recently added.  Requires entering Wallet addresses for each coin you want to mine.

I'm considering moving the wallets to a separate file, which may also help support other features like zpool custom payouts, etc and also make it easier when updating the package.

### CODE REVIEW

**Comment by aaronsace** [comment]
I will not add this unless the core code is updated to support multiple wallets.

**Comment by UselessGuru** [comment]
Where do you set that you reference '$YiiMP_Wallets.$YiiMP_Coin' in the miner?

**Comment by jakewarren81** [comment]
Here:  $YiiMP_Coin = Get-Algorithm $YiiMP_Request.$_.name

$YiiMP_Coin is set from the API request for each coin within it.  That value matches the name of the item in $YiiMP_Wallet that correlates to the Wallet address.

**Comment by UselessGuru** [comment]
> $YiiMP_Wallet that correlates to the Wallet address.

$YiiMP_Wallet**s**.$YiiMP_Coin (plural)
But how will you get it filled with value? The line 
`$NewPools = Get-ChildItemContent "Pools" -Parameters @{Wallet = $Wallet; UserName = $UserName; WorkerName = $WorkerName; StatSpan = $StatSpan} | ForEach-Object {$_.Content | Add-Member Name $_.Name -PassThru}` int the main routine is passing the values along to the miner. This does not allow for the information you need.

**Comment by platinum4** [comment]
yiimp.eu and zpool.ca I think run from the same; the yiimp.eu API is always down no matter how I tried to call it

**Comment by jakewarren81** [comment]
I'm using this pool file, its fully functional with no other modifications.

This API address responds without issue:
http://api.yiimp.eu/api/currencies

**Comment by aaronsace** [comment]
This will be included in an upcoming config file update.

**Pull request closed without merging**
