### PR TITLE
Revert "Include NetSecurity and Defender modules in main script"

### PR DESCRIPTION
**Pull request by aaronsace**
Reverts MultiPoolMiner/MultiPoolMiner#1373

### CODE REVIEW

**Comment by grantemsley** [comment]
Can you test leaving the includes in multipoolminer.ps1 but going back to the full path?

I'm very curious why it's failing on some systems.

**Comment by aaronsace** [comment]
@grantemsley If you run this in PowerShell 6, does it work? 

```
Import-Module NetSecurity
Import-Module Defender
```

**Comment by UselessGuru** [comment]
> Import-Module NetSecurity
> Import-Module Defender

Does not work for me (Win10 16299.257).

But this works.
Import-Module  $env:Windir\System32\WindowsPowerShell\v1.0\Modules\NetSecurity\NetSecurity.psd1
Import-Module $env:Windir\System32\WindowsPowerShell\v1.0\Modules\Defender\Defender.psd1

**Comment by grantemsley** [comment]
Using the full path doesn't work on Server 2012R2, but just the name does.  Probably not a very common use case though.

I think it was working without the full path for me because I was using PowerShell 5 not PowerShell core.  Turns out PowerShell Core uses a different default modules directory since it's not always compatible with PS5 modules.

I guess I'd recommend to go back to using the full path - but leave it moved to the main script so they don't keep getting imported for tons of things that dont use them - that was the more important part of the change.  Will still break on Server 2012 but I'm probably the only one who cares about that.

**Pull request merged**
