### PR TITLE
Update to Version 3.0.1

### PR DESCRIPTION
**Pull request by UselessGuru**
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/3.0.1

**To download the complete set of files [click here](https://github.com/MultiPoolMiner/MultiPoolMiner/releases/download/3.0.1/MultiPoolMiner_3.0.1_Release.zip).**

### CODE REVIEW

**Comment by Dewbs** [comment]
Get-CommandPerDevice : The term 'Get-CommandPerDevice' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\MPM\MinersLegacy\NVIDIA-CcminerDumax.ps1:38 char:24
+         $Commands.$_ = Get-CommandPerDevice $Commands.$_ $Miner_Devic ...
+                        ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-CommandPerDevice:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

**Comment by Dewbs** [comment]
Also same message for NVIDIA-CcminerPigeonCoin.ps1

**Comment by Dewbs** [comment]
ExcavatorNHMP still not downloading for me.
Bminer seems to be 'fixed' for me now in that it is benching Equi.

**Comment by Dewbs** [comment]
"Add '-CreateMinerInstancePerDeviceModel' switch (see readme)"

Prob being blind but can't find info ?

looking through https://raw.githubusercontent.com/MultiPoolMiner/MultiPoolMiner/MultiPoolMiner_3.0.1/README.txt

**Comment by Dewbs** [comment]
please add

    "lbk3":  "lbk3",

to Algorithms.txt (cryptodredge miner)

    "lbk3"      = "" #lbk3

**Comment by Dewbs** [comment]
NHMP does now download but fails unfortunately:

2018-10-07 09:49:20 INFO: Starting miner (NVIDIA-ExcavatorNHMP-1x-1): 'C:\MPM\Bin\NVIDIA-ExcavatorNHMP\excavator.exe [{"id":1,"method":"subscribe","params":["nhmp.eu.nicehash.com:3200","34My6PQ6A5pe7DisxR441pQnJD3SrznSRo.Z87-MPM"]},{"id":1,"method":"algorithm.add","params":["equihash"]},{"id":1,"method":"workers.add","params":["alg-equihash","2"]}]'
2018-10-07 09:49:47 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:49:50 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:49:52 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:49:54 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:49:57 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:49:57 INFO: Starting miner (NVIDIA-ExcavatorNHMP-1x-1): 'C:\MPM\Bin\NVIDIA-ExcavatorNHMP\excavator.exe [{"id":1,"method":"subscribe","params":["nhmp.eu.nicehash.com:3200","34My6PQ6A5pe7DisxR441pQnJD3SrznSRo.Z87-MPM"]},{"id":1,"method":"algorithm.add","params":["equihash"]},{"id":1,"method":"workers.add","params":["alg-equihash","1"]}]'
2018-10-07 09:49:59 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:50:01 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:50:04 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:50:06 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:50:08 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:50:08 INFO: Starting miner (NVIDIA-ExcavatorNHMP-1x-1): 'C:\MPM\Bin\NVIDIA-ExcavatorNHMP\excavator.exe [{"id":1,"method":"subscribe","params":["nhmp.eu.nicehash.com:3200","34My6PQ6A5pe7DisxR441pQnJD3SrznSRo.Z87-MPM"]},{"id":1,"method":"algorithm.add","params":["equihash"]},{"id":1,"method":"workers.add","params":["alg-equihash","0"]}]'
2018-10-07 09:50:10 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:50:13 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:50:15 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:50:17 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1). 
2018-10-07 09:50:20 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1x-1).

**Comment by Dewbs** [comment]
aha!  

image

**Comment by Dewbs** [comment]
Now seems to be running but not correctly:

2018-10-07 09:58:29 INFO: Starting miner (NVIDIA-ExcavatorNHMP-1x-2): 'C:\MPM\Bin\NVIDIA-ExcavatorNHMP\excavator.exe [{"id":1,"method":"subscribe","params":["nhmp.eu.nicehash.com:3200","34My6PQ6A5pe7DisxR441pQnJD3SrznSRo.Z87-MPM"]},{"id":1,"method":"algorithm.add","params":["lyra2rev2"]},{"id":1,"method":"workers.add","params":["alg-lyra2rev2","2","alg-lyra2rev2","2"]}]'
2018-10-07 09:58:37 INFO: Starting miner (NVIDIA-ExcavatorNHMP-1x-2): 'C:\MPM\Bin\NVIDIA-ExcavatorNHMP\excavator.exe [{"id":1,"method":"subscribe","params":["nhmp.eu.nicehash.com:3200","34My6PQ6A5pe7DisxR441pQnJD3SrznSRo.Z87-MPM"]},{"id":1,"method":"algorithm.add","params":["lyra2rev2"]},{"id":1,"method":"workers.add","params":["alg-lyra2rev2","1","alg-lyra2rev2","1"]}]'
2018-10-07 09:58:41 ERROR: Error returned by miner (NVIDIA-ExcavatorNHMP-1x-2): Algorithm `lyra2rev2` already active.
2018-10-07 09:58:43 INFO: Starting miner (NVIDIA-ExcavatorNHMP-1x-2): 'C:\MPM\Bin\NVIDIA-ExcavatorNHMP\excavator.exe [{"id":1,"method":"subscribe","params":["nhmp.eu.nicehash.com:3200","34My6PQ6A5pe7DisxR441pQnJD3SrznSRo.Z87-MPM"]},{"id":1,"method":"algorithm.add","params":["lyra2rev2"]},{"id":1,"method":"workers.add","params":["alg-lyra2rev2","0","alg-lyra2rev2","0"]}]'
2018-10-07 09:58:47 ERROR: Error returned by miner (NVIDIA-ExcavatorNHMP-1x-2): Algorithm `lyra2rev2` already active.

**Comment by Dewbs** [comment]
Please remove the "--fee 0" from EWBF & " -nofee" from Bminer. The increase in fees is offset by increased performance.
Seems odd to remove devfees from a project which is donation based !

**Comment by Dewbs** [comment]
> > Seems odd to remove devfees from a project which is donation based !
> 
> Agree! Removed!

Thank you! NVIDIA-EWBF2Equihash.ps1 also

**Comment by Dewbs** [comment]
At C:\MPM\MinersLegacy\NVIDIA-Bminer.ps1:77 char:67
+                 elseif ($Coins.$($Pools.$Algorithm_Norm.CoinName) {
+                                                                   ~
Unexpected token '{' in expression or statement.
At C:\MPM\MinersLegacy\NVIDIA-Bminer.ps1:77 char:67
+                 elseif ($Coins.$($Pools.$Algorithm_Norm.CoinName) {
+                                                                   ~
Missing closing ')' after expression in 'elseif' statement.
+ CategoryInfo          : ParserError: (:) [], ParseException
+ FullyQualifiedErrorId : UnexpectedToken

**Comment by Dewbs** [comment]
After using 0c492f9 still get :

2018-10-07 17:06:01 INFO: Starting miner (NVIDIA-ExcavatorNHMP-1-GPU#02): 'C:\MPM\Bin\NVIDIA-ExcavatorNHMP\excavator.exe [{"id":1,"method":"subscribe","params":["nhmp.eu.nicehash.com:3200","34My6PQ6A5pe7DisxR441pQnJD3SrznSRo.Z87-MPM"]},{"id":1,"method":"algorithm.add","params":["lyra2rev2"]},{"id":1,"method":"workers.add","params":["alg-lyra2rev2","2"]}]'
2018-10-07 17:06:08 INFO: Starting miner (NVIDIA-ExcavatorNHMP-1-GPU#01): 'C:\MPM\Bin\NVIDIA-ExcavatorNHMP\excavator.exe [{"id":1,"method":"subscribe","params":["nhmp.eu.nicehash.com:3200","34My6PQ6A5pe7DisxR441pQnJD3SrznSRo.Z87-MPM"]},{"id":1,"method":"algorithm.add","params":["lyra2z"]},{"id":1,"method":"workers.add","params":["alg-lyra2z","1"]}]'
2018-10-07 17:06:14 INFO: Starting miner (NVIDIA-ExcavatorNHMP-1-GPU#00): 'C:\MPM\Bin\NVIDIA-ExcavatorNHMP\excavator.exe [{"id":1,"method":"subscribe","params":["nhmp.eu.nicehash.com:3200","34My6PQ6A5pe7DisxR441pQnJD3SrznSRo.Z87-MPM"]},{"id":1,"method":"algorithm.add","params":["lyra2rev2"]},{"id":1,"method":"workers.add","params":["alg-lyra2rev2","0"]}]'
2018-10-07 17:06:18 ERROR: Error returned by miner (NVIDIA-ExcavatorNHMP-1-GPU#00): Algorithm `lyra2rev2` already active.
2018-10-07 17:06:21 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1-GPU#00). 
2018-10-07 17:06:21 WARNING: Benchmarking in progress: 17 miners left to benchmark.
2018-10-07 17:06:21 INFO: Start waiting before next run. 
2018-10-07 17:06:33 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1-GPU#02). 
2018-10-07 17:06:35 VERBOSE: NVIDIA-ExcavatorNHMP-1-GPU#02: {"params":[],"method":"worker.list","id":1}
2018-10-07 17:06:35 VERBOSE: NVIDIA-ExcavatorNHMP-1-GPU#02: 
2018-10-07 17:06:37 ERROR: Failed to connect to miner (NVIDIA-ExcavatorNHMP-1-GPU#01). 
2018-10-07 17:06:39 VERBOSE: NVIDIA-ExcavatorNHMP-1-GPU#01: {"params":[],"method":"worker.list","id":1}
2018-10-07 17:06:39 VERBOSE: NVIDIA-ExcavatorNHMP-1-GPU#01:

**Comment by UselessGuru** [comment]
> At C:\MPM\MinersLegacy\NVIDIA-Bminer.ps1:77 char:67

Fixed

**Comment by UselessGuru** [comment]
> After using 0c492f9 still get :

??? What is your HW config? One card only?

**Comment by UselessGuru** [comment]
> other miners working 'normally' in multi-gpu 

What do you mean by this?
CreateMinerInstancePerDeviceModel = true or false?

@Dewbs 
Do you mind if I remove some of the comment above (to keep the thread clean)?

**Comment by Dewbs** [comment]
> > other miners working 'normally' in multi-gpu
> 
> What do you mean by this?

I mean I have per gpu miners for e.g. Zealot and so on working 'ok'

> CreateMinerInstancePerDeviceModel = true or false?

  "CreateMinerInstancePerDeviceModel": "$CreateMinerInstancePerDeviceModel", in config
-CreateMinerInstancePerDeviceModel set in start.bat

> 
> > What is your HW config?
> > Can you please post the output of http://localhost:3999/devices
> 
> @Dewbs
> Do you mind if I remove some of the comment above (to keep the thread clean)?

Sure

**Comment by Dewbs** [comment]
[localhost3999devices.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2454142/localhost3999devices.txt)

**Comment by Dewbs** [comment]
8269b10


Get-CommandPerDevice : Cannot process argument transformation on parameter 'Command'. Cannot convert value to type System.String.
At C:\MPM\MinersLegacy\NVIDIA-EWBF2Equihash.ps1:54 char:49
+             $Commands.$_ = Get-CommandPerDevice $Commands.$_ $Miner_D ...
+                                                 ~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Get-CommandPerDevice], ParameterBindingArgumentTransformationException
+ FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-CommandPerDevice

**Comment by UselessGuru** [comment]
Get-CommandPerDevice : Cannot process argument transformation on parameter 'Command'. Cannot convert value to type System.String. fixed in
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2189/commits/8f7ccd7b50f7d2700e7f3fca38c7eaa7838c20ca

**Comment by Dewbs** [comment]
@UselessGuru
Fix EWBF Get-CommandPerDevice
8f7ccd7

👍 Looking good! You are on fire today!

**Comment by paulpoco** [comment]
@UselessGuru I think there is an issue as to where the Miners get saved in the Bin folder?

Here is the code with the location of where to find the find the miner but the fold is being called the downloaded zip name minus the zip
image

Here a screen of my Bin folder:
image

**Comment by UselessGuru** [comment]
@paulpoco 

What version of PWSH is installed? There is a fundamental change with sub dir handling in PWSH 6.10.
Did you update Include.psm1 as well as Downloader.ps1?

**Comment by paulpoco** [comment]
I downloaded the whole version.

**Comment by UselessGuru** [comment]
But did you update to PWSH 6.10?

**Comment by paulpoco** [comment]
Yes I uninstalled the previous version and installed 6.1.   I did not reboot after that.  Will reboot and download a version and try again later.

**Comment by UselessGuru** [comment]
@paulpoco 

I think I found the problem. I've updated the master - can you try again?

**Comment by Dewbs** [comment]
EWBF is now 0.6 - details in #2002

**Comment by paulpoco** [comment]
Tried new version.  It keeps complaining about libcurl.dll.  Benchmarked only 2 GPU Miner, when it tried the rest the GPUs never did anything.

Gone back to my old version that works for now.

[Excavator-5100_2018-10-10_15-31-38.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2466909/Excavator-5100_2018-10-10_15-31-38.txt)
[MultiPoolMiner_2018-10-10_15-31-23.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2466911/MultiPoolMiner_2018-10-10_15-31-23.txt)
[MultiPoolMiner_2018-10-10_17-24-19.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2466912/MultiPoolMiner_2018-10-10_17-24-19.txt)
[MultiPoolMiner_2018-10-10_17-28-44.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2466913/MultiPoolMiner_2018-10-10_17-28-44.txt)
[MultiPoolMiner_2018-10-10.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2466914/MultiPoolMiner_2018-10-10.txt)

**Comment by UselessGuru** [comment]
@paulpoco

> when it tried the rest the GPUs never did anything

for a test just remove the AMD_NVIDIA-Claymore-Ethash miner file and it will benchmark all other miners

> complaining about libcurl.dll.

I  cannot find any log entries regarding libcurl.dll. MPM does NOT use libcurl.dll and your issue is not cause by MPM code. You clearly have an issue with AMD_NVIDIA-Claymore-Ethash. This one does indeed need libcurl.dll. Have you compared the contents of the AMD_NVIDIA-ClaymoreEthash folder (working and non-working installation)?

I bet you will get the same libcurl.dll error when you run the miner standalone:
`C:\Users\pjb\Desktop\Oct 10 330pm MPM\Bin\AMD_NVIDIA-Claymore-Ethash\EthDcrMiner64.exe -mport -5001 -epool us-east.ethash-hub.miningpoolhub.com:20585 -ewal paulpoco.multipoolminer -epsw x -allpools 1 -allcoins exp -esm 3 -dcoin keccak -dpool hub.miningpoolhub.com:17003 -dwal paulpoco.multipoolminer -dpsw x -dcri 30 -platform 2 -dbg 1 -logfile debug.log -di 01`

BTW: Not that is is causing this issue but as written in the readme it is not recommended to run MPM from a path containing spaces like you: C:\Users\pjb\Desktop\Oct 10 330pm MPM\

**Comment by paulpoco** [comment]
@UselessGuru I'll try no spaces in the folder name

**Comment by UselessGuru** [comment]
Because you have not updated to the latest Include.psm1:
https://github.com/MultiPoolMiner/MultiPoolMiner/blob/MultiPoolMiner_3.0.1/Include.psm1

**Comment by UselessGuru** [comment]
> Not sure what causes this:

I needed to change Include-WebRequest again:
Some miners, e.g. ClaymoreDual_v11.9, contain multiple miner binaries for different driver versions in various sub dirs
https://github.com/MultiPoolMiner/MultiPoolMiner/commit/8e3b81fba2618714de77e22435c0afa60cc64095
This is also the cause for your problem where MPM extracted the wrong directory

**Comment by paulpoco** [comment]
If I have the option to show Miner windows to true, will less stuff get written to the log.

**Comment by paulpoco** [comment]
Trying newest version, all seems fine so far, still benchmarking.  No missing DLL errors so far.

Is there a way to set the font size in the start.bat file?  When mining on MPH there are so many different coins that the display gets cut off.  The size is 16 but changed once running to 14 and it all fits.
image

**Comment by UselessGuru** [comment]
@paulpoco 

Thank you for your feedback! Glad we got it working!

> Is there a way to set the font size in the start.bat file

No, not that I know of...

>  that the display gets cut off.

Don't use -ShowPoolBalancesDetails maybe? You'll still see your balances.

**Comment by paulpoco** [comment]
@UselessGuru setup has been working for days now without issue.

I guess the Zergpool stuff can be removed now or repurposed for a different pool?

**Comment by Dewbs** [comment]
@paulpoco @UselessGuru 

Add https://nlpool.nl/ ?

**Comment by Dewbs** [comment]
[NLPool.zip](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2476388/NLPool.zip)
Please note temp fix on unit correction for Yescrypt - I think their reported factor is incorrect.

**Comment by UselessGuru** [comment]
@Dewbs


Could you please create a pull request for this - thank you very much!
Grant and me can then commit it.

Aaron is currently not approving anything - that's we need two independent approvers (Grant and me).

**Comment by paulpoco** [comment]
NLPool also pays out in LTC.  So far NLPool in MPM only works with BTC.  I had set NLPool as LTC in the config file.

**Comment by UselessGuru** [comment]
>  I had set NLPool as LTC in the config file but that never ran anything from NLPool.

Should be fixed now (untested) with  (https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2189/commits/3e3715c8e07182ef84a2340c63ddaddffb20b46c & https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2189/commits/596d42c85cc1c40d767b2bce45bc603b32012ab2)

**Comment by paulpoco** [comment]
@UselessGuru already on BTC for NLPool, so will try LTC briefly later tonight(10hrs from now).

Anyone have Hex & Lbk3 working on NLPool?  So far it is not trying to benchmark those.

**Comment by Dewbs** [comment]
@paulpoco
Hex has kicked in recently
Not sure I will continue with nlpool though as the return is pretty poor
Seems I’m mining dust all the time there. I’ve had on decent return when they hit a raven block but now for a few days I have little to show.

**Comment by paulpoco** [comment]
@Dewbs if the estimate is correct, NLPool will payout about 60% more than just MPH.

I notice the DYN coin  for CPU pays more.

**Comment by paulpoco** [comment]
@UselessGuru Monero is forking October 18?  Per MPH website https://monero.miningpoolhub.com
 
screenshot_20181017-124422_chrome

**Comment by UselessGuru** [comment]
> will there have to be a NLPoolCoins too? I haven't figured out how NLPool works fully yet.

I'll create coins pool files for all pools that support it, but this will be after 3.1.0

**Comment by paulpoco** [comment]
@UselessGuru LTC on NLPool appears to work in a quick test.

**Comment by UselessGuru** [comment]
Replaces with 3.1.0

**Pull request closed without merging**
