### PR TITLE
Update -allcoins 1 for Claymore dual mining

### PR DESCRIPTION
**Pull request by mkirov0**
Claymore 11.7 says -allcoins exp is obsolete and asks for -allcoins 1. I did not try it for Sia, but I am assuming it needs to be changed as well.

### CODE REVIEW

**Comment by UselessGuru** [comment]
@mkirov0 

Where did you read it is obsolete? I cannot find anything on it on https://bitcointalk.org/index.php?topic=1433925.0

**Comment by mkirov0** [comment]
Long story, but as I was testing Claymore outside MPM to make sure it works I saw it here:
screen shot 2018-05-02 at 9 30 56 am

**Comment by UselessGuru** [comment]
Just to avoid confusion I'd rather leave it as it is for now as it is working fine.
As soon as documentation also matches we can still changes.

**Comment by mkirov0** [comment]
Yeah, thats true.
I would have updated the Claymore miner file too, but need time to study @grantemsley's new auto-update feature first, so I don't break it. Its really cool tho!

**Comment by UselessGuru** [comment]
> new auto-update feature first, so I don't break it. Its really cool tho!

There is no auto-update for the regular MPM yet. The code [@grantemsley newpoc](https://github.com/grantemsley/MultiPoolMiner/tree/newpoc) is developed by me...

**Comment by mkirov0** [comment]
Great point! Recently I ended up disabling some miners with immediate dev fee, since I had my test PC on a 2 min interval. In this case if the def fee is 1 min and its the first thing mined after start it ends up being 50% of 2 min run...

**Pull request closed without merging**
