### PR TITLE
Update CcminerNevermore to 0.5 by Nemos

### PR DESCRIPTION
**Pull request by mkirov0**
The new version works great and its top performing miner for a few algos. Its possible I messed up the hash... Tried a tool online...

### CODE REVIEW

**Comment by Rama-Nujan** [comment]
Just a general comment - the addition of other algos that this miner may not support is confusing (hmq, jha, phi, etc) - will take very long to benchmark. When you leave those in - is it because you've tested them and you know they are faster than others? 

Also from what Grant and Guru said I think having unnecessary stats kept for algos that miners don't support bloats the program.

**Comment by mkirov0** [comment]
To answer your first question - yes. I am testing on a 1070 and for the ones I have left enabled this is the top performing miner. Also I have left enabled algos I have not tested yet (no pools or other reasons). I would have added all algos from the new Algorithms.txt, but I am not clear on the contents yet. 
As for leaving in algos and commenting them out, I am copying from my system directly. I can start removing them them when transferring, but I like working with data and assuming it would be useful to others.

**Comment by Rama-Nujan** [comment]
> I have left enabled this is the top performing miner.

This is quite interesting - I'll try it out myself and report back.

**Comment by Rama-Nujan** [comment]
mkirov is correct. Nevermore does a lot more. I'm benchmarking on Maxwell and Pascal right now.

**Comment by Rama-Nujan** [comment]
This can be pulled in like that - I'll submit another PR that incorporates the better miners being kept when I've benchmarked them all.

**Comment by mkirov0** [comment]
@UselessGuru do you want me to change it to the older version? I can create a new miner if you want to keep both 0.3 and 0.4.

**Comment by mkirov0** [comment]
@Rama-Nujan 
> This can be pulled in like that 

I appreciate your approval! 😃

**Comment by mkirov0** [comment]
>  I'm benchmarking all algo on all cards now with all miners

I already did that on a 1070. Hence my comments and PRs. It will take you at least a week.

**Comment by grantemsley** [comment]
@mkirov0 I am aware that it takes a long time to sort through the miners if all miners and algorithms are enabled, especially with us adding a lot of new miners lately.  I have one particularly weak CPU system that takes as long at 10 minutes to do the profit calculations on each loop.

That's something I'm currently working on fixing.  So don't worry about it getting slow because more algos are enabled in each miner, I'll handle that.

**Comment by grantemsley** [comment]
@Rama-Nujan My preference is to enable them all and let benchmarking sort it out automatically.  Mostly because it's less work.

**Comment by UselessGuru** [comment]
I am testing all the algos right now if all gues well I'll commit today.

I changed the code base slightly to make creating miners faster.

**Comment by grantemsley** [comment]
The hash is incorrect.  It should be 940EB4C246019216C8F95FFB2F2E65FA147B13A65756A38D660146672E47844B

**Pull request merged**
