### PR TITLE
Algo speed changes

### PR DESCRIPTION
**Pull request by Rama-Nujan**
Disabling algos on slow miners (Kept 2 fastest miners for Pascal and Maxwell)
Equihash: BMiner, DSTM and EWBF fastest
Keccak: Tpruvot, Alexis and KlausT fastest
Blake2s: Excavator1, Excavator2, Alexis fastest

### CODE REVIEW

**Comment by Rama-Nujan** [comment]
The purpose of this is to speed-up benchmarking for new users.

**Comment by grantemsley** [comment]
For CcminerNanashi.ps1, we recently disabled the keccakc algorithm because they aren't actually supported.  Your PR accidentally undoes that change.

Those might be the fastest on your system - but what hardware have you tested with?  Are they the fastest on all supported cards?

**Comment by Rama-Nujan** [comment]
I will undo the KeccakC change. 

I test these on a few rigs with all the same cards within them: 980, 980ti, 1070, 1080ti

**Comment by Rama-Nujan** [comment]
I am missing 1060, 1070ti and 1080. Although the scaling I presume would be linear within the same gpu architecture.

**Comment by Rama-Nujan** [comment]
Done

**Pull request closed without merging**
