### PR TITLE
CcminerTpruvot: remove pascal

### PR DESCRIPTION
**Pull request by UselessGuru**
pascal is no longer supported (error Unknown algo parameter 'pascal')

### CODE REVIEW

**Comment by UselessGuru** [comment]
> Please can you comment out the line instead of removing?

For what reason? I don't want to keep algos in the file which are not/no longer supported. It just adds to confusion.
To me commenting out makes sense if an algo works, but is not profitable. Stuff that does not work needs to go (to be consequent we should also remove ethash)

**Comment by aaronsace** [comment]
For consistency; you should note that all the files match. 

The binary can be swapper out and algorithms enabled/disabled easily.

**Comment by UselessGuru** [comment]
> The binary can be swapper out and algorithms enabled/disabled easily.

This issue can be dealt with perfectly with my suggestions in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1237.
This will even allow for automatic miner binary update. If we are going that route then I see absolutely no reason for uncomments.

**Comment by aaronsace** [comment]
Nothing more than a minor change or a bug fix will make it into the master branch for the time being.

**Pull request merged**
