### PR TITLE
Extend Interval for selected Miners and Algorithms

### PR DESCRIPTION
**Pull request by UselessGuru**
### Please test!
This will help stabilize the watchdog trigger-happy algorithms and miners, e.g. X16R or PalginNvidia, so they will not get disabled by watchdog.
It does this by extending the interval timer duration by a factor of 10x $Interval for the specified miners and algorithms. 
The extended loop-time also stabilizes the hash rates read from these hashrate bouncy algorithms.
It also disables hash rate fluctuation detection for the specified miners and algorithms. 
This is a workaround and not a perfect solution. The new 'multi-algo' will produce inconsistent hashrates by design.

This also helps for https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1549

**Existing 'Config.txt' must be edited manually in order to use the new feature.**

### CODE REVIEW

**Comment by grantemsley** [comment]
Have you looked into also disabling the fault tolerance for those miners like we talked about?

Even with the larger benchmarking period, I think (untested) it will still throw away some hashrates if they are too different from the previous ones.

**Comment by angelics** [comment]
x16r will fluctuate for around 20mh/s+- on my 12gpu rig. some suggested -N 600 + for better accuracy. untested too. extended benchmark is useful for alexis forks

**Comment by angelics** [comment]
extend interval for miner specific is only good for alexis forks. eg. alexis hsr, zenemy.....
alexis forks have 1 well known bug, that it takes more than 5mins to have all gpus start hashing, especially with rigs more than 6cards.
as for x16r, even with extended interval, watchdog will stil kick it out after higher and higher hashrate gets saved. -N 600 is nt the solution too, and user sgminer will stil get kicked.
i'll try with -N 600 and report back

**Comment by UselessGuru** [comment]
> watchdog will stil kick it out

Are you sure you have amended config.txt properly?

Line 738 should actually ignore hash rate fluctuation for configured miners:
`$Stat = Set-Stat -Name "$($Miner.Name)_$($_)_HashRate" -Value $Miner_Data.HashRate.$_ -Duration $StatSpan -FaultDetection ($Config.ExtendIntervalAlgorithm -inotcontains $_ -and $Config.ExtendIntervalMinerName -inotcontains $Miner.Name)`
where `($Config.ExtendIntervalAlgorithm -inotcontains $_ -and $Config.ExtendIntervalMinerName -inotcontains $Miner.Name)` should be $false

**Comment by angelics** [comment]
my bad. i did nt actually check the changes :) will give this PR a shot later. celebrating mothers day atm.

**Comment by UselessGuru** [comment]
@angelics: Still good?

**Comment by angelics** [comment]
i reset benchmark, testing benchmark now. give me few more hours. all good otherwise

**Comment by UselessGuru** [comment]
> 05 Minutes Once Bin\NVIDIA-Alexis78-11\ccminer.exe -a x17
05 Minutes Once Bin\NVIDIA-Alexis78-11\ccminer.exe -a c11
05 Minutes Once Bin\ZEnemy-NVIDIA-109a\z-enemy.exe -a x16r

Something is wrong with your config.txt.
You should see a message in the log like this:
`Benchmarking watchdog sensitive algorithm or miner. Increasing interval time temporarily to 10x interval...`

Please post http://localhost:3999/config

**Comment by angelics** [comment]
sry. my bad there. working nw :)
`2018-05-15 11:33:53 INFO: Benchmarking watchdog sensitive algorithm or miner. Increasing interval time temporarily to 3x interval (720 seconds). `

**Comment by UselessGuru** [comment]
@angelics 

I do appreciate your efforts. Thank you.
But please do not report findings here for code that you have modified to suit your needs. This will lead to inconsistent test results.

(the Original code enhances benchmark time by 10, and not 3 like yours. I cannot see what other modifications you implemented that might interfere with the original code)

**Pull request merged**
