### PR TITLE
ZergPool: Add new Equihash algos, europe only

### PR DESCRIPTION
**Pull request by UselessGuru**
Fix Zergpool divisor error

### CODE REVIEW

**Comment by paulpoco** [comment]
I am using this PR and the one for EWBF2 and I am only seeing Equihash1927-Zerocoin & Equihash1445-Bitcoinz.  The 2 other 144_5 ones don't try and Benchmark for Zergpool.

**Comment by UselessGuru** [comment]
@paulpoco 

> The 2 other 144_5 ones don't try

Why should it?
**There is only ONE Equihash 144_5 Algorithm** and that has already been benchmarked. MPM will mine whichever 144_5 coin is the most profitable.

**Comment by paulpoco** [comment]
Oh i get it now, and see a different 144_5 coin listed, and guess it could change later.

**Comment by paulpoco** [comment]
@UselessGuru on all of Zergpool examples of command line, the "mine.zergpool.com:port" now says that is the old stratum(still active) but they use "algo.mine.zergpool.com:port" now.

image

**Comment by UselessGuru** [comment]
@paulpoco 

Host is fixed

**Comment by paulpoco** [comment]
@UselessGuru  Line 133 is there supposed to be a space?
image

**Comment by UselessGuru** [comment]
@paulpoco 

> From Zergpool: They lowered other Alt payout coins ...

Thanks - I assume that you posted this as purely informational. I don't see any impact on MPM. ?

**Comment by paulpoco** [comment]
@UselessGuru yes just informational

**Comment by paulpoco** [comment]
@UselessGuru Zergpool has started offering Equihash965 but MPM is saying something about unable to determine divisor for Minex? 
screenshot_20180817-054555_teamviewer

**Comment by UselessGuru** [comment]
> Zergpool has started offering Equihash965 but MPM is saying something about unable to determine divisor for Minex?

ZergPools API is reporting incorrect data. Probably WIP (Wirk In Progress on theis side).
MPM is fully ready to support Equihash965. All that's needed is a working pool (with correct API data).

**Comment by UselessGuru** [comment]
ZergPool has fixed its API. Equihash965 is working well!

**Comment by paulpoco** [comment]
Appears to work now.

**Pull request closed without merging**
