### PR TITLE
Detect CPUs through CIM instead of OpenCL

### LINKED ISSUE #1866: CPUs no longer showing up
I have CPU turned on in my config file but I am no longer mining CPU only miners.

With all these fun fixes it is a challenge to know what files to download.  Especially since we have a master to download from AND several fixes that are in the test state.

So I am not sure what is going on with the system.  Excavator is now working much better.  But no more CPU mining.

### PR DESCRIPTION
**Pull request by grantemsley**
This generates the CPU devices using WMI/CIM instead of OpenCL.  WMI is going to have the most accurate information available about the processors, and doesn't rely on any drivers besides what's built into windows, so it makes sense to pull the information from there.

Tested on systems with and without CPU OpenCL drivers, and on multi processor systems where it properly generates 2-4 devices, one for each physical CPU.

I intend to try to expand on this in a future PR to include the supported instruction sets in the Info property, if I can find a way of doing it that isn't ugly, but this is enough on its own to get CPU mining working properly again.

Fixes #1866 
Relates to #1857 

Edit:  Added caching of the devices.  They shouldn't be changing while the script is running, but just in case we add some data that does change (like temperature or utilization) I added a -refresh switch to update the cached devices.  Needed because CIM is fairly slow, and Get-Device gets called for each and every miner to update the DeviceName list for backwards compatibility.

### CODE REVIEW

**Comment by Rimplestilhskin** [comment]
Re: https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1866

I downloaded latest version, right side is the green clone-download in zip file, copied bin, downloads, stats folders and mine works. Latest commit 331cfc8 

Is it maybe related to opencl drivers and intel SDK that needs to be uninstalled and reinstalled ?
I have read about latest win 10 updates that borks amd, nvidia and other drivers.

I again read the readme file here and a few other projects readme files, downloaded + installed the linked files minus intel opencl SDK (that you have to register :-( to download) and seems to work for me on cpu + NV.
Basically latest dotnet, latest NV drivers, latest opencl runtime, vc redistribute .... etc....

Latest commit 331cfc8 

   Device: {CPU#00}

Miner[Fee]                     Algorithm              Speed  USD/Day Accuracy       USD/GH/Day Pool[Fee]
----------                     ---------              -----  ------- --------       ---------- ---------
CpuminerJayddeeAessse42[0.00%] YescryptR16      859.75  H/s 524.2833     100% 609,808,982.6076 BlockMasters[0.00%]
CpuminerJayddeeAvx2[0.00%]     YescryptR16      820.00  H/s 500.0434     100% 609,808,982.6076 BlockMasters[0.00%]
CpuminerJayddeeSse2[0.00%]     YescryptR16       80.00  H/s  48.7847     100% 609,808,982.6076 BlockMasters[0.00%]
CpuminerJayddeeAvx2[0.00%]     Lyra2z           927.99 KH/s   0.5197     100%         560.0452 BlazePool[0.00%]
ClaymoreCpu[0.00%]             CryptoNightV7    307.00  H/s   0.4054     100%   1,320,602.5189 NiceHash[0.00%]
XmrigCpu[0.00%]                CryptoNightV7    296.00  H/s   0.3909     100%   1,320,602.5189 NiceHash[0.00%]
CpuminerJayddeeSse2[0.00%]     Lyra2z           538.52 KH/s   0.3016     100%         560.0452 BlazePool[0.00%]
FireiceCpu[0.00%]              CryptoNightV7    227.00  H/s   0.2998     100%   1,320,602.5189 NiceHash[0.00%]
CpuminerJayddeeAessse42[0.00%] Yescrypt           4.75 KH/s   0.4047      85%      85,149.6690 ZergPool-GlobalBoost[0.00%]
CpuminerJayddeeAvx2[0.00%]     Yescrypt           4.73 KH/s   0.4028      85%      85,149.6690 ZergPool-GlobalBoost[0.00%]
CpuminerTpruvotCore2[0.00%]    Yescrypt           4.53 KH/s   0.3857      85%      85,149.6690 ZergPool-GlobalBoost[0.00%]
CpuminerJayddeeSse2[0.00%]     m7m              195.73 KH/s   0.2761      97%       1,410.3764 ZergPool-Magi[0.00%]
CpuminerJayddeeAvx2[0.00%]     m7m              189.77 KH/s   0.2676      97%       1,410.3764 ZergPool-Magi[0.00%]
CpuminerJayddeeAessse42[0.00%] m7m              188.09 KH/s   0.2653      97%       1,410.3764 ZergPool-Magi[0.00%]
CpuminerJayddeeAvx2[0.00%]     Allium             1.27 MH/s   0.3160      83%         248.4557 ZergPool-Garlic[0.00%]
CpuminerJayddeeSse2[0.00%]     CryptoNightV7    160.00  H/s   0.2113     100%   1,320,602.5189 NiceHash[0.00%]
CpuminerJayddeeAessse42[0.00%] CryptoNightV7    130.00  H/s   0.1717     100%   1,320,602.5189 NiceHash[0.00%]
FireiceCpu[0.00%]              CryptoNightHeavy 131.00  H/s   0.1622     100%   1,238,283.2937 NiceHash[0.00%]
CpuminerJayddeeAessse42[0.00%] Lyra2z           287.03 KH/s   0.1607     100%         560.0452 BlazePool[0.00%]
XmrigCpu[0.00%]                CryptoNightHeavy 129.00  H/s   0.1597     100%   1,238,283.2937 NiceHash[0.00%]
CpuminerJayddeeAessse42[0.00%] Allium           792.32 KH/s   0.1969      83%         248.4557 ZergPool-Garlic[0.00%]
CpuminerJayddeeSse2[0.00%]     Allium           710.40 KH/s   0.1765      83%         248.4557 ZergPool-Garlic[0.00%]
CpuminerJayddeeAvx2[0.00%]     HMQ1725          209.78 KH/s   0.0722     100%         344.3543 BlazePool[0.00%]


   Device: {GPU#00}

Miner[Fee]                                    Algorithm                                Speed USD/Day     Accuracy        USD/GH/Day Pool[Fee]
----------                                    ---------                                ----- -------     --------        ---------- ---------
CcminerNevermore[0.00%]                       Tribus                              71.47 MH/s  3.7348         100%           52.2553 ZergPool[0.00%]
CcminerTpruvot[0.00%]                         Tribus                              70.27 MH/s  3.6721         100%           52.2553 ZergPool[0.00%]
CcminerSuprMiner[0.00%]                       Tribus                              64.70 MH/s  3.3809         100%           52.2553 ZergPool[0.00%]
CcminerSkunk[0.00%]                           Tribus                              53.88 MH/s  2.8156         100%           52.2553 ZergPool[0.00%]
CcminerAlexis[0.00%]                          C11                                 19.85 MH/s  1.9332         100%           97.3879 ZergPool[0.00%]
CcminerNevermore[0.00%]                       HMQ1725                              5.28 MH/s  1.8171         100%          344.3543 BlazePool[0.00%]
CcminerNanashi[0.00%]                         HMQ1725                              5.00 MH/s  1.7225         100%          344.3543 BlazePool[0.00%]
CcminerXevan[0.00%]                           Xevan                                3.45 MH/s  1.6246         100%          471.3989 ZergPool[0.00%]
CcminerNevermore[0.00%]                       C11                                 16.42 MH/s  1.5989         100%           97.3879 ZergPool[0.00%]

**Comment by grantemsley** [comment]
@Rimplestilhskin "Is it maybe related to opencl drivers and intel SDK that needs to be uninstalled and reinstalled"

Yes, that's exactly the problem.  This fixes it so that no matter what OpenCL CPU drivers you have (including none at all) your CPUs get detected properly.  The CPU miners don't need OpenCL at all, so there's no reason why we should require it either.

**Comment by Kettoch** [comment]
This works for me.

**Comment by Kettoch** [comment]
Likely needs to take https://github.com/MultiPoolMiner/MultiPoolMiner/commit/525aeb175a3af8a9a226b777731a039b1cbee979 into account now.

**Comment by grantemsley** [comment]
@Kottoch nope.  I wrote that PR (https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1867) - this works perfectly with it.

**Comment by Kettoch** [comment]
Yes, works great!

**Comment by grantemsley** [comment]
@aaronsace Have you had a chance to look over this yet?

**Comment by aaronsace** [comment]
@grantemsley Can you make it return no platform for CPUs as this is an OpenCL specific feature?

**Comment by grantemsley** [comment]
@aaronsace Removed the platformid portions.  Also renamed Info to CIM to reflect where the data is coming from, as is done with OpenCL.

**Pull request merged**
