### PR TITLE
Algorithms.txt: Add CryptoNight and Equihash algorithm variants

### PR DESCRIPTION
**Pull request by UselessGuru**
# Important!!! #

The updated Algorithms.txt in this PR is a definitive requirement for all new CryptoNight and Equihash miners, e.g. 
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2024
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2023
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2022
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2007
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2002

## CryptoNight

I put together a list of all available CryptoNight algo variants and put them together in one file. XmRig & FireIce, SRB-miner, as well as other CryptoNight miners use different algo names for the same algos which make a common algorithm.txt a hell of a task :-(

Important: A complete algorithm.txt with all cryptonight variants is a prerequisite to get new miners working properly.

I tried NOT to include coin names, since the pools should always return an algo name and an optional coin name as separate property.

I am looking for assistance to verify:

the completeness of all available variants in algorithm.txt
the correctness of the mapping of all variants, we must make sure that we end up with as few normalized algorithms (Get-Algorithm) as possible

These pages have very helpful overviews of most algo variants:
https://github.com/xmrig/xmrig/blob/master/src/common/crypto/Algorithm.cpp
https://github.com/xmrig/xmrig-proxy/blob/master/doc/STRATUM_EXT.md#14-algorithm-names-and-variants
https://github.com/fireice-uk/xmr-stak

### Normalized algorithm naming scheme (as returned from Get-Algorithm):
[BaseAlgorithm][Variant]

**Base algorithms**
- CryptoNight
- CryptoNightLite
- CryptoNightHeavy

**Variants** (and their synonyms, the first value will be used for the naming scheme)
For CryptoNight:
- (none) / 0 / bbscoin / graft / monero (ASIC only!)
- Msr / fast / masari
- Rto / arto
- V7 / 1 / monerov7
- Xao / alloy
- Xtl / stellite

For CryptoNightLite:
- (none) / 0 / light
- V7 / 1 / aeonv7
- Ipbc / xor / aeon

For CryptoNightHeavy:
- (none), ryo
- Tube / bittube / bittube2
- Xhv / haven

The original PR for this was https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1979

Notes: CryptoNightItalo: PoW is identical to CryptoNight-Haven  (https://cryptoknight.cc/italo/)

## Equihash

Equihash has now new variants, like Equihash144_9.

Since the number after the underscore is a vital part of the algorithm we are including it as part of the normalized algorithm name.

**Synthetic algorithms**
Some pools, e.g. ZergPool have added synthetic algorithm names to their API to indicate the coin that is being mined. (Equihash144BtcZ is Equihash, and the coin being mined is BtcZ)

For all such variations the executed algorithm is the same, e.g Equihash144_9 regardless of the coin.

Since these synthetic algorithms are pool specific, the pool file must convert the algorithm to a normalized form as used by MPM.
-> The synthetic algorithms do not need to be included in Algorithms.txt

### CODE REVIEW

**Comment by paulpoco** [comment]
Supported coin options:
        - aeon7
        - bbscoin
        - bittube
        - cryptonight
        - cryptonight_bittube2
        - cryptonight_masari
        - cryptonight_haven
        - cryptonight_heavy
        - cryptonight_lite
        - cryptonight_lite_v7
        - cryptonight_lite_v7_xor
        - cryptonight_v7
        - cryptonight_v7_stellite
        - graft
        - haven
        - intense
        - masari
        - monero7
        - ryo
        - stellite
        - turtlecoin

Version: xmr-stak 2.4.7 c5f0505d

**Comment by UselessGuru** [comment]
> - cryptonight_bittube2 This is new. A matching one in algorithms.txt?

See https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2019

**Comment by paulpoco** [comment]
cryptonight_bittube2 is how "xmr-stak.exe --help" spits it out.

I see cryptonightbittubev2 in the algorithm.txt but how would that match up with the way xmr-stak calls them?

**Comment by UselessGuru** [comment]
@paulpoco 

> cryptonight_bittube2 is how "xmr-stak.exe --help" spits it out.

It is now in the consolidated https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2048

**Comment by UselessGuru** [comment]
Fixed with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2094

**Pull request closed without merging**
