### PR TITLE
CcminerZfast 233

### PR DESCRIPTION
**Pull request by angelics**
CcminerZfast 233 available for testing.
very limited gpu available to use and only for miningpoolhub

edit: https://bitcointalk.org/index.php?topic=3259259.0
edit2: ccminerzfast optimization will only apply after 15~20 minute after program start to avoid disabling miner Fee (1.8%)

### CODE REVIEW

**Comment by grantemsley** [comment]
Is there a github or bitcointalk link where we can find out more about this miner?

**Comment by Rama-Nujan** [comment]
https://bitcointalk.org/index.php?topic=3259259.0

This is a very fast miner. I've used it myself but have not figured out how to code it in to use only MPH.

**Comment by angelics** [comment]
@Rama-Nujan simply remove any $Devices and $DevicesIDS (if u run on master copy of MPM) related in this file. it shud be fine. 
included pool check `if ($Pools.$Algorithm_Norm.host -match ".*miningpoolhub\.com")`
nt sure if there is other cleaner way. but it works
will make changes after recent get-device problem fixed.

**Comment by grantemsley** [comment]
I will be unable to test this, since I don't have any single rigs with 3 NVIDIA cards in them to test it on.

**Comment by angelics** [comment]
update and closing. just in case somebody out there want to use.
will revisit this unless someone taking over.

**Pull request closed without merging**
