### PR TITLE
Update XmRig CPU to version 2.6.4

### PR DESCRIPTION
**Pull request by UselessGuru**
Changes:
- cryptonight-lite/ipbc replaced to cryptonight-heavy/tube for Bittube (TUBE).
- Added cryptonight/rto (cryptonight variant 1 with IPBC/TUBE mod) variant for Arto (RTO) coin.
- Added cryptonight/xao (original cryptonight with bigger iteration count) variant for Alloy (XAO) coin.
Better variant detection for nicehash.com and minergate.com.
-Added support for specify both algorithm and variant via single algo option.

Fixes https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1965

Edit:
Requires https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2018

### CODE REVIEW

**Comment by Kettoch** [comment]
After creating the new file and removing the old, nothing happens.  The Algo Does not show up, let alone benchmark.  I have removed the old xmrig cpu benchmark file and it does not do anything.

Other new algos are benching but this does not show up.

does this update have a dependency on https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1979/fileshttps://github.com/MultiPoolMiner/MultiPoolMiner/pull/1979 ?

**Comment by grantemsley** [comment]
Yes this definitely requires #1979

**Comment by Kettoch** [comment]
Well, currently it does not even try to launch.  I will try isolating it.

**Comment by paulpoco** [comment]
Working fine.  It only Benchmarked CryptoNightHeavy.  It didn't even try CryptoNightV7.

AMD Ryzen 7 1700

**Comment by UselessGuru** [comment]
It benchmarks what ever algorithms are available. For a list of available algorithms see http://localhost:3999/algorithms

**Comment by paulpoco** [comment]
CryptoNightV7 is in that list from http://localhost:3999/algorithms

**Comment by UselessGuru** [comment]
Please post http://localhost:3999/miners

**Comment by Kettoch** [comment]
To be honest, at this stage of the development of v3, testing all the new pull requests gets to be an interesting challenge.
I need to start tracking the active PR's I am using so that asking for help would be easier.

**Comment by paulpoco** [comment]
![image](https://user-images.githubusercontent.com/801414/42850920-d076bfb0-89de-11e8-9a0e-b42b1efedf16.png
@Kettoch I started making file names with the PRs I have included.

**Comment by paulpoco** [comment]
@UselessGuru 
Please post http://localhost:3999/miners
[localhost3999miners.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2203716/localhost3999miners.txt)



Or do you have an old stat file with 0 hash rate?
BTW: 0 hashrate stat files are usually 400 bytes in size (easy to find :-))
* No 0 hashrate.  Only have one hash file for XmrigCpu
image

**Comment by Kettoch** [comment]
Raw copy of master in test directory.
all miners removed but this one
Algorithms.txt modified per the listed reference requirement.


Still no miners and this is what I get in algorithms
[
  "Blake2s",
  "CryptoNightV7",
  "DecredNiceHash",
  "Equihash",
  "Ethash",
  "Ethash2gb",
  "Groestl",
  "Keccak",
  "Lbry",
  "Lyra2RE2",
  "Lyra2z",
  "NeoScrypt",
  "Pascal",
  "Sib",
  "Skunk"
]

**Comment by Kettoch** [comment]
Pools:
[
  {
    "lyra2z": {
      "Algorithm": "Lyra2z",
      "CoinName": "",
      "Price": 5.573E-11,
      "StablePrice": 5.53820086778021E-11,
      "MarginOfError": 0.0046442590154161731,
      "Protocol": "stratum+tcp",
      "Host": "lyra2z.mine.zpool.ca",
      "Port": 4553,
      "User": "BTC",
      "Pass": "Alien,c=BTC",
      "Region": "US",
      "SSL": false,
      "Updated": "2018-07-18T21:29:18.0906951Z",
      "Name": "Zpool",
      "Price_Bias": 5.4610383498520883E-11,
      "Price_Unbias": 5.53820086778021E-11
    },
    "equihash": {
      "Algorithm": "Equihash",
      "CoinName": "",
      "Price": 2.7455688985E-07,
      "StablePrice": 2.8091699843996688E-07,
      "MarginOfError": 0.12819146109666085,
      "Protocol": "stratum+ssl",
      "Host": "equihash.usa.nicehash.com",
      "Port": 33357,
      "User": "BTC.Alien",
      "Pass": "x",
      "Region": "US",
      "SSL": true,
      "Updated": "2018-07-18T21:31:10.0503881Z",
      "Name": "NiceHash",
      "Price_Bias": 1.7288351700924361E-07,
      "Price_Unbias": 2.8091699843996688E-07
    },
    "ethash": {
      "Algorithm": "Ethash",
      "CoinName": "",
      "Price": 5.16504E-12,
      "StablePrice": 4.7731396098394965E-12,
      "MarginOfError": 0.012146492462184163,
      "Protocol": "stratum+tcp",
      "Host": "daggerhashimoto.usa.nicehash.com",
      "Port": 3353,
      "User": "BTC.Alien",
      "Pass": "x",
      "Region": "US",
      "SSL": false,
      "Updated": "2018-07-18T21:31:10.021408Z",
      "Name": "NiceHash",
      "Price_Bias": 4.599208896963892E-12,
      "Price_Unbias": 4.7731396098394965E-12
    },
    "lyra2re2": {
      "Algorithm": "Lyra2RE2",
      "CoinName": "",
      "Price": 3.16E-12,
      "StablePrice": 2.80086770086684E-12,
      "MarginOfError": 0.0057212859769923477,
      "Protocol": "stratum+tcp",
      "Host": "lyra2v2.mine.zpool.ca",
      "Port": 4533,
      "User": "BTC",
      "Pass": "Alien,c=BTC",
      "Region": "US",
      "SSL": false,
      "Updated": "2018-07-18T21:29:18.0733707Z",
      "Name": "Zpool",
      "Price_Bias": 2.7527940055656992E-12,
      "Price_Unbias": 2.80086770086684E-12
    },
    "neoscrypt": {
      "Algorithm": "NeoScrypt",
      "CoinName": "",
      "Price": 1.0967E-10,
      "StablePrice": 1.0941974864221572E-10,
      "MarginOfError": 0.0070719658259724948,
      "Protocol": "stratum+tcp",
      "Host": "neoscrypt.mine.zpool.ca",
      "Port": 4233,
      "User": "BTC",
      "Pass": "Alien,c=BTC",
      "Region": "US",
      "SSL": false,
      "Updated": "2018-07-18T21:29:18.1477092Z",
      "Name": "Zpool",
      "Price_Bias": 1.0709831047296297E-10,
      "Price_Unbias": 1.0941974864221572E-10
    },
    "groestl": {
      "Algorithm": "Groestl",
      "CoinName": "Groestlcoin",
      "Price": 1.7540000000000001E-13,
      "StablePrice": 1.6024913038063903E-13,
      "MarginOfError": 0.10439490334487882,
      "Protocol": "stratum+tcp",
      "Host": "hub.miningpoolhub.com",
      "Port": 17004,
      "User": "Kettoch.Alien",
      "Pass": "x",
      "Region": "US",
      "SSL": false,
      "Updated": "2018-07-18T21:07:54.7147688Z",
      "Name": "MiningPoolHub",
      "Price_Bias": 1.1006155294907595E-13,
      "Price_Unbias": 1.6024913038063903E-13
    },
    "keccak": {
      "Algorithm": "Keccak",
      "CoinName": "",
      "Price": 1.0644E-13,
      "StablePrice": 1.0636672413735735E-13,
      "MarginOfError": 0.00276305565207919,
      "Protocol": "stratum+tcp",
      "Host": "keccak.usa.nicehash.com",
      "Port": 3338,
      "User": "BTC.Alien",
      "Pass": "x",
      "Region": "US",
      "SSL": false,
      "Updated": "2018-07-18T21:31:09.9458337Z",
      "Name": "NiceHash",
      "Price_Bias": 1.0548503260239472E-13,
      "Price_Unbias": 1.0636672413735735E-13
    },
    "ethash2gb": {
      "Algorithm": "Ethash2gb",
      "CoinName": "Musicoin",
      "Price": 3.93046E-12,
      "StablePrice": 3.9747304953564074E-12,
      "MarginOfError": 0.00829031392661587,
      "Protocol": "stratum+tcp",
      "Host": "us-east.ethash-hub.miningpoolhub.com",
      "Port": 20585,
      "User": "Kettoch.Alien",
      "Pass": "x",
      "Region": "US",
      "SSL": false,
      "Updated": "2018-07-18T21:07:55.0054202Z",
      "Name": "MiningPoolHubCoins",
      "Price_Bias": 3.8758752046158131E-12,
      "Price_Unbias": 3.9747304953564074E-12
    },
    "decrednicehash": {
      "Algorithm": "DecredNiceHash",
      "CoinName": "",
      "Price": 7.8000000000000005E-16,
      "StablePrice": 8.115695828756576E-16,
      "MarginOfError": 0.013923415716592861,
      "Protocol": "stratum+tcp",
      "Host": "decred.usa.nicehash.com",
      "Port": 3354,
      "User": "BTC.Alien",
      "Pass": "x",
      "Region": "US",
      "SSL": false,
      "Updated": "2018-07-18T21:27:34.4289461Z",
      "Name": "NiceHash",
      "Price_Bias": 7.7767012081969861E-16,
      "Price_Unbias": 8.115695828756576E-16
    },
    "lbry": {
      "Algorithm": "Lbry",
      "CoinName": "",
      "Price": 1.2320000000000001E-14,
      "StablePrice": 9.6952722282973E-15,
      "MarginOfError": 0.074023833321520932,
      "Protocol": "stratum+tcp",
      "Host": "lbry.usa.nicehash.com",
      "Port": 3356,
      "User": "BTC.Alien",
      "Pass": "x",
      "Region": "US",
      "SSL": false,
      "Updated": "2018-07-18T21:31:10.0441495Z",
      "Name": "NiceHash",
      "Price_Bias": 7.54222858199455E-15,
      "Price_Unbias": 9.6952722282973E-15
    },
    "pascal": {
      "Algorithm": "Pascal",
      "CoinName": "",
      "Price": 8.85E-15,
      "StablePrice": 8.8486277591024317E-15,
      "MarginOfError": 0.021018821648131618,
      "Protocol": "stratum+tcp",
      "Host": "pascal.usa.nicehash.com",
      "Port": 3358,
      "User": "BTC.Alien",
      "Pass": "x",
      "Region": "US",
      "SSL": false,
      "Updated": "2018-07-18T21:31:10.0581166Z",
      "Name": "NiceHash",
      "Price_Bias": 8.29066457300459E-15,
      "Price_Unbias": 8.8486277591024317E-15
    },
    "sib": {
      "Algorithm": "Sib",
      "CoinName": "",
      "Price": 6.0999999999999993E-13,
      "StablePrice": 6.1245100221722608E-13,
      "MarginOfError": 0.0045951021516726547,
      "Protocol": "stratum+tcp",
      "Host": "x11gost.usa.nicehash.com",
      "Port": 3359,
      "User": "BTC.Alien",
      "Pass": "x",
      "Region": "US",
      "SSL": false,
      "Updated": "2018-07-18T21:23:46.2288407Z",
      "Name": "NiceHash",
      "Price_Bias": 6.0400817746297877E-13,
      "Price_Unbias": 6.1245100221722608E-13
    },
    "blake2s": {
      "Algorithm": "Blake2s",
      "CoinName": "",
      "Price": 6.3E-15,
      "StablePrice": 8.74255999811454E-15,
      "MarginOfError": 0.013135302166844684,
      "Protocol": "stratum+tcp",
      "Host": "blake2s.mine.zpool.ca",
      "Port": 5766,
      "User": "BTC",
      "Pass": "Alien,c=BTC",
      "Region": "US",
      "SSL": false,
      "Updated": "2018-07-18T21:29:17.9143666Z",
      "Name": "Zpool",
      "Price_Bias": 8.398051496253529E-15,
      "Price_Unbias": 8.74255999811454E-15
    },
    "skunk": {
      "Algorithm": "Skunk",
      "CoinName": "",
      "Price": 1.9900000000000002E-12,
      "StablePrice": 2.1329942873369487E-12,
      "MarginOfError": 0.015024544070968881,
      "Protocol": "stratum+tcp",
      "Host": "skunk.mine.zpool.ca",
      "Port": 8433,
      "User": "BTC",
      "Pass": "Alien,c=BTC",
      "Region": "US",
      "SSL": false,
      "Updated": "2018-07-18T21:29:18.3605373Z",
      "Name": "Zpool",
      "Price_Bias": 2.0368524873172924E-12,
      "Price_Unbias": 2.1329942873369487E-12
    },
    "cryptonightv7": {
      "Algorithm": "CryptoNightV7",
      "CoinName": "",
      "Price": 1.1925193844E-07,
      "StablePrice": 1.2409578227565605E-07,
      "MarginOfError": 0.042546459037679625,
      "Protocol": "stratum+ssl",
      "Host": "cryptonightv7.usa.nicehash.com",
      "Port": 33363,
      "User": "BTC.Alien",
      "Pass": "x",
      "Region": "US",
      "SSL": true,
      "Updated": "2018-07-18T21:31:10.0924445Z",
      "Name": "NiceHash",
      "Price_Bias": 1.0825627392363602E-07,
      "Price_Unbias": 1.2409578227565605E-07
    }
  }
]

Devices:
[
  {
    "Index": 0,
    "PlatformId": 0,
    "PlatformId_Index": 0,
    "Type_PlatformId_Index": 0,
    "Vendor": "NVIDIA Corporation",
    "Vendor_Index": 0,
    "Type_Vendor_Index": 0,
    "Type": "Gpu",
    "Type_Index": 0,
    "OpenCL": {
      "AddressBits": 64,
      "Available": true,
      "CompilerAvailable": true,
      "DoubleFpConfig": "FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma",
      "EndianLittle": true,
      "ErrorCorrectionSupport": false,
      "ExecCapabilities": "ExecKernel",
      "Extensions": "cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer",
      "GlobalMemCacheSize": 458752,
      "GlobalMemCacheType": 2,
      "GlobalMemCachelineSize": 128,
      "GlobalMemSize": 11811160064,
      "ImageSupport": true,
      "LocalMemSize": 49152,
      "LocalMemType": 1,
      "MaxClockFrequency": 1582,
      "MaxComputeUnits": 28,
      "MaxConstantArgs": 9,
      "MaxConstantBufferSize": null,
      "MaxMemAllocSize": 2952790016,
      "MaxParameterSize": 4352,
      "MaxReadImageArgs": 256,
      "MaxSamplers": 32,
      "MaxWorkGroupSize": 1024,
      "MaxWorkItemDimensions": 3,
      "MaxWorkItemSizes": "1024 1024 64",
      "MaxWriteImageArgs": 16,
      "MemBaseAddrAlign": 4096,
      "MinDataTypeAlignSize": 128,
      "Name": "GeForce GTX 1080 Ti",
      "ClVersion": "OpenCL C 1.2 ",
      "Platform": "@{Profile=FULL_PROFILE; Version=OpenCL 1.2 CUDA 9.2.127; Name=NVIDIA CUDA; Vendor=NVIDIA Corporation; Extensions=System.Object[]}",
      "PreferredVectorWidthChar": 1,
      "PreferredVectorWidthShort": 1,
      "PreferredVectorWidthInt": 1,
      "PreferredVectorWidthLong": 1,
      "PreferredVectorWidthFloat": 1,
      "PreferredVectorWidthDouble": 1,
      "Profile": "FULL_PROFILE",
      "QueueProperties": "OutOfOrderExecModeEnable, ProfilingEnable",
      "SingleFpConfig": "FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt",
      "Type": "Gpu",
      "Vendor": "NVIDIA Corporation",
      "VendorId": 4318,
      "Version": "OpenCL 1.2 CUDA",
      "DriverVersion": "398.11"
    },
    "Model": "GeForce GTX 1080 Ti",
    "Name": "GPU#00"
  },
  {
    "Index": 1,
    "PlatformId": 0,
    "PlatformId_Index": 1,
    "Type_PlatformId_Index": 1,
    "Vendor": "NVIDIA Corporation",
    "Vendor_Index": 1,
    "Type_Vendor_Index": 1,
    "Type": "Gpu",
    "Type_Index": 1,
    "OpenCL": {
      "AddressBits": 64,
      "Available": true,
      "CompilerAvailable": true,
      "DoubleFpConfig": "FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma",
      "EndianLittle": true,
      "ErrorCorrectionSupport": false,
      "ExecCapabilities": "ExecKernel",
      "Extensions": "cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer",
      "GlobalMemCacheSize": 458752,
      "GlobalMemCacheType": 2,
      "GlobalMemCachelineSize": 128,
      "GlobalMemSize": 11811160064,
      "ImageSupport": true,
      "LocalMemSize": 49152,
      "LocalMemType": 1,
      "MaxClockFrequency": 1582,
      "MaxComputeUnits": 28,
      "MaxConstantArgs": 9,
      "MaxConstantBufferSize": null,
      "MaxMemAllocSize": 2952790016,
      "MaxParameterSize": 4352,
      "MaxReadImageArgs": 256,
      "MaxSamplers": 32,
      "MaxWorkGroupSize": 1024,
      "MaxWorkItemDimensions": 3,
      "MaxWorkItemSizes": "1024 1024 64",
      "MaxWriteImageArgs": 16,
      "MemBaseAddrAlign": 4096,
      "MinDataTypeAlignSize": 128,
      "Name": "GeForce GTX 1080 Ti",
      "ClVersion": "OpenCL C 1.2 ",
      "Platform": "@{Profile=FULL_PROFILE; Version=OpenCL 1.2 CUDA 9.2.127; Name=NVIDIA CUDA; Vendor=NVIDIA Corporation; Extensions=System.Object[]}",
      "PreferredVectorWidthChar": 1,
      "PreferredVectorWidthShort": 1,
      "PreferredVectorWidthInt": 1,
      "PreferredVectorWidthLong": 1,
      "PreferredVectorWidthFloat": 1,
      "PreferredVectorWidthDouble": 1,
      "Profile": "FULL_PROFILE",
      "QueueProperties": "OutOfOrderExecModeEnable, ProfilingEnable",
      "SingleFpConfig": "FpDenorm, FpInfNan, FpRoundToNearest, FpRoundToZero, FpRoundToInf, FpFma, FpCorrectlyRoundedDivideSqrt",
      "Type": "Gpu",
      "Vendor": "NVIDIA Corporation",
      "VendorId": 4318,
      "Version": "OpenCL 1.2 CUDA",
      "DriverVersion": "398.11"
    },
    "Model": "GeForce GTX 1080 Ti",
    "Name": "GPU#01"
  },
  {
    "Index": 2,
    "Vendor": "GenuineIntel",
    "Type_Vendor_Index": 0,
    "Type": "Cpu",
    "Type_Index": 0,
    "CIM": {
      "CimClass": "@{CimSuperClassName=CIM_Processor; CimSuperClass=; CimClassProperties=System.Object[]; CimClassQualifiers=System.Object[]; CimClassMethods=System.Object[]; CimSystemProperties=}",
      "CimInstanceProperties": "                                                        ",
      "CimSystemProperties": "@{Namespace=root/cimv2; ServerName=ALIEN; ClassName=Win32_Processor; Path=}",
      "Caption": "Intel64 Family 6 Model 85 Stepping 4",
      "Description": "Intel64 Family 6 Model 85 Stepping 4",
      "InstallDate": null,
      "Name": "Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz",
      "Status": "OK",
      "Availability": 3,
      "ConfigManagerErrorCode": null,
      "ConfigManagerUserConfig": null,
      "CreationClassName": "Win32_Processor",
      "DeviceID": "CPU0",
      "ErrorCleared": null,
      "ErrorDescription": null,
      "LastErrorCode": null,
      "PNPDeviceID": null,
      "PowerManagementCapabilities": null,
      "PowerManagementSupported": false,
      "StatusInfo": 3,
      "SystemCreationClassName": "Win32_ComputerSystem",
      "SystemName": "ALIEN",
      "AddressWidth": 64,
      "CurrentClockSpeed": 2904,
      "DataWidth": 64,
      "Family": 179,
      "LoadPercentage": 3,
      "MaxClockSpeed": 2904,
      "OtherFamilyDescription": null,
      "Role": "CPU",
      "Stepping": null,
      "UniqueId": null,
      "UpgradeMethod": 1,
      "Architecture": 9,
      "AssetTag": "",
      "Characteristics": 252,
      "CpuStatus": 1,
      "CurrentVoltage": 0,
      "ExtClock": 100,
      "L2CacheSize": 12288,
      "L2CacheSpeed": null,
      "L3CacheSize": 16896,
      "L3CacheSpeed": 0,
      "Level": 6,
      "Manufacturer": "GenuineIntel",
      "NumberOfCores": 12,
      "NumberOfEnabledCore": 12,
      "NumberOfLogicalProcessors": 24,
      "PartNumber": "",
      "ProcessorId": "BFEBFBFF00050654",
      "ProcessorType": 3,
      "Revision": 21764,
      "SecondLevelAddressTranslationExtensions": false,
      "SerialNumber": "",
      "SocketDesignation": "SOCKET 0",
      "ThreadCount": 24,
      "Version": "",
      "VirtualizationFirmwareEnabled": false,
      "VMMonitorModeExtensions": false,
      "VoltageCaps": null,
      "PSComputerName": null
    },
    "Model": "Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz",
    "Name": "CPU#00"
  }
]

Here you go @UselessGuru

**Comment by Kettoch** [comment]
Ok, something that was not clear.
It seems there are two things that were not clear.  The miner file may have those lists of commands. But it will not run any of them unless you have the Algorithm from the pool in your algorithms configuration.

I added heavy and now I get that to work.  But, the V7 will not because of the temp fix looking for stratum+tcp because v7 protocol is stratum+ssl and gets filtered out.

Without looking at the individual pool files by running their web request, I would not have found this.

Might be good to explain the link between the algorithm section in the config, the algorithms.txt, the commands in the miner and what the pools return.  That relationship is KEY in getting things to launch and I am CERTAIN, I only partially understand that now.

**Comment by UselessGuru** [comment]
> Might be good to explain the link between the algorithm section in the config, the algorithms.txt, the commands in the miner and what the pools return.

Like what I've written here?
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2002

**Comment by Kettoch** [comment]
Actually, that was quite good.  A cleaned up version of this should be integrated into the readme somewhere.  It teaches people how to look at the information and not ask dumb questions like I did.

What about the temp fix for stratum+ssl and stratum+tcp?

**Comment by paulpoco** [comment]
> What about the temp fix for stratum+ssl and stratum+tcp? like what @Kettoch said.

Right now I am only using MPM and MPMC and it is not Benchmarking CryptoNightV7 but other Miners use CryptoNightV7 fine.  When I would also use Nicehash xmrig cpu would Benchmark CryptoNightHeavy but not CryptoNightV7.

http://localhost:3999/algorithms
[
  "CryptoNightV7",
  "Equihash",
  "Equihash1445",
  "Ethash",
  "Ethash2gb",
  "Ethash3gb",
  "Groestl",
  "Keccak",
  "Lyra2RE2",
  "Lyra2z",
  "MyriadGroestl",
  "NeoScrypt",
  "Skein",
  "Yescrypt"
]


[localhost3999miners.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2216471/localhost3999miners.txt)

**Comment by UselessGuru** [comment]
@paulpoco 
Inspect the pools at http://localhost:3999/pools ans look at the protocol value
XmRig cannot mine with pools that have 'stratum+ssl'

**Comment by paulpoco** [comment]
@UselessGuru 
Yes I see that MPH & MPHC is 'stratum+ssl'
    },
    "cryptonightv7": {
      "Algorithm": "CryptoNightV7",
      "CoinName": "Monero",
      "Price": 1.1971092765E-07,
      "StablePrice": 1.1650406438946402E-07,
      "MarginOfError": 0.031024927678379319,
      "Protocol": "stratum+ssl",
      "Host": "us-east.cryptonight-hub.miningpoolhub.com",
      "Port": 17024,
      "User": "paulpoco.multipoolminer",
      "Pass": "x",
      "Region": "US",
      "SSL": true,
      "Updated": "2018-07-21T20:49:45.1916061Z",
      "Name": "MiningPoolHub",
      "Price_Bias": 1.1302568647922471E-07,
      "Price_Unbias": 1.1971092765E-07
    },

**Comment by UselessGuru** [comment]
Replaced by https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2126

**Pull request closed without merging**
