### PR TITLE
Excavator NHMP version 1.5.11a (Nvidia / Nicehash Only)

### PR DESCRIPTION
**Pull request by UselessGuru**
As requested here: https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2030

This PR requires _pending_ https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1903 as a prerequisite.

### CODE REVIEW

**Comment by paulpoco** [comment]
NiceHash Miner 2.0.2.6 is now available!
2018-07-25
Dear NiceHash miners!

New release of the NiceHash Miner is now available for download: 2.0.2.6 - Beta

Version 2.0.2.6 brings the following changes and updates:

**Updated excavator to v1.5.10a
Removed Lbry, Sia, and DaggerHashimoto_Sia (dual)**
Join the conversation about this release on our official NiceHash subreddit.

Your NiceHash team.

**Comment by paulpoco** [comment]
There are a few Equihash Benchmarks on NHMP that fail for some reason, will try and look at logs to see which ones and report back

**Comment by UselessGuru** [comment]
@aaronsace 

Why 👎 ???

**Comment by UselessGuru** [comment]
@paulpoco 

> API level has gone from 0.1.6 and bumped to 0.1.7

No impact: https://github.com/nicehash/excavator/commit/1da95b2843fe20d611ad8d36c9d820894bf8a4f7#diff-8a5da52ed126447d359e70c05721a8aa

> There are a few Equihash Benchmarks on the 1.5.9a that fail for some reason

Probably out of memory - You must have at least a swap file as large as the sum of installed graphics memory.

**Comment by paulpoco** [comment]
@UselessGuru My swap was 16384, will increase to 16384 x 1.5 and see how that goes.  2 x 1070 8G cards.

**Comment by paulpoco** [comment]
[[2018-07-28 09:59:58.060385] [thread=0x00003fcc] [debug]]

	wrkr0-0 | Fetched new work, job_0 '00000072e6abc1fa'


[[2018-07-28 09:59:58.130403] [thread=0x00003bc4] [debug]]

	wrkr1-3 | Fetched new work, job_0 '00000072e6abc1fa'


[[2018-07-28 09:59:58.160815] [thread=0x00003af0] [debug]]

	wrkr0-2 | Fetched new work, job_0 '00000072e6abc1fa'


[[2018-07-28 09:59:58.228827] [thread=0x00003fe0] [debug]]

	wrkr1-1 | Fetched new work, job_0 '00000072e6abc1fa'


[[2018-07-28 09:59:58.234829] [thread=0x00003e2c] [info]]

	net | pascal | New job '0000009c4357dfce', diff=4


[[2018-07-28 09:59:58.918983] [thread=0x00003af0] [fatal]]

	wrkr0-2 | CUDA error 'out of memory' in func 'cuda_daggerhashimoto_pascal::run' line 662


[[2018-07-28 09:59:58.922987] [thread=0x00003e2c] [info]]

	Shutting down


[[2018-07-28 09:59:58.924986] [thread=0x00003e2c] [info]]

	api | Closing


[[2018-07-28 09:59:58.927986] [thread=0x00003e2c] [info]]

	http | Closing


[[2018-07-28 09:59:59.000002] [thread=0x00003fe0] [fatal]]

	wrkr1-1 | CUDA error 'out of memory' in func 'cuda_daggerhashimoto_pascal::run' line 662


[[2018-07-28 10:00:05.205953] [thread=0x00003fcc] [debug]]

	wrkr0-0 | Hasher interrupted


[[2018-07-28 10:00:05.445000] [thread=0x00003bc4] [debug]]

	wrkr1-3 | Fetched new work, job_1 '0000009c4357dfce'


[[2018-07-28 10:00:05.891099] [thread=0x00003fcc] [debug]]

	wrkr0-0 | Worker thread ended


[[2018-07-28 10:00:05.944115] [thread=0x00003bc4] [debug]]

	wrkr1-3 | Hasher interrupted


[[2018-07-28 10:00:06.122153] [thread=0x00003bc4] [debug]]

	wrkr1-3 | Worker thread ended

**Comment by paulpoco** [comment]
Maybe when an algo is not connecting, after a bit sooner it switches to something else?
image

**Comment by paulpoco** [comment]
1 and 2 Thread Equihash seem to fail to connect properly.

**Comment by paulpoco** [comment]
Option to set a different Nicehash server when their servers are down?
image

**Comment by paulpoco** [comment]
@UselessGuru is it only me having some algos not working correctly?
image
image

I left them as is per the PR.  In the past there was 3 algos that wouldn't work, and I would # the lines out of the ones that didn't work.

**Comment by UselessGuru** [comment]
@paulpoco 
> So like previous versions the first 3 algos from ExcavatorNHMP.ps1 don't work: cryptonightV7, daggerhashimoto, equihash.

I get ALL algorithms working just fine. I can't see why it is not working for you.
Could you please post the Excavator log files - thank you. Maybe I can see something of interest.

**Pull request closed without merging**
