### PR TITLE
New: NVIDIA-CryptoDredge Miner version 0.9.2

### PR DESCRIPTION
**Pull request by paulpoco**
CryptoDredge: Update to version 0.9.2
Important: This version requires CUDA drivers 9.2. Make sure you update your Nvidia drivers!

The new version brings substantial speed improvements, so for best results it is recommended to re-benchmark (=delete stat files for this miner).

https://bitcointalk.org/index.php?topic=4807821.200

Algorithms:

    "aeon"      = "" #Aeon, new in 0.9 (CryptoNight-Lite algorithm)
    "allium"    = "" #Allium
    "blake2s"   = "" #Blake2s, new in 0.9
    "cnheavy"   = " -i 5" #CyptoNightHeavy, new in 0.9
    "cnhaven"   = " -i 5" #CryptoNightHeavyHaven, new in 0.9.1
    "cnv7"      = " -i 5" #CyptoNightV7, new in 0.9
    "cnfast"    = " -i 5" #CryptoNightFast, new in 0.9
    "cnsaber"   = " -i 5" #CryptonightHeavyTube (BitTube), new in 0.9.2
    "lyra2v2"   = "" #Lyra2REv2
    "lyra2z"    = "" #Lyra2z
    "neoscrypt" = "" #NeoScrypt
    "phi"       = "" #PHI
    "phi2"      = "" #PHI2
    "skein"     = "" #Skein
    "skunkhash" = "" #Skunk
    "stellite"  = " -i 5" #CryptoNightXtl, new in 0.9
    "tribus"    = "" #Tribus, new with 0.8

### CODE REVIEW

**Comment by Dewbs** [comment]
CryptoDredge v0.9.1
New CryptoNightHaven algorithm
Fix issue related to many rejected shares on NiceHash pool when used CryptoNight-like algorithms

https://github.com/technobyl/CryptoDredge/releases

**Comment by Dewbs** [comment]
Nicehash seems to be ok now

**Comment by Dewbs** [comment]
Hmm correction - heavy benchmarks ok but light benchmarks as '0' - could maybe use extended interval?

**Comment by Dewbs** [comment]
I don't understand - I tried light again:

[CryptoDredge-GPU#01-4001_2018-09-05_00-02-20.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2350568/CryptoDredge-GPU.01-4001_2018-09-05_00-02-20.txt)
[CryptoDredge-GPU#02-4002_2018-09-05_00-02-20.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2350569/CryptoDredge-GPU.02-4002_2018-09-05_00-02-20.txt)
[CryptoDredge-GPU#00-4000_2018-09-05_00-02-20.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2350570/CryptoDredge-GPU.00-4000_2018-09-05_00-02-20.txt)

still benchmarks at '0' after ~10mins of benching ?

**Comment by UselessGuru** [comment]
Included in https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2189

**Pull request closed without merging**
