### PR TITLE
Report status info to monitoring site

### PR DESCRIPTION
**Pull request by grantemsley**
I needed a way to monitor all my workers and make sure none of them have died, rebooted for windows updates, etc.  This adds a feature to send a web request to a remote monitoring server on every loop.

It's intended to report to the web interface I built here: https://github.com/grantemsley/mpm-monitor, but anyone could build their own web interface or android app or whatever to store and view the data.
image 2

If you want to test it against my web server, the MinerStatusURL is "http://mining.emsley.ca/miner.php", and you can lookup your address at "http://mining.emsley.ca".  Just add "-MinerStatusURL http://mining.emsley.ca/miner.php" to your parameters in Start.bat

### CODE REVIEW

**Comment by grantemsley** [comment]
The only part I'm not happy with is around like 485, searching through $Miners to find the matching one just to get the pool name.  It might be more efficient to just add the pool name to each $ActiveMiners object when they are created, but I couldn't figure out how to do that without breaking things.

**Comment by CptanPanic** [comment]
I would like to see a more general API setup where mpm would create a rest server. Possible to flip your change around?

**Comment by grantemsley** [comment]
@CptanPanic  It's possible, but the reason I went this route is that I have workers spread out in different places on different networks.  Having them push data to a central server rather than polling them means not having to deal with port forwarding on each connection or adding new ones to poll.  Any new worker I setup just automatically reports to the server.

I also will be adding a rest API to the website code that spits everything out as JSON to be polled by a local GUI app or android app or what have you.

If anything, I'd eventually add both methods of monitoring - each works better for different use cases.

**Comment by aaronsace** [comment]
@grantemsley Maybe we can get a version of your monitoring server setup on our new domain. Traffic could be high for this though as there may be thousands of updates per minute. 

@fonyo Could look at the logistics of doing this.

**Comment by grantemsley** [comment]
@aaronsace That would be awesome.  I don't mind hosting it for myself and a few friends, but hosting it for everyone would be a bit too much for my little server.

If it's going to be used by the general public, it would need to be changed to a MySQL database instead of SQLite, but that's a pretty simple change to make.

It won't require too much storage, since there's only one record for each unique address+workername combination, with old data getting overwritten.

**Comment by grantemsley** [comment]
Wow I really need to learn how to use git better...just messed this up...fixing it now.

**Comment by fonyo** [comment]
Let me just state this is amazing and would love to test it!

**Comment by fonyo** [comment]
I would like to have a thorough test before we commit to anything. Is there any way to contact you @grantemsley? If you are not happy to disclose details here, please send me a pm on bitcointalk (fonyo) or Skype (fonyo_tnf). Cheers.

**Comment by grantemsley** [comment]
Absolutely.  My email address is in my github profile.  Feel free to email me, or google hangouts at the same email address.

**Comment by paulpoco** [comment]
Yes Windows 10 will restart on its' own for updates.

One solution could be for individual users to have the start.bat file run on startup even if not logged in yet?

Instead of hosting all these monitoring in one Central place, could we use Google Drive to write a file and somehow with IFTT if it sees a file date that gets too old then an IFTT notification happens?

**Comment by grantemsley** [comment]
@paulpoco Starting before someone is logged in will cause problems with some miners, since they won't create windows and that breaks some of them.

If it's a dedicated mining rig, you can turn windows update off through group policies (on pro at least), and/or setup automatic login.  That doesn't really work for people who are mining from their gaming computers in their spare time though.

Sure, you could do logging to google drive or dropbox or whatever, but supporting every different file syncing service would be a nightmare, and you'd very quickly run into issues with the file being changes in multiple locations at once and causing sync errors.

**Comment by paulpoco** [comment]
@grantemsley your right about needing Windows open to open windows.

I am new again to mining.  Did it back in 2013 when that $6 lost wallet.dat is worth about $633 now.

**Comment by grantemsley** [comment]
@paulpoco I had maybe 5-10 bitcoin back in early 2011 when you could still CPU mine them and they were worth around $1 a piece.  God I wish I could find that wallet file now.  Lost forever unfortunately.

**Comment by CptanPanic** [comment]
Looks good, and could use this right away.

**Comment by fonyo** [comment]
Yes, I can confirm we had great walk-through with @grantemsley today and after the required changes on the PS-side, I shall approve. It works great with his website. "mpm-monitor" will require some changes to incorporate with multipoolminer.io. Great work!

**Comment by CptanPanic** [comment]
I am having problems trying this out.  I added -minerstatusurl http://192.168.1.82:1234 to my start.bat file, but nothing gets posted to the server.  I verifed the server works by doing "curl -H "Content-Type: application/json" -d '{"screencast":{"subject":"tools"}}' 192.168.1.82:1234" from computer and it works. What am I missing?

**Comment by grantemsley** [comment]
@CptanPanic if you are using my mpm-monitor site, you need to set the minerstatusurl to have ```/miner.php``` at the end.

**Comment by CptanPanic** [comment]
@grantemsley  I found the issue.  Problem is Address parameter for me is not set since I am using MPH.  So I changed the Address parameter in ReportStatus.ps1 to not be required.

**Comment by grantemsley** [comment]
@cptanpanic address is used as the database key to lookup your workers in my website.  So it's very much required.

If you have created your own web tool then cool.

**Pull request merged**
