### PR TITLE
Disable Nist5 algorithm

### PR DESCRIPTION
**Pull request by UselessGuru**
Nist5 is ASIC territory and mining with CPU or GPU is no longer profitable

### CODE REVIEW

**Comment by mkirov0** [comment]
One question... hypothetically shouldn't the free market (the profits per Mhs reported by the pools) put Nist5 at the bottom of the list as far as MPM is concerned, since the profits per Mhs would just drop off a cliff?
There is a "3" instead of "#" in the EcavatorNvidia1.ps1 just FYI

**Comment by UselessGuru** [comment]
> One question... at the bottom of the list

For that very reason I'd like to remove it from all miners. There is no point in keeping it in the config if it will never be profitable again. This saves precious CPU ticks and makes MPM more efficient.

> There is a "3" instead of "#" in the EcavatorNvidia1.ps1 just FYI

👍 Corrected.

**Comment by mkirov0** [comment]
That makes sense!
Thanks!

**Comment by mkirov0** [comment]
Sorry I'm polluting this space, but I don't think its worth it opening a new issue with this question:
Am I safe to assume I can disable

- Blake2b
- Cryptonight (I see a PR was just created for this one)
- Lbry
- Myriad-Groestl
- Nist5 (the one from this PR)
- Pascal
- Quark
- Qubit
- Skein
- X11
- X11Ghost

**Comment by grantemsley** [comment]
Are those all algorithms that are mined on ASICs now?  If so, yep, and we should probably just remove them altogether.

**Comment by mkirov0** [comment]
I used this site to check the ASIC market:
https://www.asicminervalue.com/
There are ASIC offers for each algo above.  I think it is legit, but haven't used their services myself.

As far as removing the algos IMHO as a new user I would rather see all of them commented out in the miner file with a short explanation just like UselessGuru did with Cryptonight and Nist5. If these algos were missing from the miner files before I did this ASIC investigation, as a new user I would have felt like the algos were just missed by the devs and I am about to reinvent the wheel. And at that point I would enable them and eventually learn the hard way why they were disabled in the first place 😄 that could be just me tho 😄

**Comment by angelics** [comment]
asic algo = sha256,scrypt,x11,x13,x14,15,quark,qubit,decred,lbry,sia,Pascal,cryptonight,cryptonight-light,skein,myr-gr,groestl,nist5,sib,x11gost,veltor,blakecoin,vanilla,equihash,ethash
the only profitable asic algo is ethash
new user dont check miner file. the 1st thing they check/ change is the documentation / start.bat
put REM asic algo=blablabla in bat file and remove all the algos related will be much better. imo

**Pull request merged**
