### PR TITLE
SRB Miner version 1.6.5 (AMD only)

### PR DESCRIPTION
**Pull request by UselessGuru**
Moved writing config and pools file to API

directory stucture based on https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1931

### CODE REVIEW

**Comment by UselessGuru** [comment]
@aaronsace 

I think we should keep name/algo for the config files. 
This allows for individual manual fine tuning it the config files per algo. If we make the port number the unique naming property then the config file get rewritten on each algo change.

**Comment by UselessGuru** [comment]
@aaronsace 

What about my argumentation? This PR has been ready for quite a while.

**Comment by aarona907** [comment]
Doesn't work for me.  Its not building the pool.txt file properly or passing arguments to the command line correctly.  Line 91 looks to be a duplicate and needs to be removed to build the pool.txt file.  I just started to play with MPM so I could be way off.

**Comment by UselessGuru** [comment]
@aarona907 

Did you put the API file in the API folder?
Line 91 is not a duplicate:

```
            $Arguments = @(
                [PSCustomObject]@{
                    Config = [PSCustomObject]@{
                        api_enabled      = $true
                        api_port         = [Int]$Miner_Port
                        api_rig_name     = "$($Config.Pools.$($Pools.$Algorithm_Norm.Name).Worker)"
                        cryptonight_type = $Algorithm
                        intensity        = 0
                        double_threads   = $false
                        gpu_conf         = @($Miner_Device.Type_PlatformId_Index | Foreach-Object {
                            [PSCustomObject]@{
                                "id"        = $_  
                                "intensity" = 0
                                "threads"   = [Int]$Threads
                                "platform"  = "OpenCL"
                                #"worksize"  = [Int]8
                            }
                        })
                    }
                }
                [PSCustomObject]@{
                    Pools = [PSCustomObject]@{
                        pools = @([PSCustomObject]@{
                            pool = "$($Pools.$Algorithm_Norm.Host):$($Pools.$Algorithm_Norm.Port)"
                            wallet = $($Pools.$Algorithm_Norm.User)
                            password = $($Pools.$Algorithm_Norm.Pass)
                            pool_use_tls = $($Pools.$Algorithm_Norm.SSL)
                            nicehash = $($Pools.$Algorithm_Norm.Name -eq 'NiceHash')
                        })
                    }
                }
            )
```

There are two items in the arguments array:
1. Config  (-> [MPM\Bin\AMD-SRBMiner-CryptoNight]\Config_[MinerName]_[Algorithm].txt)
2. Pools   (-> [MPM\Bin\AMD-SRBMiner-CryptoNight]\Pools_[PoolName]_[Algorithm].txt)

These will get converted into two configuration files. This conversion will take inside the API file.

**Comment by aarona907** [comment]
@UselessGuru 

Here is what the log files produce when I run the script.  It outputs a pool file but it is blank.  Config file is output fine.

MPM Log
2018-08-02 09:23:57 INFO: Starting miner (SRBMiner-1-GPU#01-GPU#02): 'C:\Users\Aaron\Desktop\MultiPoolMiner-master\Bin\AMD-SRBMiner-CryptoNight\SRBMiner-CN.exe [{"Config":{"api_enabled":true,"api_port":5202,"api_rig_name":"gminer","cryptonight_type":"heavy","intensity":0,"double_threads":false,"gpu_conf":" "}},{"Pools":{"pools":""}}]'

SRBMiner Log
'wmic' is not recognized as an internal or external command,
operable program or batch file.
Pools must be an array of pools
Unknown error parsing pools config.

If you have it working on a rig I'm sure it is something wrong on my end.  I will spend a little more time on it later.

**Comment by UselessGuru** [comment]
@aarona907 

Can you see if the additional change I just added to multipoolminer.ps1 does the trick?

https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1915/commits/932463556048f10ad8e42d1eb0d5652ac2842be8

Line 428
        if ($Miner.Arguments -isnot [String]) {$Miner.Arguments = $Miner.Arguments | ConvertTo-Json **-Depth 10** -Compress}

This change is originally from https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2038 but can be pplied here too.

Side note: The WMIC error is confusing... none of the MPM code does anything with WMIC. ???

**Comment by UselessGuru** [comment]
> Are you using the wmic when dealing with or monitoring processes? 

No, none of the MPM code does anything with WMIC.

**Comment by UselessGuru** [comment]
Replaced with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2122

**Pull request closed without merging**
