### PR TITLE
Add X11evo to CcminerSib

### PR DESCRIPTION
**Pull request by mkirov0**
Top performing miner for x11evo (tested on 1070)

It is also the top performing miner for:
Blakecoin
Blake2s

### CODE REVIEW

**Comment by grantemsley** [comment]
Are blakecoin and blake2s ones that actually have ASICs?  I can't find any info to that effect.

**Comment by mkirov0** [comment]
Guilty as charged. I copied from here: 🙂 
[https://github.com/MultiPoolMiner/MultiPoolMiner/blob/master/Miners/CcminerKlaust.ps1](url)
I can enable them tho

**Comment by grantemsley** [comment]
If they are profitable, enable them please.

**Comment by mkirov0** [comment]
Added a few more while at it...

**Pull request merged**
