### PR TITLE
Separate configuration and add GUI for configuring

### PR DESCRIPTION
**Pull request by grantemsley**
@fonyo Here it is!

This moves all configuration into a separate Config.ps1, instead of being specified as parameters on the command line or in start.bat

It adds a setup program which gives a nice GUI for configuring all the options.  The default starting configuration is all in Config.sample.ps1.  If a Config.ps1 file already exists, it's settings will be loaded so you can change them.

The lists of pools, algorithms and miners are all dynamically created the same way they work in the main script, so they will appear automatically in the lists.

The GUI will only work on windows, but Config.sample.ps1 can be copied to Config.ps1 and edited manually when this is eventually ported to linux.  Editing a config file is the more linux way anyways, since most wouldn't have a GUI at all.

### CODE REVIEW

**Comment by aaronsace** [comment]
Not sure about this, please nobody merge it unless I say so.

**Comment by grantemsley** [comment]
I've love to hear your thoughts on it @aaronsace, once you've had a chance to look over it.  And let me know if there's anything you want me to change.

**Comment by fonyo** [comment]
It does require thorough testing to ensure everything is right but I support the idea. It should not make the start.bat file obsolete, though? And you also need a batch file for the setup and to run the gui as people don't know how to run PS files.

**Comment by grantemsley** [comment]
@fonyo I removed the pool specific bat files since they wouldn't work anymore.  Start.bat is still there.

And yeah, I suppose it does need a bat file to launch the setup...forgot the default isn't to run PowerShell scripts on most people's systems.

**Comment by UselessGuru** [comment]
I very much like this approach - wasn't it me who raised it in some thread ;-)

I will test it for sure!

**Comment by UselessGuru** [comment]
Does not retrieve miners... what am I doing wrong?
My miner files have been slightly modified. What are the requirements for them to show in the GUI list?

**Comment by grantemsley** [comment]
@UselessGuru to load the miners, it does this around line 33 of setup.ps1
```
$Miners = Get-ChildItemContent "Miners" -Parameters @{Pools = $Pools; Stats = $Stats} | ForEach-Object {$_.Content | Add-Member Name $_.Name -PassThru}
$MinerList = $Miners | Select-Object -ExpandProperty Name -Unique | Sort-Object
```
Depends on what changes you've made in your own version.

**Comment by tarioch** [comment]
I would really like this as well.
One thing that I'm also wondering about when touching the config anyway. It would be nice to be able to override currency and address for certain pools directly in the config instead of having to edit the pool files.

**Comment by UselessGuru** [comment]
> Depends on what changes you've made in your own version.

I found the issue:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/853/commits/ef8d32782ef542267d7a824badc00a65beedcb35

Another possible issue:
What will happen if a pool cannot be accessed? As I see it this will lead to incomplete config data and when clicking save you might loose the parameters for the inaccessible pool.

**Comment by grantemsley** [comment]
@UselessGuru that's true about pools that are not responding.  I'll see what I can do about that.

**Comment by UselessGuru** [comment]
> I'll see what I can do about that.

Commit my pull :-)

**Comment by grantemsley** [comment]
@UselessGuru what pull?

**Comment by UselessGuru** [comment]
https://github.com/grantemsley/MultiPoolMiner/commit/b133dd08123bff2c6c7adae49beefcfac906ac65

**Comment by grantemsley** [comment]
Ah, you pushed that directly to THIS pull request.  Since you're a collaborator here, you have write access to the branch on my fork.  No need for me to commit it, you already did :)

**Comment by UselessGuru** [comment]
Still trying to understand github desktop 👍

**Comment by grantemsley** [comment]
The entire GUI is written in powershell.  I used visual studio to create the xaml for it.

**Comment by grantemsley** [comment]
@UselessGuru I can change the save button to separate apply and exit buttons.

Do you think it still needs the Next button, or do you think people understand how tabs work?

**Comment by UselessGuru** [comment]
> Do you think it still needs the Next button

Yes, it kinda helps that all tabs will be seen/changed.
The sexy version: Keep the save button greyd out until all pages have been visited once (on first start only, flag could be an existing 'config.ps1'. Like this the GUI would become a wizard.

**Comment by grantemsley** [comment]
@UselessGuru your Fix miners commit adds ```$GPUs = (Get-GPUdevices $Type $False)``` - I'm guessing that's something that only belongs in your own branch?

**Comment by grantemsley** [comment]
Disabling the save button until they've seen all the tabs is easy to do...but I'm not sure I'd want to go that far.  Most people should probably just leave all the defaults  anyways.

Maybe leave it greyed out until they visit at least the User Info tab?

**Comment by UselessGuru** [comment]
> $GPUs = (Get-GPUdevices $Type $False)

true, missed that. This is needed for one of my features to run individual miner instances per GPU type.
Does NOT belong to the main branch - remove it!

**Comment by UselessGuru** [comment]
> until they visit at least the User Info tab?

makes sense, but I like to force user to see all the goodies ;-)

**Comment by UselessGuru** [comment]
> $Algorithm needs to be run through Get-Algorithm too.

It's doing it, doesn't it?

$AlgorithmList = $AllPools.Algorithm | `Foreach-Object {Get-Algorithm $_} |` Select-Object -Unique | Sort-Object

**Comment by grantemsley** [comment]
@aaronsace Would it be faster to get this merged if I split it into two parts?  One for moving configuration to config.ps1, and a separate one for the setup GUI portion?

I'm hoping to at least get the configuration changes portion merged.  Not having that part merged is making it harder for me to juggle all the branches I'm working on :)

**Comment by aaronsace** [comment]
@grantemsley Great, it was too complex with the GUI. I want the configuration for 2.7.2. I'll review this tonight.

**Comment by grantemsley** [comment]
This has both the GUI and the configuration changes.  I take it you mean you do want me to split them up?  If so, close this and I'll create a PR for just the config changes, then we can work out the setup gui separately.

**Comment by aaronsace** [comment]
@grantemsley Sorry, misunderstood the pull listed under the comment. Yes please.

**Comment by grantemsley** [comment]
Closing in favour of #964

**Pull request closed without merging**
