### PR TITLE
Add feature to set zpool payout currency.

### PR DESCRIPTION
**Pull request by nnymsgthb**
Add a way to set the desired zpool payout currency via a new command line parameter named "ZpoolCurrency". There might be better names for the parameter, so feel free to change it.

### CODE REVIEW

**Comment by grantemsley** [comment]
You'd also need to have a valid wallet address for whatever currency you are using, no?

**Comment by nnymsgthb** [comment]
That's correct. I'm just using zpool and miningpoolhub. So I can just change the "-wallet" command line parameter, because it just affects zpool. I suppose if one wanted to use some of the other pools simultaneously, then it would be necessary to add separate "-wallet" command line parameters (e.g. "-ZpoolWallet") for the different pools.

**Comment by aaronsace** [comment]
Someone else is proposing a solution to non-BTC payments but I would reject both in the current state. 
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/898

Main issue here: 
Don't mention pool names in the main code, it needs to be generic.

**Comment by nnymsgthb** [comment]
Ok, that's reasonable. How about moving the pool specific information (e.g. walletadress, payout currency, etc.) to separate config files. This would also help to clean up the string of command line parameters in the start.bat. Unfortunately, I dont have enough experience in PS to do it. Also it would make sense to implement it, if you preffered a different solution.

Great piece of software btw. Thank you very much.

**Comment by mtbor** [comment]
Why not just use c=(coin) in the password field, this is supported by several yiimp type pools.

I have used c=dgb and c=xvg to much success.   Just make sure it's a coin the pool mines and it doesn't show red on the page (indicating they don't have enough to pay out).

**Comment by aaronsace** [comment]
This will be included in an upcoming config file update.

**Pull request closed without merging**
