### PR TITLE
Improvements to Get-Binaries

### PR DESCRIPTION
**Pull request by grantemsley**
- New command line parameters:
    - `-VerifyOnly` will check the hashes of miners without downloading anything
    - `-Overwrite` will automatically delete old versions and redownload the latest version for you, instead of needing you to manually delete them first
    - `-SkipCPU`, `-SkipAMD`, and `-SkipNVIDIA` will skip downloading miners for the specified types. Miners that work with multiple types will still be downloaded if you haven't excluded all the types it supports
- Freshly downloaded miners will have their hashes checked immediately after being installed.  Previously they would only be checked if you ran the script a second time
- If overwriting an old miner, the associated stats files are also deleted to ensure the miner gets rebenchmarked
- Rewrote most of the logic of the script to make it a bit faster and easier to follow
- Added safeguards to ensure only files in the script's Bin directory can be deleted - it will never be able to delete anything outside of that directory

### CODE REVIEW

**Comment by thinkplaystudios** [comment]
Does it make sense to archive previously downloaded miners just in case reversion is required?  And in that vein, have a way to go back to any previous version even though the code knows a newer version exists?

**Comment by grantemsley** [comment]
@thinkplaystudios The previous versions' zip file will still be in the .\Downloads directory if you need it.  It doesn't delete those.

If you wanted to revert to an earlier version, the easiest way would be to grab the older miner file (git stores a complete history of every file changed, so you can go find the old version easily).  Or if you only want to keep the old version temporarily, you can just not use `-Overwrite`

**Comment by thinkplaystudios** [comment]
@grantemsley thanks, that helps.

**Comment by UselessGuru** [comment]
@grantemsley 

Suggestion: Add detection for CPU OpenGL if not installed.
We should really get OpenCL installed for CPUs too.

**Pull request merged**
