### PR TITLE
Central list of unprofitable algorithms, valid for all miners

### PR DESCRIPTION
**Pull request by mkirov0**
Lets see if this helps with speeding things up.

### CODE REVIEW

**Comment by grantemsley** [comment]
How does this differ from the ExcludeAlgorithm setting we already have?

**Comment by grantemsley** [comment]
Ok, that's a reasonable point...so why not just fix ExcludeAlgorithm to not affect secondary algorithms then.

**Comment by UselessGuru** [comment]
> so why not just fix ExcludeAlgorithm 

Nothing to fix. ExcludeAlgorithm excludes algorithms completely and works as designed.
Unprofitable algorithms however still might be profitable as secondaries.

What you might be asking for is 'ExcludePrimaryAlgorithm'.
My approach is similar to removing algos (=editing miner files) from each and every miner. But simpler because it offer a single point of configuration.

**Comment by grantemsley** [comment]
Ok, that makes sense.

Still don't like it being it's own separate file - configuration belongs in the config.txt file.

**Comment by mkirov0** [comment]
I agree on the organization level it is probably easier if everything is in one place. I also think tho that the list will not be altered often and the average user will probably rely on the list provided with the master and will not touch it at all. Honestly I can see this done both ways, just my 2 cents...

**Comment by UselessGuru** [comment]
@grantemsley 

If we make it a part of the config we cannot update the list by just replacing a single file.

From where would you take the data for the configuration file? I don't want to keep this information somewhere hardcoded in the ps1 files.

**Comment by grantemsley** [comment]
From command line parameters and/or config.txt file like we do with ever other setting?

**Comment by UselessGuru** [comment]
> From command line parameters and/or config.txt 

config.txt: There is no more default config.txt that we can pre-populate. The content of the default config.txt is entirely built with variables, but no hard coded values.

So we're back to command line parameters, which I don't see as a good option because they are a headache if we want to update centrally the list.

The idea behind my list is simple:
Whenever a new ASIC comes out and ruins profitability of an algo we just add the algo to the list - done.
Much simpler than telling the user to manually editing an long list of algos, and that for each start bat file.

**Comment by grantemsley** [comment]
Ok yeah that makes sense then.

**Pull request merged**
