### PR TITLE
Add PhoenixMiner

### PR DESCRIPTION
**Pull request by adamje42**
Miner can be found here:
https://bitcointalk.org/index.php?topic=2647654.0

Install contents in \Bin\PhoenixMiner\

### CODE REVIEW

**Comment by UselessGuru** [comment]
Miner is fast!

1. There is no direct link, so we either have to document installation in readme, or host the miner here.
2. The miner code needs to be enhanced so it does not use cards with less than 3GB vram for ethash mining. I will take care of this.

**Comment by Sniffle** [comment]
Testing this, I've made it repeat the benchmarking twice for AMD cards and it only detects one of my 2 RX580 8GB cards.

**Comment by adamje42** [comment]
@Sniffle What's the command generated by MPM to start the miner?

**Comment by Sniffle** [comment]
You'll have to give me a few to get back to it, I've got to get kids to bed.  I'll edit this when I can get there

**Comment by adamje42** [comment]
@UselessGuru After looking at the readme for PhoenixMiner I believe the problem is that PhoenixMiner starts Device IDs at the number 1, rather than 0.

@Sniffle Could you create a .bat in the PhoenixMiner folder with just the code:
`PhoenixMiner.exe -list`
and show us the output.

**Comment by UselessGuru** [comment]
@Sniffle 

To further analyze your setup I need a complete list of OpenGL devices as found by MPM.
Howto:
- open a powerhell console (`pwsh.exe`)
- change to the MPM directory (cd \[MPM directory]
- type `using module .\Include.psm1`
- run `[OpenCl.Platform]::GetPlatformIDs() | ForEach-Object {[OpenCl.Device]::GetDeviceIDs($_, [OpenCl.DeviceType]::All)} | Where {$_.Type -eq 'GPU' -and $_.Vendor -eq 'NVIDIA Corporation'} > Logs\OpenGL.txt`
- upload the file 'Logs\OpenGL.txt' here

**Comment by UselessGuru** [comment]
@adamje42 
> After looking at the readme for PhoenixMiner I believe the problem is that PhoenixMiner starts Device IDs at the number 1, rather than 0.

True, but confusing. All other miners begin with 0, and then how is that supposed to work with MORE than 10 cards? It says '-gpus <123 ..n> Use only the specified GPUs (if more than 10, separate the indexes with comma)'???

I have updated the miner files to start indexing with 1

**Comment by Sniffle** [comment]
I haven't had a chance to do the diagnostic work you requested.  I did however have the opportunity to grab the new files and rebenchmark the Ethash algorithm, and while now both cards are detected, the benchmark looks like it might fail as it is throwing the error failed to connect to miner phoenixmineramd.

I'll attach logs as soon as I'm able gotta get back to the kids.

**Comment by adamje42** [comment]
@Sniffle Should be fixed now.

**Comment by Sniffle** [comment]
@adamje42 that got it, it now benchmarks,a and is roughly on par with claymore, only time will tell if it ends up beating out claymore overall

**Comment by UselessGuru** [comment]
@aaronsace 

Should we commit?
There is no direct DL link. I think updating 'downloader.ps1' could make sense. How about a message saying something like 'Go to http://... and DL manually?

**Comment by aaronsace** [comment]
@UselessGuru If you think it's good another then I'll add it to the next release package. Merge and put the forum link in the miner URL.

**Comment by Braintelligence** [comment]
@aaronsace Looking forward to next release. Thanks for your hard work!

**Pull request merged**
