### PR TITLE
Allow for comments in JSON files

### PR DESCRIPTION
**Pull request by UselessGuru**
Skips lines beginnig with # ... this allows for extra comments
Standard MS implementation does not allow contents in JSON files :-(

### CODE REVIEW

**Comment by grantemsley** [comment]
Will this work for in line comments as well, ie:

```
"Interval": "$Interval",
"Region": "$Region", # Can be: us, asia or europe
"SSL": "$SSL",
```

**Comment by UselessGuru** [comment]
> Will this work for in line comments as well? ie:

Nope, just for lines beginning with #
But at least you can put some comments in. I could probably change the code so that it also allows inline comments, but that would it probably make slower.

**Comment by UselessGuru** [comment]
I changed it so it allows for the following:

# Comment
"Interval": "$Interval", #Comment
"Region": "$Region", # Can be: us, asia or europe
"SSL": "$S<#Comment#>SL",

Limitation: It does not support a# in between two ""

**Comment by aaronsace** [comment]
@UselessGuru I'd rather keep the JSON standard. There is a readme and a GUI coming anyway.

**Comment by UselessGuru** [comment]
> and a GUI coming anyway.

Also for Linux?

**Comment by aaronsace** [comment]
@UselessGuru Will Linux users be as dumb as Windows users and not read the readme...?

**Comment by UselessGuru** [comment]
@aaronsace 

> Will Linux users be as dumb as Windows users and not read the readme...?

Yes, I'll find you some!
I really believe that having comments makes sense - especially for Linux users where editing command files is standard. But JSON files are not the easiest to edit manually, every comma counts!

**Comment by aaronsace** [comment]
Yes, it's easy to break JSON but it means that it's always precise. Sure we can get a GUI going if needed. If I start to include the readme text file in the release then it may help.

**Comment by aaronsace** [comment]
Not going to be merging this.

**Pull request closed without merging**
