### PR TITLE
Update XmrigCryptonight: Enable per device mining, rename miner

### LINKED ISSUE #1965: XMRig-CPU Fails for brand new install
Apparently it cannot use the default config file from the package.

When used, it overrides the API PORT and other things.  Need to determine if a minimalist config file will allow it to launch so that command line parameters will work.

### PR DESCRIPTION
**Pull request by paulpoco**
### Important: The Nvidia variant does not work in rigs with multiple nvidia card models!!!

**If all cards are of the same model (regardless of manifacturer) it should work fine. The Amd variant is not affected by this.**

Update XmRig CPU to version 2.6.4
Update XmRig Nvidia to version 2.7.0-beta
Update XmRig AMD to version 2.7.3-beta

As an exception to the rule we go for beta versions because this is the only available code to support the new cn algorithms.

Changes:

cryptonight-lite/ipbc replaced to cryptonight-heavy/tube for Bittube (TUBE).
Added cryptonight/rto (cryptonight variant 1 with IPBC/TUBE mod) variant for Arto (RTO) coin.
Added cryptonight/xao (original cryptonight with bigger iteration count) variant for Alloy (XAO) coin.
Better variant detection for nicehash.com and minergate.com.

Fixes #1965

### CODE REVIEW

**Comment by paulpoco** [comment]
image

Getting that error at start and listed at bottom later.

**Comment by UselessGuru** [comment]
@paulpoco 

Problem seen and fixed.

**Comment by Dewbs** [comment]
[XmRigNvidia-GPU#02-4002_2018-09-05_18-16-19.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353870/XmRigNvidia-GPU.02-4002_2018-09-05_18-16-19.txt)
[XmRigNvidia-GPU#01-4001_2018-09-05_18-15-16.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353871/XmRigNvidia-GPU.01-4001_2018-09-05_18-15-16.txt)
[XmRigNvidia-GPU#00-4000_2018-09-05_18-14-09.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353872/XmRigNvidia-GPU.00-4000_2018-09-05_18-14-09.txt)
[XmRigNvidia-GPU#02-4002_2018-09-05_18-15-16.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353873/XmRigNvidia-GPU.02-4002_2018-09-05_18-15-16.txt)
[XmRigNvidia-GPU#01-4001_2018-09-05_18-13-05.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353874/XmRigNvidia-GPU.01-4001_2018-09-05_18-13-05.txt)
[XmRigNvidia-GPU#02-4002_2018-09-05_18-13-05.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353875/XmRigNvidia-GPU.02-4002_2018-09-05_18-13-05.txt)
[XmRigNvidia-GPU#00-4000_2018-09-05_18-13-05.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353876/XmRigNvidia-GPU.00-4000_2018-09-05_18-13-05.txt)
[XmRigNvidia-GPU#00-4000_2018-09-05_18-18-22.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353877/XmRigNvidia-GPU.00-4000_2018-09-05_18-18-22.txt)
[XmRigNvidia-GPU#01-4001_2018-09-05_18-18-22.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353878/XmRigNvidia-GPU.01-4001_2018-09-05_18-18-22.txt)
[XmRigNvidia-GPU#02-4002_2018-09-05_18-18-22.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353879/XmRigNvidia-GPU.02-4002_2018-09-05_18-18-22.txt)
[XmRigNvidia-GPU#02-4002_2018-09-05_18-17-20.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353880/XmRigNvidia-GPU.02-4002_2018-09-05_18-17-20.txt)
[XmRigNvidia-GPU#00-4000_2018-09-05_18-16-19.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353881/XmRigNvidia-GPU.00-4000_2018-09-05_18-16-19.txt)
[XmRigNvidia-GPU#01-4001_2018-09-05_18-17-20.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353882/XmRigNvidia-GPU.01-4001_2018-09-05_18-17-20.txt)
[XmRigNvidia-GPU#01-4001_2018-09-05_18-16-19.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353883/XmRigNvidia-GPU.01-4001_2018-09-05_18-16-19.txt)
[MultiPoolMiner_2018-09-05.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353902/MultiPoolMiner_2018-09-05.txt)

**Comment by Dewbs** [comment]
[XmRigNvidia-GPU#00-NiceHash-CryptoNightHeavy.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353916/XmRigNvidia-GPU.00-NiceHash-CryptoNightHeavy.txt)
[XmRigNvidia-GPU#00-NiceHash-CryptoNightV7.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353917/XmRigNvidia-GPU.00-NiceHash-CryptoNightV7.txt)
[XmRigNvidia-GPU#01-NiceHash-CryptoNightHeavy.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353918/XmRigNvidia-GPU.01-NiceHash-CryptoNightHeavy.txt)
[XmRigNvidia-GPU#01-NiceHash-CryptoNightV7.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353919/XmRigNvidia-GPU.01-NiceHash-CryptoNightV7.txt)
[XmRigNvidia-GPU#02-NiceHash-CryptoNightHeavy.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353920/XmRigNvidia-GPU.02-NiceHash-CryptoNightHeavy.txt)
[XmRigNvidia-GPU#02-NiceHash-CryptoNightV7.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2353921/XmRigNvidia-GPU.02-NiceHash-CryptoNightV7.txt)

**Comment by paulpoco** [comment]
Works now but I have 2 Nvidia cards that are the same model.

I had XmRigNvidia disabled before because it was never one of the top GPU miners.

**Comment by paulpoco** [comment]
No errors now

**Comment by UselessGuru** [comment]
> Works now but I have 2 Nvidia cards that are the same model.

Same model no problem :-)

Different models will cause issues because at the beginning of each loop MPM will kill one or the other instance of the miner because all instances will have the same process name.

Problematic code:
`    if ($ActiveMiners | ForEach-Object {$_.GetProcessNames()}) {Get-Process -Name @($ActiveMiners | ForEach-Object {$_.GetProcessNames()}) -ErrorAction Ignore | Select-Object -ExpandProperty ProcessName | Compare-Object @($ActiveMiners | Where-Object Best -EQ $true | Where-Object {$_.GetStatus() -eq "Running"} | ForEach-Object {$_.GetProcessNames()}) | Where-Object SideIndicator -EQ "=>" | Select-Object -ExpandProperty InputObject | Select-Object -Unique | ForEach-Object {Stop-Process -Name $_ -Force -ErrorAction Ignore}}
`

A possible solution could be changing the process handling to use PID's.

**Pull request closed without merging**
