### PR TITLE
CryptoDredge Miner version 0.8.3 (Nvidia only)

### PR DESCRIPTION
**Pull request by UselessGuru**
### CryptoDredge: Update to version 0.8.3

**Important: This version requires CUDA drivers 9.2. Make sure you update your Nvidia drivers!**

The new version brings substantial speed improvements, so for best results it is recommended to re-benchmark (=delete stat files for this miner).

https://bitcointalk.org/index.php?topic=4129696.msg42985868#msg42985868

Algorithms:
```
    "allium"    = "" #Allium
    "lyra2v2"   = "" #Lyra2REv2
    "lyra2z"    = "" #Lyra2z
    "neoscrypt" = "" #NeoScrypt
    "phi"       = "" #PHI
    "phi2"      = "" #PHI2
    "skein"     = "" #Skein
    "skunkhash" = "" #Skunk
    "tribus"    = "" #Tribus, new with 0.8
```

### CODE REVIEW

**Comment by paulpoco** [comment]
@UselessGuru 
$ManualUri = "https://bitcointalk.org/index.php?topic=4129696.0" is now closed

new one is https://bitcointalk.org/index.php?topic=4807821

"Watchdog
If you are using a third-party watchdog, you can disable the built-in watchdog by using --no-watchdog option."

https://github.com/technobyl/CryptoDredge/releases

Release 0.8.2 - (August 6, 2018)
Fix Phi2 bug related to smart contracts
Improve Tribus

Release 0.8.1 - (August 3, 2018)
Improve Allium, Lyra2z, and Phi2 for low-end and middle-end graphics cards
Fix P2Pool bug related to many rejected shares
Fix TCP and WebSocket connections used for API
Add power consumption monitoring

**Comment by paulpoco** [comment]
@UselessGuru found bug not using all GPUs.

Line 52
`-d $(($Miner_Device | ForEach-Object {'{0:x}' -f $_.Type_Vendor_Index}) -join '')`
should be
`-d $(($Miner_Device | ForEach-Object {'{0:x}' -f $_.Type_Vendor_Index}) -join ',')`

**Comment by paulpoco** [comment]
Last 3 fixes fixed the double entries

**Comment by paulpoco** [comment]
https://github.com/technobyl/CryptoDredge/releases Version 0.8.3

**Comment by UselessGuru** [comment]
Replaced with https://github.com/MultiPoolMiner/MultiPoolMiner/pull/2125

**Pull request closed without merging**
