### PR TITLE
Update ClaymoreDual miners

### PR DESCRIPTION
**Pull request by UselessGuru**
## One miner file for per ClaymoreDual mining platform (AMD & NVIDIA)

One miner file replaces all individual miner files per platform. The generated miner objects are backwards compatible.

#### New dual mining algorithms or custom intensities
New variants or different intensities can be added to $Commands, one entry = one miner object
Also read: #1491

### Fixes
Support for more than 9 devices: deviceIDs > 10 in hex
Improve pool compatibility: `if ($Pools.$MainAlgorithm_Norm.Name -eq 'NiceHash') {$EthereumStratumMode = "3"} else {$EthereumStratumMode = "2"}`
Also read: #1470

#### 3gb Limitation
By default Ethash uses only Cardswith 4GB VRAM, 3GB cards can no longer be used
Ethash2gb parameter is still supported
Ethash3gb parameter (future MPM enhancement) will use cards with > 3GB VRAM
Also read: #1497

#### Fee Calculation
(See #1237 and #1152)

Miner fee(s) will be deducted from returned hashrate
$MinerFeeInPercentSingleMode = 1.0
$MinerFeeInPercentDualMode = 1.5
Property 'fees' added to miner (array) so it can be used in core

### What's updated in this PR
- Simplify code: use $Devices for device selection
- Bring AMD variant to the same code base as NVIDIA

### Prerequisites
This change requires new functions Get-Devices &  Get-DeviceIDs  to be present. These are in the master code base since https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1633

### How to update:
Manually remove all obsolete miner files in the 'Miners' folder with the following file names:
- ClaymoreAmd*.txt & ClaymoreNvidia*.txt.

Also delete the obsolete benchmark files in the 'Stats' folder:
-  ClaymoreAmd_*_.HashRate.txt

Note: This update will trigger some updated miners to benchmark again.

### CODE REVIEW

**Comment by grantemsley** [comment]
Wish I had these last time I had to go edit all 10000 ClaymoreAmd.* files...

One problem I see though - ClaymoreAmd.txt and ClaymoreAmd.ps1 will conflict with each other, no?

**Comment by angelics** [comment]
i have nt mine / test eth mining much. can u actually set different difficulty for diff dual mining?
eg. 
eth;keccak:20 = d=20
eth;keccak:20 = d=40
eth;blake2s:20 = ""
what happen to $commoncommands then? cant find a proper usecase

**Comment by UselessGuru** [comment]
@angelics 

>  is there typo for MainAlgorithmCommands vs MainAlgorithmCommand? 

Thank you or pointing it out. Fixed.

> what happen to $commoncommands then? cant find a proper usecase

I don't quite understand? 
$CommonCommands = @(...)  get applied to ANY algorithm, regardless of difficulty.
The first element applies to the primary algorithm, the second to the second algorithm.
Usecase: You want to restart miner every hour or when some GPU failed in DualMining mode ONLYthe add " -r 60" as second element: `$CommonCommands = @(""; " -r 60")`

>  different difficulty should be properly documented as colon is needed

Changed to array, to be consistent with $CommandCommands = @(...)

**Comment by UselessGuru** [comment]
> One problem I see though - ClaymoreAmd.txt and ClaymoreAmd.ps1 will conflict with each other, no?

I don't have AMD hardware so I cannot test myself, but I cannot imagine the possible issue.
ClaymoreAmd.txt caters for all Non-ClaymoreDual miners. Because they are for different algorithms there will be independent stat files.
MPM-internally it is irrelevant what the source of the miner object is.

Pls correct me if I am wrong.

**Comment by grantemsley** [comment]
> I don't have AMD hardware so I cannot test myself, but I cannot imagine the possible issue.
ClaymoreAmd.txt caters for all Non-ClaymoreDual miners. Because they are for different algorithms there will be independent stat files.
MPM-internally it is irrelevant what the source of the miner object is.

> Pls correct me if I am wrong.

It may not break anything, but it does make it a bit confusing for people working on the miners.  Maybe rename this one to ClaymoreAMDDual?  Or better yet, split the old one up into 4 separate miners - they are actually 3 different miners with different download links and different names.

**Comment by UselessGuru** [comment]
> ClaymoreAMDDual

I want to avoid renaming it for two reasons:
a) to keep the file name in line with the NVidia variant
b) Renaming will also trigger benchmarking.

**Pull request merged**
