### PR TITLE
ClaymoreAmd: Unified miner 

### PR DESCRIPTION
**Pull request by UselessGuru**
## One miner file for all Claymore Dual Amd variants

One miner file replaces all individual miner files. The generated miner objects are backwards compatible.

### New dual mining algorithms or custom intensities
New variants or different intensities can be added to $Commands, one entry = one miner object
Also read: #1491

### Fixes
Support for more than 9 devices: deviceIDs > 10 in hex "[Convert]::ToString($DeviceID, 16)"
Improve pool compatibility: "$(if($Pools.Ethash.Name -eq 'NiceHash'){3}else{2})"
Also read: #1470

### 3gb Limitation
By default Ethash uses only Cardswith 4GB VRAM, 3GB cards can no longer be used
Ethash2gb parameter is still supported
Ethash3gb parameter (future MPM enhancement) will use cards with > 3GB VRAM
Also read: #1497

### Fee Calculation
(as discussed here: #1237)

Miner fee(s) will be deducted from returned hashrate
$MinerFeeInPercentSingleMode = 1.0
$MinerFeeInPercentDualMode = 1.5
Property 'fees' added to miner (array) so it can be used in core
Also read: #1152

### CODE REVIEW

**Comment by grantemsley** [comment]
I've been testing this on several of my systems, with a mix of NVIDIA and AMD cards, and it's working very well.

**Comment by thinkplaystudios** [comment]
This is a nice enhancement and cleans up the files.  Seems to work well.

**Comment by thinkplaystudios** [comment]
Are there already a number of folks running with this?  I'm curious if there is a decent number of folks that have gone ahead with this on their main rigs.

**Comment by grantemsley** [comment]
@thinkplaystudios I'm using it without any issues.

**Comment by angelics** [comment]
missing negative $port in nvidia version
`                Arguments = ("-mode 1 -mport $Port -epool $($Pools.$MainAlgorithm_Norm.Host):$($Pools.$MainAlgorithm_Norm.Port) -ewal $($Pools.$MainAlgorithm_Norm.User) -epsw $($Pools.$MainAlgorithm_Norm.Pass)$MainAlgorithmCommand$($CommonCommands | Select -Index 0) -esm $EthereumStratumMode -allpools 1 -allcoins 1 -platform 2 -di $($DeviceIDs -join '')" -replace "\s+", " ").trim()`
nicelydone

**Pull request closed without merging**
