### PR TITLE
Alexis, KlausT, Nanashi, Tpruvot, SPmod, Cpuminer-opt, Cpuminer-multi updates

### PR DESCRIPTION
**Pull request by Rama-Nujan**
I added all algos that the miners can mine, kept the tpruvot x86 version (for me it was faster on Maxwell and Pascal).

### CODE REVIEW

**Comment by mkirov0** [comment]
I see you adding a lot of algos which is great, but are there any MPM supported pools that mine them?

**Comment by iwtym** [comment]
Hi, the majority are not used - but it is no harm to add in case they become added in pool, they will get picked up by the program. Some of them are used, Cryptov7, M7M, YescryptR16 come to mind.

**Comment by iwtym** [comment]
When/if these get pushed through I can create a new Pull for algo specific miner changes I made.

**Comment by UselessGuru** [comment]
> but are there any MPM supported pools that mine them?

You never know... Pool operators add / remove algorithms at will.
It is good to have all possible algorithms configured. If there are no pools for it they will just be ignored.

**Comment by mkirov0** [comment]
OK thats great then. We definitely need a "AllAlgos" or something similar as placeholder for start.bat tho; because it will be hard to edit such an algo list. Maybe even something like what @angelics mentioned for an ASIC placeholder which will exclude the ASIC-ed algos right from the start.bat

**Comment by iwtym** [comment]
Funny you ask - I use these start files myself. I have no idea how a placeholder would work - but tabbing out algos is not that hard. Only a handful of "general" miners mine more than one efficiently.

**Comment by mkirov0** [comment]
Yeah giving it a second round of thinking "AllAlgos" is not necessary... It could be done with just -excludealgorithm, but it would be nice to have the ASIC-ed algos disabled by default and keep the -excludealgorithm for customizations IMHO of course.

**Comment by UselessGuru** [comment]
> We definitely need a "AllAlgos" or something

This is not needed at all.
Just remove the -algorithm parameter from the start bat.
MPM will use any available algorithm
Note: This is not recommended because it will reduce profitability significally.

**Comment by mkirov0** [comment]
> This is not needed at all.
Agreed. 

Gave it some thinking and realized AllAlgo is not how it should be done... Its just how I've set up my rig in the beginning and it has carried over and over and has turned into a mess... I guess I was resolving my own issues out-loud, but seems like a good time to redo stuff 😄

**Comment by Rama-Nujan** [comment]
> Note: This is not recommended because it will reduce profitability significally.

It was far better for me this way.

**Comment by mkirov0** [comment]
How do we know which miner is most profitable for each algo? Or we are supposed to have all enabled?

**Comment by Rama-Nujan** [comment]
Removed them. A commit I hadn't pushed and reverted slipped in.  Please tell me if you would like the bat files recommitted with Aaronsace's default information like the ones currently in.

**Comment by Rama-Nujan** [comment]
> How do we know which miner is most profitable for each algo? Or we are supposed to have all enabled?

I removed the -algorithm function altogether for myself. Same for -pool.

**Comment by grantemsley** [comment]
Thanks for removing that.  Looked it over again:

- I'd recommend not removing the x64 ccminertpruvot.  If the x86 version is faster on some systems, by all means create a second one called ccminertpruvotx86 with that version.  Leave it to the benchmarking to figure out which is faster on a particular setup.
- Remove CpuminerJayddeeAvx.ps1 - the AVX version of that miner no longer exists. This was removed in master already.

Other than that, I like it.  Makes it easy to see which algos a miner supports, and means immediate support for a lot of them should a pool start mining them.

**Comment by Rama-Nujan** [comment]
Done. Just figured out how to do branches. When this gets pushed in master I'll do branches off master.

**Comment by grantemsley** [comment]
@Rama-Nujan You didn't quite revert tpruvot - exe name needs the -x64

**Comment by grantemsley** [comment]
Errors in algorithms.txt:  

- cryptonightv7 should only be listed once, in lower case
- ziftr is missing a comma after it

**Comment by grantemsley** [comment]
Also please change the folder for ccmineralexis back to \NVIDIA-Alexis78hsr

**Comment by grantemsley** [comment]
Looking good.  Merged.

**Pull request merged**
