### PR TITLE
Change AutoUpdate to DisableAutoupdate

### PR DESCRIPTION
**Pull request by UselessGuru**
Reason:
Script definition has a switch parameter default to true. (PSAvoidDefaultValueSwitchParameter) which is not recommended.

### CODE REVIEW

**Comment by grantemsley** [comment]
I realize it's probably not good form the way it is.  But which of these is easier to parse at a glance?  "AutoUpdate = true" or "NoAutoUpdate = False"?

"If not NoAutoUpdate"...makes the code much harder to read.

**Comment by UselessGuru** [comment]
> "If not NoAutoUpdate"...makes the code much harder to read.

Agree, but Switch variables default to false. So if not present no auto update will take place.
And master Aaron wants that update to be on by default.

**Comment by grantemsley** [comment]
Calling it "$DisableAutoUpdate" would be a little less confusing to me.

**Comment by UselessGuru** [comment]
Changed to Disable..., makes more sense.

**Comment by UselessGuru** [comment]
> Shouldn't you leave out setting the default value entirely? The "= $false" part?

We have in all other switch parameters too. And it does not hurt.

**Pull request merged**
