### PR TITLE
MASSIVE miner update: ZEnemy - ZFast (needs work) - PHI - ASIC udpates etc etc

### PR DESCRIPTION
**Pull request by iwtym**
Some older commits on there + a massive miner update. Can start hammering these through w/ merge permission

### CODE REVIEW

**Comment by grantemsley** [comment]
Thanks for your contribution!

There looks to be a lot of good stuff in there...but also a bunch of irrelevant changes and merge conflicts. And some of them are replacing existing miners with completely different ones from different sources.

It's really hard to review and test a giant change like this.  If you can split it up, make a PR for each miner or something, that would make it a lot easier to get merged in.  As it is, it would be really hard to merge this.

**Comment by mkirov0** [comment]
Dude! You lost me the moment you tried to change the donation wallet address and user...
Thats low sorry...

**Comment by iwtym** [comment]
If I knew how to only push some of my commits I would but I have no idea how this works

**Comment by grantemsley** [comment]
@iwtym in that case, if you want I can take a look at some of the changes you made and make my own pull requests to integrate some of the useful changes.

**Comment by iwtym** [comment]
Actually I think I can fork the current, replace them with some of my changes and re-pull request. Ill start doing that.

**Pull request closed without merging**
