### PR TITLE
Add CCMiner Anxmod Phi

### PR DESCRIPTION
**Pull request by Rama-Nujan**
One of the fastest phi miners around.

### CODE REVIEW

**Comment by UselessGuru** [comment]
Is this any faster?

**Comment by Rama-Nujan** [comment]
Yes much faster than any Phi miners. This and zenemy are close.

**Comment by grantemsley** [comment]
I am testing this.

**Comment by Rama-Nujan** [comment]
I benchmarked this against Alexis and apart from a fast phi implementation its slower

**Pull request merged**
