### PR TITLE
Disable FW update UAC popup

### PR DESCRIPTION
**Pull request by UselessGuru**
Do not update Windows FW rules when using a 3rd party FW, e.g. Symantec Endpoint Protection 14

### CODE REVIEW

**Comment by aaronsace** [comment]
It says you changed all the lines, probably the indents. 

Could you just let me know what you changed that makes this work and why it wasn't working?

**Comment by aaronsace** [comment]
@UselessGuru If you want to join the MultiPoolMiner organization, please can you add me on Skype (username is just aaronsace).

**Comment by UselessGuru** [comment]
> It says you changed all the lines, probably the indents.

This was the old pull... this one properly just changed some lines:
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/874/commits/87da4ba270d171c044e0e53fea264352bb2615ff

untitled

**Comment by aaronsace** [comment]
Think I understand what you are doing now; wasn't getting it yesterday.

**Pull request merged**
