### PR TITLE
Claymore Nvidia post-ASICs Update

### PR DESCRIPTION
**Pull request by Rama-Nujan**
Sadly, Claymore was never all that fast on Nvidia cards. The advent of ASCIs for Blake2s, Decred, Lbry and Pascal have all but eliminated Nvidia cards from those combinations. Keccak remains profitable once in a blue moon.

### CODE REVIEW

**Comment by angelics** [comment]
did u mean blake2b? instead of blake2s? as far as i know, there is no blake2s asic yet.

**Comment by UselessGuru** [comment]
Blake2s is profitable as secondary algo.

**Comment by Rama-Nujan** [comment]
Fixed it!

**Comment by Rama-Nujan** [comment]
Changes made - this can be pulled

**Pull request closed without merging**
