### PR TITLE
CPUMiner-TPruvot: Remove unsupported HMQ1725

### PR DESCRIPTION
**Pull request by UselessGuru**
CPU feature check removed

Directory structure based on https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1931

### CODE REVIEW

**Comment by grantemsley** [comment]
Unfortunately, that won't work.

On an Intel i7-6700K, my driver version is listed as `2527.8 (sse2,avx)`

But this CPU [does have the AVX2 instruction set](https://ark.intel.com/products/88195/Intel-Core-i7-6700K-Processor-8M-Cache-up-to-4_20-GHz), and CpuminerJaydeeAvx2 works great on my system.

I don't think you can rely on OpenCL to show all the available instruction sets - remember, the CPU miners don't actually use OpenCL at all, they talk to the CPU more directly, so the CPU OpenCL driver might not support it, but the miner can still use it just fine.

As far as I can find, there's no powershell native way to determine which instruction sets a CPU has.  It's not in the Win32_Processor information or any other class i could find in WMI.  If we really want to, we could probably find an exe that shows it who's output is easy to parse.  There are plenty of those.  But it's probably easier to just let it fail on systems where it doesn't work.

**Comment by Dewbs** [comment]
https://www.tenforums.com/drivers-hardware/106331-powershell-script-cpu-information-incl-cpuid.html
https://en.wikipedia.org/wiki/CPUID

Any use?

**Comment by grantemsley** [comment]
@Dewbs Nice find.  I could be wrong, but I don't think so.  That will easily determine the exact processor model, but according to that page you have to call cpuid with specific register values to get to the information we need, which I don't think there is a native way to do.

**Comment by UselessGuru** [comment]
@grantemsley 
> On an Intel i7-6700K, my driver version is listed as 2527.8 (sse2,avx)
> But this CPU does have the AVX2 instruction set, and CpuminerJaydeeAvx2 works great on my system.

Can you spot something in the new CPU devices that we could use for the filter? I only have one CPU and hove no information about other computers.

**Comment by grantemsley** [comment]
Not easily, but I'm working on it.  WMI doesn't have the information either.

So far the options I've found are:

- Try to parse the CPUID from WMI - won't work, because it only contains some of the information required.
- Import a C# library to retrieve it like we do with OpenCL - possible, but I'd have to find or code one. This is probably the best option
- Maintain a text file with all possible CPU models and their feature sets - way too much work
- Run a third party cpu info tool and parse it's output - would work, but ugly

**Comment by grantemsley** [comment]
@UselessGuru I found a nice program someone wrote and modified it a bit to make the output easier to parse - https://github.com/grantemsley/FeatureDetector.  It's makes a nice small and fast exe, and is open source unlike most CPU detection tools.

I made it's output look like:
```
C:\>FeatureDetector.exe
MMX
x64
ABM
RDRAND
BMI1
BMI2
ADX
MPX
SSE
SSE2
SSE3
SSSE3
SSE4.1
SSE4.2
AES-NI
AVX
FMA3
AVX2
```

That can easily create an array of supported features in powershell just by doing:
`$features = .\FeatureDetector.exe`
Which I would add to the CPU info generated in #1868 

Then you can just do something like:

`if ("AVX" -in $Device.Info.Features) { ...`

Not sure how you and @aaronsace feel about adding another exe file to the code (we already do with 7zip, so probably not that big a deal?), but this is the best way I've come up with.  It's irritating that on linux it's as easy as `cat /proc/cpuinfo` but on windows there's just no easy way to get that information.

**Comment by UselessGuru** [comment]
@grantemsley 

To me this is perfect - anything is better than lots of errors from failing benchmarks because the feature set is not supported.

@aaronsace 

Maybe you can use the code in the openCL stuff, so we could even make it cross-OS compatible.

**Comment by UselessGuru** [comment]
Further deployment depends on https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1868

**Comment by aaronsace** [comment]
Prefer not to add 'exe' files and even remove 7zip if possible.

**Comment by grantemsley** [comment]
@aaronsace Ok, I'll see if I can find a way to do it without exe files.  Removing 7zip shouldn't be that hard to do either.

**Comment by UselessGuru** [comment]
I removed the CPU feature detection

**Pull request merged**
