### PR TITLE
sgminer x16r

### PR DESCRIPTION
**Pull request by angelics**
sgminer x16r
setx GPU_FORCE_64BIT_PTR 0 is needed for sgminer to run

### CODE REVIEW

**Comment by thinkplaystudios** [comment]
In your experience, have you see SGMINER with GPU_FORCE_64BIT_PTR 1 causing high CPU utilization?  Hence why GPU_FORCE_64BIT_PTR need to be set 0?

**Comment by angelics** [comment]
with ptr 1, the sgminer just crash after checking connection to devfee pool. this is the only way to get the miner run. i do not have any amd with me anymore sadly.

**Comment by grantemsley** [comment]
What card are you using, and specifically how much memory does it have?

That option controls whether OpenCL uses 64bit pointers for memory access - needed to access memory above 4GB, with the downside of possibly running slower because it uses larger numbers for the memory addresses.

**Comment by angelics** [comment]
rx580 8gb micron. claymore dual mining hashrate stays within benchmarked value after GPU_FORCE_64BIT_PTR 0. the rig was handed over to my friend.

**Comment by angelics** [comment]
this is just a temp fix. after switching to other miner, eg. claymore, the 64bit ptr is stil 0. this custom variable originally was meant to run custom OC profiles using `".\profile\"+$_.Algorithm+"_"+$_.Type+".bat"`

**Comment by angelics** [comment]
re-tested with amd rig. closing this for new PR

**Pull request closed without merging**
