### PR TITLE
AHashPool: Fix divisors

### PR DESCRIPTION
**Pull request by UselessGuru**
https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1368

### CODE REVIEW

**Comment by aaronsace** [comment]
> we may also do this for other algos

**Comment by UselessGuru** [comment]
> we may also do this for other algos

Done. Waiting for the pool to change, then we can commit

**Comment by grantemsley** [comment]
@UselessGuru Is this PR still relevant?

**Comment by UselessGuru** [comment]
Pool has not yet updated its divisors. Will reopen if needed

**Pull request closed without merging**
