### PR TITLE
Logging with timestamps and error levels

### PR DESCRIPTION
**Pull request by grantemsley**
image 4

This adds a new function Write-Log, which displays messages with a timestamp and error level, and also writes them to a file which is rotated each day.  Write-Log is used instead of Write-Error, Write-Warning, and Write-Verbose.

The lack of timestamps in the existing transcript log was frustrating me.  Sometimes it's important to know exactly when things started going wrong.  This makes logs that are much easier to read.  It also makes issues easier to find, just searching the log file for "WARNING" or "ERROR".

I still left the transcript version logs in, because they will still contain any other uncaught errors.

### CODE REVIEW

**Comment by grantemsley** [comment]
Rebased to fix conflicts.

**Comment by grantemsley** [comment]
Rebased again to fix latest conflicts.

@aaronsace Anything holding this back from being merged?  I'm happy to make any changes you might need.

**Comment by UselessGuru** [comment]
I see no problem with it.

**Comment by aaronsace** [comment]
Please output using the corresponding commands instead of 'Write-Host': 
```
Write-Debug
Write-Error
Write-Host
Write-Information
Write-Output
Write-Verbose
Write-Warning
```

**Comment by grantemsley** [comment]
I did think of using those, but they you can't control the formatting of them at all - can't have the timestamps at the beginning, can't set the color, and can't get rid of the CategoryInfo and FullyQualifiedErrorId for Write-Error.  And you have to set $InformationPreferences, $VerbosePreference, etc.

I can make the change, but it doesn't come out as nice looking IMHO.

**Comment by aaronsace** [comment]
Yeah but I'm not really interested in changing any colours; just add the timestamps on the lines in the log file. 

Then any custom colours that are needed can be added ad-hoc because this works: 
`"test" | Write-Output | Write-Host -BackgroundColor Yellow -ForegroundColor Black`

The standard variables can then be used to control the level of detail shown on the screen: 
`$[Name of Stream]Preference = Continue/SilentlyContinue`

**Comment by grantemsley** [comment]
Even if you don't care about color, my issue is instead of getting them formatted in nice columns where the the date is in the same place on each line, you get something this:

```
2017-12-31 22:55:37 Loading pool information...
WARNING: 2017-12-31 20:43:02 Pool API (HashRefinery) returned nothing.
Write-Log : 2017-12-31 22:59:58 Test
At line:1 char:1
+ Write-Log -Level Error "Test"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log
```
Info stream doesn't prepend INFO like warning does, and error does it's own unique thing.

Instead of:
```
2017-12-31 23:00:40 INFO: Loading Pool Information...
2017-12-31 23:00:41 WARNING: Pool API (HashRefinery) returned nothing.
2017-12-31 23:00:43 ERROR: Test
```
The latter is a lot easier to read when you are skimming through the logs.

If your main objection is that you can't control how verbose it is, I can keep the nice formatting but still honor the $[stream]preference settings.  And change it to have levels info/verbose/warn/error to match the usual streams, but still keep the nicer formatting.

Up to you.

**Comment by UselessGuru** [comment]
I like the colored output. :-)
We should make it configurable (switch to turn it off)
In that context I do also like a switch to set log levels (off, normal, info, warnings, error, debug). 

@aaronsace: What is your exact motivation for 
```
Write-Debug
Write-Error
Write-Host
Write-Information
Write-Output
Write-Verbose
Write-Warning
```
Just trying to understand ;-)

**Comment by UselessGuru** [comment]
@grantemsley 

I think there is a problem with the lines calling 'Write-Log' without specifying the 'Level parameter:

In transcript i got these:
>> TerminatingError(): "Cannot find an overload for "log" and the argument count: "2"."
>> TerminatingError(ForEach-Object): "Cannot find an overload for "log" and the argument count: "2"."

I fixed it by always adding '-Level' to each log command

**Comment by grantemsley** [comment]
```[Parameter(Mandatory=$false)][ValidateSet("Error","Warn","Info","Debug")][string]$Level = "Info"```

Level defaults to info if not specified.

```Write-Log "test"```
works perfectly for me.  Not sure what you're doing differently.

**Comment by grantemsley** [comment]
Latest commit makes it use the built in $DebugPreference, $VerbosePreference, $WarningPreference and $ErrorPreference varibles for controlling how detailed the logging is.

**Comment by grantemsley** [comment]
Per chat with @aaronsace, changed to use write-error, write-verbose, etc.

**Comment by Braintelligence** [comment]
@grantemsley Hi there, do I need to set something specifically, so I can see this new logging? I'm not sure I've seen it yet while using the current MPM. Or is this not in a release yet?

**Pull request merged**
