### PR TITLE
Move config.txt to config.example.txt

### PR DESCRIPTION
**Pull request by grantemsley**
Renames config.txt to config.example.txt so that it isn't tracked in git.  If config.txt is missing when the script is first launched, it will be copied over from the example file automatically.

This removes one of the places where command line parameters needed to be updated, and make's sure people's customized config.txt never gets accidentally overwritten or cause merge conflicts.

### CODE REVIEW

**Comment by UselessGuru** [comment]
Better even make MPM create the default file itself. I am working on this.

**Comment by grantemsley** [comment]
@aaronsace Changed as requested.

**Comment by grantemsley** [comment]
@UselessGuru I thought about that - downside is you have to run it at least once before you can edit the config file.  Makes it a little harder for people who are just getting started.

**Comment by grantemsley** [comment]
@aaronsace Ok. Should we change this error message a bit below that too then?

`    #Error in Config.txt
    if ($Config -isnot [PSCustomObject]) {
        Write-Log -Level Error "*********************************************************** "
        Write-Log -Level Error "Critical error: Config.txt is invalid. MPM cannot continue. "
        Write-Log -Level Error "*********************************************************** "
        Start-Sleep 10
        Exit
    }
`

**Comment by grantemsley** [comment]
@aaronsace I went ahead and changed the other error message too.  Let me know if you want me to change it back.

**Comment by aaronsace** [comment]
Yes, and remove the asterisks.

**Pull request merged**
