### PR TITLE
Ethash2g ClaymoreAMD tries mining ETH for DevFee.

### PR DESCRIPTION
**Pull request by bbluemel**
Just need changing -allcoins from 1 to exp.

### CODE REVIEW

**Comment by aaronsace** [comment]
Can you explain this a bit more?

**Comment by bbluemel** [comment]
Hi @aaronsace 
From the Claymore Dual Eth+Dec Readme:

> - I mine ETH fork on my 2GB cards. For devfee miner tries to mine ETH and it fails because ETH cannot be mined on 2GB cards.
> - Use "-allcoins exp -allpools 1" options.

So e.g. if Ethash2g is mining MusicCoin (which it does a fair bit at the moment) - when it tries to do the DevFee, it notices it cannot mine to there, so switches to an ETH pool to mine ETH for the DevFee.  This fails as it cannot allocate the DAG on a 2Gb card.  The miner then quits (and for me sometimes causes a lockup!)
Using that option, the DevFee mines Expanse (I believe) so the DAG can fit, and then won't error and quit.

**Comment by UselessGuru** [comment]
From the Claymore Dual Eth+Dec Readme:
_-allcoins Specify "-allcoins 1" to be able to mine Ethereum forks, in this mode miner will use some default pools for devfee Ethereum mining. 
   Note that if devfee mining pools will stop, entire mining will be stopped too. 
   Miner has to use two DAGs in this mode - one for Ethereum and one for Ethereum fork, it can cause crashes because DAGs have different sizes. 
   Therefore for this mode it is recommended to specify current Ethereum epoch (or a bit larger value), 
   for example, "-allcoins 47" means that miner will expect DAG size for epoch #47 and will allocate appropriate GPU buffer at starting, instead of reallocating bigger GPU buffer (may crash) when it starts devfee mining.
   Another option is to specify "-allcoins -1", in this mode miner will start devfee round immediately after start and therefore will get current epoch for Ethereum, after that it will be able to mine Ethereum fork.
   If you mine Expanse, the best way is to specify "-allcoins exp", in this mode devfee mining will be on Expanse too and DAG won't be recreated at all.
   If you mine ETC on some pool that does not accept wallet address but requires Username.Worker instead, the best way is to specify "-allcoins etc", in this mode devfee mining will be on ETC pools and DAG won't be recreated at all._

I don't really understand it... ;-(

But:
In ETH only mode the miner is defined as '-allcoins **1**'
In Dual Algo Mode it is '-allcoins **exp**'

Why the difference? If @bbluemel's change helps and does not have any side effects (what is to be tested) then I think we should configure both modes identical using '-allcoins **exp**'.

**Comment by bbluemel** [comment]
@UselessGuru yeah that part seems rather complicated, but I have been using -allcoins exp when I've been running the miners myself, and it's solved the issue.  Although it waste about 20s switching between them.

It does work though, here's a recent DevFee session on mine, you can see it switches to the MPH expanse port for the devfee, and then back to musicoin for the normal mining.

image

It probably needs doing for NVidia cards too, though I don't have an NV 2Gb card that this would be an issue on.

**Comment by aaronsace** [comment]
How about just removing AllPools? Isn't MiningPoolHub compatible with dev mining now?

**Comment by aaronsace** [comment]
"-allcoins exp" should work fine though as I believe Claymore takes the switching/DAG hit anyway...

**Comment by bbluemel** [comment]
Hi @aaronsace 
Removing allpools and allcoins gives the following:
image

And with allpools removed and "-allcoins -1" to force devfee straight away gives the following:
image

Seems like "-allcoins exp" is the only fix here.

Thanks

Ben

**Pull request merged**
