### PR TITLE
Setup GUI, take 2

### PR DESCRIPTION
**Pull request by grantemsley**
A new improved version of my setup GUI, rewritten to work with the new config.txt system.

One of my main goals was to make it so we don't have to edit start.bat anymore.  Having all settings stored in config.txt means no more need to edit the command line parameters.  This will hopefully make it easier for users to upgrade.  It's also very important for the GUI I've written - it needs to launch MultiPoolMiner.ps1 directly, which is easier and more user friendly if it doesn't require any parameters.

# Features

- Generate a miner status key right in the GUI
- Dynamically loads pools and their available settings, so new ones can be easily added
  - Pools have a ```-info``` switch added
  - When the info switch is set, instead of the normal output they return information about the pool and a list of settings they accept
- Dynamically generates the lists of algorithms and miners
- One click to choose only the algorithms your primary pools support - so you can add backup pools without worrying about them taking priority over your preferred ones
- Keeps any additional settings you've added if you manually edit config.txt - so it won't overwrite any new settings the GUI doesn't support yet
- Checks that your configuration is valid

# Todo - things I could use help with

- [x] Adding -info output for the rest of the pools
- [ ] Make sure the correct altcoin payment address parameters are being added. I don't use any of them, so I'm not entirely sure if I've done it correctly
- [x] Issue: Unknown 'Custom' field when adding a new pool
- [ ] Testing

# Screenshots
seutp1
setup2
setup3
setup4
setup5
setup6
setup7

### CODE REVIEW

**Comment by UselessGuru** [comment]
Looks good! I cannot do testing on alt coins. Don't use'em myself.
Updated -info on:
- NiceHash
- Blockmunch

Added AltMiner.nt & ZergPool (incl. -info).

I think there is no point in doing any work on ItalYiiMP - looks dodgy and is offline again.

Suggestion: make miner url a hyperlink.

**Comment by grantemsley** [comment]
Thanks @UselessGuru 

Couple things you missed though:
- Altminer is using blockmunch's URL for the first request
- Nicehash website is missing the .com
- ZergPool is using wrong URL for first request

I can see if I can find a way to make the URLs clickable.  WPF requires a code behind for each link to make them clickable but I think I remember seeing a trick somewhere to do them dynamically.

**Comment by UselessGuru** [comment]
@grantemsley 

Thanks 🥇 you've got hawks eyes - github is playing tricks with me again

I cannot test ZergPool since it is currently down
_(We are on maintenance after hack and following DDoS attack. ETA 18:00 CET 08.02.2018. Working to get all restored)_.

**Comment by grantemsley** [comment]
@UselessGuru also did your IDE automatically change a bunch of formatting, or did you go through and do that?

**Comment by UselessGuru** [comment]
No, I did that to match MPMs indents (you should see a comment regarding this on the commit)

**Comment by grantemsley** [comment]
Ah missed that.  Thanks for cleaning it up!

**Comment by korishan** [comment]
I'd like to look at a running copy of this. Am I blind, or is it not ready for general release? I can't seem to find it.

**Comment by grantemsley** [comment]
You'll need to use git to pull this particular branch to test it.

**Comment by korishan** [comment]
ok, thnx.  I see the pull requests, but I don't see your name listed.  Ohwell. I can wait. I'm still new to the git world.

**Comment by grantemsley** [comment]
Probably because it's on my fork until it gets merged. If you checkout my branch you can test it out:

```
git clone https://github.com/grantemsley/MultiPoolMiner.git
cd MultiPoolMiner
git checkout configtxtsetupgui
```

**Comment by korishan** [comment]
Ahhh.  that would make a difference.  I'm on windows, not linux. I know I have git available on here thru Visual Studio, but I don't know how to use it.
Appreciate the info, none-the-less :)

**Comment by grantemsley** [comment]
@korishan If you don't know how to use git, you can download it directly at https://github.com/grantemsley/MultiPoolMiner/archive/configtxtsetupgui.zip to test it out.

**Comment by korishan** [comment]
Much obliged!  :D

**Comment by korishan** [comment]
After running your setup, does it MPM ignore the wallet and other settings inside the Start.bat file?

**Comment by grantemsley** [comment]
Yes.  That's the goal.

**Comment by UselessGuru** [comment]
**Issue: Unknown 'Custom' field when adding a new pool**

When adding/configuring a new pool for the first time an unknown 'custom' field is displayed:
newpool_customfield

Once saved and setup restarted it is gone:
newpool_customfieldgone

**Comment by grantemsley** [comment]
@UselessGuru I'm assuming that before you opened the setup, there was no entry for blazepool at all in config.txt?  I'll fix it.

**Comment by UselessGuru** [comment]
> I'm assuming that before you opened the setup, there was no entry for blazepool at all in config.txt? I'll fix it.

Correct.

**Comment by UselessGuru** [comment]
@grantemsley 

I like the 'Info' stuff with all the pools and am looking for a similar thing to configure miners. 

A lot of users have manually finetuned their miner files, e.g intensity for each algo. We should keep these settings on updates, e.g. Ccminer 2.3 -> Ccminer 2.4

Another use case: Right now I am working on the ClaymoreDual miner. Depending on hardware very different values for -dcri (intensity for dual mining) are required.
Instead of asking the user to manually edit the miner file I would like to store the miner settings in separate config file (also see [this pull](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1221)).
The GUI could present a dialog where they can set their custom dcri values, e.g with two sliders.

Now I am looking for an elegant solution that something like this:

- When MPM detects a new miner (new = no existing default config) is found it will force an initial setup (your GUI)
- It should read the default values from the miner (call for Info).
- Present the config values to the user so the user can edit them.
  Possible config values could be: 
  - all list of all supported algorithms, there should be a way of disabling it
  - options for each supported algorithm
  - some general options
- When done the setting should either be written to 'Configs\config.txt', or preferrably even to a separate miner config file 'Configs\[MinerName.txt]'

What do you think?

See attached miner file for possible 'Info' values (totally untestet nonworking sample).
[ClaymoreNvidia.ps1.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/1721104/ClaymoreNvidia.ps1.txt)

**Comment by grantemsley** [comment]
@UselessGuru I definitely want to expand it to configuring miner parameters.  I've got some hacks in my own branch to pass the number of threads to each of the CPU miners, which changes for each system.  So there is definitely a need for it.

I'd say leave it all in config.txt - it's already setup to handle passing parameters to the miners.  The only issue is there's no easy way for non-programmers to discover what the valid options are.  We can always add a way to copy just one miner's settings from one file to another if needed.

I don't like the idea of using the -info switch for the miners though.  It works well for pools because they are all ps1 scripts already.  But the vast majority of the miners are JSON, and I think converting them all to scripts would be inefficient and a step backwards.  I'm not entirely sure, but from what I've seen, one of the project's goals/styles is to use JSON where ever possible, and resort to scripts only for the parts where it's necessary.

I can dynamically add parameters for the miners the same way they are added in the pools.  So the only real problem is how to discover what the valid parameters are.

I was thinking having an optional '''<minername>.parameters''' file, containing JSON describing the available options.  Make Get-ChildItemContent ignore those files, and let the setup program read them.  Unlike the pools, they wouldn't need to be dynamically generated from API calls, so a static JSON file should be fine.

**Comment by UselessGuru** [comment]
> But the vast majority of the miners are JSON, and I think converting them all to scripts would be inefficient and a step backwards. I'm not entirely sure, but from what I've seen, one of the project's goals/styles is to use JSON where ever possible

Most multi-algo miners are already /still (???) in ps1.

At first JSON seem easy, but it so limited in what you can do. 

A few examples of things I cannot imagine with JSON:
- a simplified and easily configurable miner for ClaymoreDual (updating 20 JSON files is much more of a hassle than 1 PS1 file - errors are much more likely)
- Iterating inside a miner to launch a separate miner instance per GPU device class (as I have implemented in my build)
- Reading miner options from the miner file (e.g. supported algos)

> Unlike the pools, they wouldn't need to be dynamically generated from API calls, so a static JSON file should be fine.

There are so many different miners with different options in different places, I don't see we can do this efficiently with JSON.

If it was my project I would convert them all to ps1. To me I cannot really see the benefit of JSON.

**Comment by grantemsley** [comment]
@aaronsace is there anything you would like to see done differently before considering merging this?

**Comment by aaronsace** [comment]
Sorry, I'll be visiting this in a couple of weeks.

**Comment by UselessGuru** [comment]
@grantemsley 

Small changes required with Setup GUI 
- The dialog should be either fixed or resize properly
- Add support for large comments as in [Zergpool.zip] (as an example) (https://github.com/MultiPoolMiner/MultiPoolMiner/files/1739194/Zergpool.zip)

zergpool_largecomment

**Comment by grantemsley** [comment]
@UselessGuru Put your really long description of the pool in the Description property, not Note.  Note is intended to just be a couple words.  Description can be as long as you want.  Only thing it doesn't do is word wrap, which I think I can fix.

image

**Comment by grantemsley** [comment]
Text should wrap nicely now.

Seeing if I can make the content resize better if you resize the window.  Right now if you resize it, the content will get bigger and keep the same aspect ratio, so there are large margins on the sides.  I could just lock the window size, but if I can I'd rather make it resizable just in case someone's trying to run it on a really high DPI screen.

**Comment by UselessGuru** [comment]
Text wrap looks good.
Implementing proper resize is a lot of work. My opinion: Either implement full working resize or or lock it.

**Comment by netrion** [comment]
where can i download the gui? or is it long time left to its finished looks great

**Comment by UselessGuru** [comment]
@netrion 

https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1187/files

You will have to update all the relevant files manually. Currently there is not all-you-can-eat version of the latest MPM code PLUS gui.

**Comment by grantemsley** [comment]
Anyone good enough with git to know how to fix that Config.txt conflicting files warning?

**Comment by Falacio** [comment]
Hi. A totally newbie here (also non english speaker)
I've been using MPM for a couple of days, and wanted to test you setup. Congrats, it looks promising.
Setup runs fine and creates a config.txt
I've tried to lauch then with any start.bat (as I've read before that config file should override any input parameters) and I'm getting some issues:
In first place, there is a '}' symbol in line 702 of MultiPoolMiner.ps1 that gives an error. I had to delete it, but maybe there is a '{' missing somewhere... I've checked and I have updated all files I found here (with MPM too).
Deleting it allows me to run start.bat, but then the program is not able to continue. Only piece of useful info I found in logs:

> INFO: Updating exchange rates from Coinbase...
> INFO: Loading saved statistics...
> INFO: Loading pool information...
> WARNING: Pool API (Zpool) returned nothing.
> INFO: Selecting best pool for each algorithm...
> INFO: Updating exchange rates from Coinbase...
> INFO: Loading saved statistics...
> INFO: Loading pool information...
>  PS>TerminatingError(Invoke-RestMethod): "              www.zpool.ca | 502: Bad gatewaybody{margin:0;padding:0}Error502Ray ID: 3fb63399c9c861db &bull; 2018-03-14 10:54:19 UTCBad gatewayYouBrowserWorkingBarcelonaCloudflareWorkingwww.zpool.caHostErrorWhat happened?The web server reported a bad gateway error.What can I do?Please try again in a few minutes.Cloudflare Ray ID: 3fb63399c9c861db&bull;Your IP: 95.20.128.XXX&bull;Performance &amp; security by Cloudflare"
> WARNING: Pool API (Zpool) has failed.
> INFO: Selecting best pool for each algorithm...

And more or less the same again and again.

I've tried to run as standalone and overwriting a fresh version on MPM. And I cannot past beyond that point. And no idea what I'm doing bad. Or maybe is not fully implemented yet?

Sorry for bothering and thank you all for your work

**Comment by grantemsley** [comment]
@UselessGuru If you are using my setup gui, it should override EVERYTHING in start.bat, so you can use any start.bat file or just run multipoolminer.ps1 directly if you want.

**Comment by Falacio** [comment]
@grantemsley @UselessGuru  Thanks for answering. As I've explained, I've tried with several start.bat, as grantemsley said, it shoud work with any of them, but it didn't. Still nobody has said a word about that four lines error message... I haven't tried again since then, now I'm trying to make that ZergPoolCoins work as intended with particular coins.
I'll go back to setup with other aproach and will tell you the results.

**Comment by grantemsley** [comment]
@falacio it's probably because some of the files for this haven't been updated yet.

Try this:  Use this version to generate the config.txt, then copy that config.txt to a different directory with the release version.

**Comment by Falacio** [comment]
Well that one worked pretty well... The config.txt really took over .bat parameters. I'm only having little probles with some pools, maybe for that conflicting files showing above. Thanks a lot.

**Comment by grantemsley** [comment]
@aaronsace Have you had a chance to look at this?  I'd like to incorporate any feedback you have and update it for the new pool files.

**Comment by grantemsley** [comment]
I will revisit this in a new PR

**Pull request closed without merging**
