### PR TITLE
Patch for Issue #1349

### PR DESCRIPTION
**Pull request by boro2000**
Bugfix for "Pools out of Sync" problems when using NiceHash alone and together with another Pool

### CODE REVIEW

**Comment by UselessGuru** [comment]
@boro2000 

If the 0 price is the cause (frankly I don't know right now) then your approach goes into the right direction, but then we must consider a solution which applies to all pools.

**Comment by boro2000** [comment]
@UselessGuru 
Yes, every pool should be checked, if it has this problem.
NiceHash differs from the other pools, in this case: a currencies price can suddenly drop to zero. This is not the case for the other mining pools, as far as I could find out.

**Comment by UselessGuru** [comment]
> a currencies price can suddenly drop to zero

Nicehash differs because the pool file does not take historical data into account:

Most pools go a get-stat -> set-stat to use old data.
NH just does a set-stat (no get-stat first) which can cause sudden drops to 0.

Still I believe the solution should be dealt with in the main routine, and not in the miner definition file.

**Comment by boro2000** [comment]
@UselessGuru
Exactly :)
I changed the miner definition file, because it is a NiceHash speciality and, most conveniently, at the beginning, of the processing chain. If any currency would drop to zero at NiceHash - it is removed from any further processing, until NiceHash delivers a price greater than zero.
Of course this can be handled within the mpm core routine, too.

**Comment by aaronsace** [comment]
@UselessGuru It may be better to add a zero check in the main code but I've approved and leave it up to you.

**Comment by borzaka** [comment]
Please, have a look at my [comment](https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1349#issuecomment-369656068) regarding this issue;
> Pool prices are out of sync when they are not included in the Start.bat

**Comment by kiLLeen** [comment]
@borzaka that is due to #1325 , which I have already reported and narrowed down the repro steps and the underlying issue.

**Pull request merged**
