### PR TITLE
MultiPoolMiner.ps1: Add DonationRun info to log

### PR DESCRIPTION
**Pull request by UselessGuru**
Write donation run info to log (https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1292, https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1286, https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1309)

### CODE REVIEW

**Comment by UselessGuru** [comment]
> I don't see any need for the 'DonateRun' variable.

removed

> The log will be a good addition. Please can you add the time remaining to the log message.

done

**Comment by aaronsace** [comment]
What is the 59 seconds for...?

**Comment by UselessGuru** [comment]
What is the 59 seconds for...?

See comment of
https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1363/commits/95e3f2b84a3b77ec7efa16170f8344fe94ff350f

**Comment by UselessGuru** [comment]
@aaronsace 

> I don't see any need for the 'DonateRun' variable.

For better readability and to avoid mis-configuration it should be added.

Scenario:
Miners, e.g. ZergPoolCoins (coming) or MPHCoins should have a way to detect donation run. This allows to maximize donation profit by enabling all possible algo/coins combos (normal runs may be limited to mining coins that may not desirable for donation, e.g. https://github.com/MultiPoolMiner/MultiPoolMiner/issues/1413). 

We can detect donation run if $BTC/$User variable is (non-)present, but this defies their purpose:
- For MPHCoins: To detect donation I check the presence of $BTC, which is not present in normal runs
- For other pools $User might serve the same purpose

Possible config issues and mis-operation
It is quite possible that someone adds $User parameter to a pool that requires $Wallet, but NOT $User (and vice versa). This will cause the pools to switch to donation mode 100% of the time :-(

Having a properly named variable makes code easier to understand. But more so it helps avoiding mis-configuration errors and will result in less issues.

**Comment by aaronsace** [comment]
@UselessGuru I'm quite sure all that has been addressed and fixed; check the logic on the latest code. Config files can be dynamically changed in realtime. I don't want donation code in the pool files which also means there is no need for a variable because nothing would use it.

**Comment by UselessGuru** [comment]
> I don't want donation code in the pool files which also means there is no need for a variable because nothing would use it.

There is already donation code in this code. The `-or $BTC` makes sure we get proper donation:

`$MiningPoolHubCoins_Request.return | Where-Object {($Coins.count -eq 0 -or $Coins -icontains $_.coin_name -or $BTC) -and $_.pool_hash -gt 0} | ForEach-Object {`

Do you want to take it out? Without donation run detection there is 100% loss in donation if no backup pools are configured.

**Pull request closed without merging**
