### PR TITLE
Fix 'no username or wallet', merger PRs, add balances for all currencies

### PR DESCRIPTION
**Pull request by paulpoco**
Fixes https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2149

The challenge in Fix 'no username or wallet'

I enables fully dynamic config via config file (=saving a new config file while MPM is running).
The old code had issues with that.
What is implemented in this code:

Assume the following:

config file contains $Variables, e.g. $Config.Wallet = "$Wallet", not hard coded values

MPM starts -> fills all $Variables with either values from command line OR defaults, e.g. $Wallet = "ABC"
MPM fills $Config_Parameters with $Variable-Values
MPM (in Get-ChildItemContent) replaces all $Config.'$Variable' with static $Variable value, e.g $Config.Wallet = "ABC"

While MP is running someone is changing $Config.Wallet = "XYZ" (hard coding the value in the file)

Without my code:

MPM will reload config.
Note: $Wallet is still "ABC"
MPM fills $Config_Parameters, Wallet will be "ABC" again!
MPM (in Get-ChildItemContent) replaces all $Config.'$Variable' with $Variable-Value , $Config.Wallet = "ABC" again!

with my code:
MPM will reload config.
Note: $Wallet is still "ABC" -> it is important to use the actual value from $Config.Wallet
Fill $Config_Parameters, only use $Variable-Value where there is no real value in running config, Wallet will remain "XYZ" (read from $ConfigBackup.Wallet)
MPM (in Get-ChildItemContent) replaces all $Config.'$Variable' with $Variable-Value , $Config.Wallet = "XYZ"

### CODE REVIEW

**Comment by grant** [comment]
@UselessGuru, you probably meant @grantemsley.

**Comment by paulpoco** [comment]
I am trying this.  Has ShowPoolBalancesDetails changed?
image

**Comment by paulpoco** [comment]
@UselessGuru @grantemsley can #2110 merged into this one?

Having changes in MultiPoolMiner.ps1 and Include.psm1 in different PRs is hard to track.

**Comment by UselessGuru** [comment]
Merged

**Comment by UselessGuru** [comment]
@paulpoco 

> I am trying this. Has ShowPoolBalancesDetails changed? It is not there anymore.

This was in a different branch. I've added it to this PR now.
https://github.com/MultiPoolMiner/MultiPoolMiner/tree/UselessGuru_PoolBalancesMultiCurrrency

When we commit this PR then all changes to core are done. 
Then only miner updates are pending which will make keeping up to date much easier.

**Pull request merged**
