### PR TITLE
Adding more AMD miners

### PR DESCRIPTION
**Pull request by symalla**
This is Dependant on "Extend Interval for selected Miners and Algorithms [#1682](https://github.com/MultiPoolMiner/MultiPoolMiner/pull/1682)"

After applying the extend interval and adding this minders to ExtendIntervalMinerName I was able to get these to benchmark on my system.

`
 "ExtendIntervalMinerName": [
    "PalginNvidia",
	"aeris",
	"avermore",
	"SgminerPhi-5613",
	"SgminerBitcore-10",
	"Gatelessgate-0136",
	"SgminerKL-101",
	"SgminerLyra2z-djm3403",
	"SgminerLyra2z",
	"Sgminer",
	"SgminerSkein",
	"SgminerXevan"
  ]
`

### CODE REVIEW

**Comment by thinkplaystudios** [comment]
Thanks for this!  Just to point out, SigminerPhi-5613.ps1 was misspelled.

**Comment by angelics** [comment]
did u actually tested using master MPM? i can see most miners were from my personal repo... did u set 64 ptr to 0?

**Comment by symalla** [comment]
@angelics Yes this is running on MPM master with the Extend interval patch applied. 

I didn't change 64 ptr to 0 and was able to successfully benchmark these

**Comment by UselessGuru** [comment]
Forgot to mention:
- Also do NOT include version numbers in binary path, e.g .\Bin\AMD-Aeris**-02**\sgminer.exe
- $URI cannot be a mega link - these are not downloadable. If the miner will be included we (the devs) will  have to upload the binaries to the repository and change the URI.

**Comment by angelics** [comment]
it shud nt run. for bitcore-10,kl-101 and phi5613. as far as i tested these miners crashed with PTR 1, outside MPM. it had nth to do with extended interval. refer #1414

**Comment by symalla** [comment]
@angelics I have just pulled a brand new Master running with PTR1, will take a while to bench with the 10min intervals, but so far Bitcore10 completed successfully.

@grantemsley what is needed for the devs to choose to include a miner with only a megalink download available. I can remove Aris from this pull since it still it is megalink and Beta, but it is nice to add the x16* for the AMD cards.

**Comment by grantemsley** [comment]
@symalla For any miner that only has megalink or other non-automatic downloads, I'll rehost it in our binaries repository at https://github.com/MultiPoolMiner/miner-binaries/ and change the URI before we add it.  Not a problem.

**Comment by symalla** [comment]
Okay after the re-benchmarking with current master and PTR 1 @angelics  was correct majority didn't work for me this time.  Of the ones that work only Sgminer-Bitcore-10 was more profitable then current available. 

2018-05-14 18_59_27-192 168 1 33 - remote desktop connection

I am not sure how to delete the other from this commit so I will mark as closed and open a new pull for just the one.

**Pull request closed without merging**
