### PR TITLE
Add balance for Blockmasters.co

### PR DESCRIPTION
**Pull request by UselessGuru**

### CODE REVIEW

**Comment by grantemsley** [comment]
blockmasters is one of the pools that pays out in the currency you mined, isn't it?  So just asking for a balance from your BTC balance would only show actual bitcoin you mined (and you aren't mining bitcoin with MPM), wouldn't it?

**Comment by UselessGuru** [comment]
> So just asking for a balance from your BTC balance would only show actual bitcoin you mined

Good point. Yes - I never mined anything else.

**Comment by grantemsley** [comment]
I only mine BTC myself, which is why I only use the pools that support automatic exchange and mine only to a BTC address.

If someone who mines and gets paid out in altcoins wants to share their configuration (with their addresses, so I can check their balances), we can work on adding pools that don't pay in BTC.  That's why the balance objects keep the currency field already, because I expected it would eventually be showing other coins there.  I just have no way to test it myself without getting the data from someone who does get paid in other coins.

And unless those pools return exchange rate information, we'll have to look that up ourselves, which also gets tricky because (AFAIK) there is no single exchange that we can get exchange rates for all possible coins from.

**Comment by grantemsley** [comment]
Going to close this for now. I do want to revisit getting the balances of directly mined altcoins from pools other than miningpoolhub at some point though.

**Pull request closed without merging**
