### PR TITLE
Use status key instead of BTC address

### PR DESCRIPTION
**Pull request by grantemsley**
Adds a miner status key to the new config.txt file.  Removes the requirement for having a bitcoin address from the website.

Website has also been modified to generate these status keys for new users.

You can still use your bitcoin address as your status key if you prefer, so existing users can keep using their address as the status key without changing anything.

### CODE REVIEW

**Comment by fonyo** [comment]
I see the data only gets passed to ReportStatus.ps1 if both MinerStatusURL and MinerStatusKey are present. It would be convenient for the current 250+ workers to set up an OR scenario so existing users can carry on BAU and MPH users and future users can use either. Please? My intentions are coming from a public relations perspective. Reddit is mad as is.

**Comment by grantemsley** [comment]
@fonyo good point.

Two ways I can see to fix that:

1.  Check if either -MinerStatusKey or -Wallet is set.  If MinerStatusKey is set, use that, otherwise use the -wallet value.  So existing users can keep using as is.

2.  Not add another switch at all to the .bat files, and set MinerStatusKey to $Wallet in config.txt.  Those who want to use something other than the wallet address edit config.txt

Which would be preferable?

**Comment by fonyo** [comment]
The first option is preferable as we retain old functionality while adding a new feature (option) for users without a btc address.

**Comment by grantemsley** [comment]
@fonyo well, both options do that actually.  The difference is just in how you specify a non-bitcoin address.

**Comment by fonyo** [comment]
The first one sounds more-straightforward and logical to me given we are only just about to introduce the new config.txt system. The less user-interaction, the better.

**Comment by grantemsley** [comment]
Ok, modified it a bit for backwards compatibility.

If you want to use something other than -wallet, you can specify -MinerStatusKey or edit it in config.txt and it will use that.  Otherwise it will use what you have in -wallet.

If neither MinerStatusKey nor Wallet is specified, it won't do any reporting.

Also added a line in the output showing what your status key is.  Hopefully that makes it a little clearer for people.

**Comment by fonyo** [comment]
Brilliant.

**Pull request merged**
