### PR TITLE
New: AMD_NVIDIA-lolMiner version 0.5

### PR DESCRIPTION
**Pull request by UselessGuru**
https://bitcointalk.org/index.php?topic=4724735.0

Hi there, 
this is the announcement thread for lolMiner 0.5, a multi algorithm Equihash miner with focus on AMD GPUs (OpenCL based).
Note it will run on most Nvidia GPUs, too but the speed and stability may vary. Hope to improve this in the future.

Currently with this miner you can mine 4 different algorithms:
         Algorithm	   Req GPU Mem	   Coins that use it
Equihash96/5
500MB
Minex Coin (MNX)
Equihash144/5
3G
E.g. ANON, BTG, BTCZ,XSG, ZEL and many more!  
Equihash192/7
4G
Zero (ZER), Genesis (GENX) & Zero Classic
Equihash210/9
1G
Aion Mainnet

Download:

From Dropbox:
[Lin 64] Click me (0.5 Linux) 
[Win 64] Click me (0.5 Windows) 
(More Mirrors to come)

Usage:

The first way to use the miner is from command line interface. The syntax is

Code:
Linux: ./lolMiner --coin <shortCut> --pool <poolAddr> --port <portNumber> --user <Wallet or user name> --pass <userPassword>
Windows: lolMiner.exe --coin <shortCut> --pool <poolAddr> --port <portNumber> --user <Wallet or user name> --pass <userPassword>

Here the <shortCut> parameter is a short name for the coin you want to mine. For example inserting AION will configure the miner to mine AION, MNX for MinexCoin and so on.
For more shortcuts and more options please read the lolMiner_manual.pdf shipped with the miner. 
lolMiner 0.5 supports fail-over pools, configuration files (easy sharing between Rigs and easy switching between coins), automatic worker names, a simple statistics reading API, logging to text file and many more features. 

Estimated Performance: 

Most of this measurements were reported by community members in this thread. Results may vary a bit depending on clocks, driver version and operation systems:

GPU              	
   Equi 96/5
   Equi 210/9
   Equi 144/5
   Equi 192/7
Vega64	
~24.000 sol/s
~155.0 sol/s
  ~37 sol/s
~22.5 sol/s
580      	
~13.800 sol/s
~107.5 sol/s
  ~25 sol/s
~15.5 sol/s
560      	
  ~6.900 sol/s
    ~54 sol/s
~12.5 sol/s
 ~7.5 sol/s
(More data to come when available)

Known issues and troubleshooting: 

Problem: The miner crashed at startup when creating memory buffers or miner ends up with 0 sol/s from start.
Solution: The AMD driver requires on start as many MB of system memory as it will need on all started GPUs together. Increase the fixed page file size (Windows) or swap partition size (Linux) to give the rig more virtual memory.

Problem: The miner gets unstable or slow when using more then 4-5 GPUs
Solution: Start two instances and use the --devices parameter (command line) or "DEVICES" (config file) to point one instance to the first n GPUs and the second to the next. For most systems that will work better.

### CODE REVIEW

**Comment by Dewbs** [comment]
All benchmark '0' - 

example command output:

2018-09-04 20:25:11 INFO: Starting miner (lolMiner-GPU#02): 'C:\MPM\Bin\AMD_NVIDIA-lolMiner\lolminer.exe {"ConfigFile":{"FileName":"lolMiner-GPU#02-ZergPool-Equihash965.txt","Content":{"DEFAULT":"@{APIPORT=4002; COIN=MNX; DEVICES=System.Object[]; POOLS=System.Object[]; SHORTSTATS=10}"}},"Commands":"-usercfg=lolMiner-GPU#02-ZergPool-Equihash965.txt -profile=DEFAULT"}'

typical log output:

-------------------------------------------------
             Welcome to lolMiner 0.43            

   This software is only meant for pool mining   
with the Equihash 96.5, 144.5 or 192.7 algorithm 

         Made by Lolliedieb, August 2018         
-------------------------------------------------
Warning: No user configuration file found. You can define it by -userCFG=<filename> 
Warning: No user configuration file defined in command line or file not found.
Using only command line settings.
Error: user profile "command line" does not contain connection data, section POOLS is missing

**Comment by UselessGuru** [comment]
@Dewbs 

Very odd... 
What does MultiPoolMiner.ps1 line 422 ()or around there look like?

`        if ($Miner.Arguments -isnot [String]) {$Miner.Arguments = $Miner.Arguments | ConvertTo-Json -Depth 10 -Compress}`

**-Depth 10** is crucial.

**Comment by Dewbs** [comment]
-Depth was missing
I have lost track which version I was using - probably from one of the pull requests
I have updated to latest master, will report back!

**Comment by Dewbs** [comment]
Trying to update my files but now am stuck with

Start-Sleep : Cannot validate argument on parameter 'Seconds'. The argument is null, empty, or an element of the argument collection contains a null value. Supply a collection that does not contain any null values and then try the command again.
At C:\MPM\MultiPoolMiner.ps1:583 char:17
+     Start-Sleep $Config.Delay #Wait to prevent BSOD
+                 ~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Start-Sleep], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.StartSleepCommand

**Comment by Dewbs** [comment]
A can of worms.
If I use the current master mpm.ps1 I get the above error - and in addition Zergpool fails (if I have only zergpool specified in my config I get 'no pools available'). n.b. using zergpool.ps1 from #2135

If I use your mpm,ps1 from #2112

https://github.com/MultiPoolMiner/MultiPoolMiner/files/2336117/MultiPoolMiner_ps1.txt

then zergpool works ok but this miner still fails (it has the -depth 10 you mention above).

-------------------------------------------------
             Welcome to lolMiner 0.43            

   This software is only meant for pool mining   
with the Equihash 96.5, 144.5 or 192.7 algorithm 

         Made by Lolliedieb, August 2018         
-------------------------------------------------
Warning: No user configuration file found. You can define it by -userCFG=<filename> 
Warning: No user configuration file defined in command line or file not found.
Using only command line settings.
Error: user profile "command line" does not contain connection data, section POOLS is missing


2018-09-04 22:58:25 INFO: Starting miner (lolMiner-GPU#02): 'C:\MPM\Bin\AMD_NVIDIA-lolMiner\lolminer.exe {"ConfigFile":{"FileName":"lolMiner-GPU#02-ZergPool-Equihash1445.txt","Content":{"DEFAULT":{"APIPORT":"4002","COIN":"AUTO144","DEVICES":["2"],"POOLS":[{"POOL":"equihash144.mine.zergpool.com","PORT":2146,"USER":"1GD1YxJWzne32MeDLfX5MLV6dGtT5uW4AN","PASS":"multipoolminer,c=BTC,mc=ZEL"}],"SHORTSTATS":10}}},"Commands":"-usercfg=lolMiner-GPU#02-ZergPool-Equihash1445.txt -profile=DEFAULT -disable_memcheck=1"}'
2018-09-04 22:58:25 INFO: Starting miner (lolMiner-GPU#01): 'C:\MPM\Bin\AMD_NVIDIA-lolMiner\lolminer.exe {"ConfigFile":{"FileName":"lolMiner-GPU#01-ZergPool-Equihash1445.txt","Content":{"DEFAULT":{"APIPORT":"4001","COIN":"AUTO144","DEVICES":["1"],"POOLS":[{"POOL":"equihash144.mine.zergpool.com","PORT":2146,"USER":"1GD1YxJWzne32MeDLfX5MLV6dGtT5uW4AN","PASS":"multipoolminer,c=BTC,mc=ZEL"}],"SHORTSTATS":10}}},"Commands":"-usercfg=lolMiner-GPU#01-ZergPool-Equihash1445.txt -profile=DEFAULT -disable_memcheck=1"}'
2018-09-04 22:58:25 INFO: Starting miner (lolMiner-GPU#00): 'C:\MPM\Bin\AMD_NVIDIA-lolMiner\lolminer.exe {"ConfigFile":{"FileName":"lolMiner-GPU#00-ZergPool-Equihash1445.txt","Content":{"DEFAULT":{"APIPORT":"4000","COIN":"AUTO144","DEVICES":["0"],"POOLS":[{"POOL":"equihash144.mine.zergpool.com","PORT":2146,"USER":"1GD1YxJWzne32MeDLfX5MLV6dGtT5uW4AN","PASS":"multipoolminer,c=BTC,mc=ZEL"}],"SHORTSTATS":10}}},"Commands":"-usercfg=lolMiner-GPU#00-ZergPool-Equihash1445.txt -profile=DEFAULT -disable_memcheck=1"}'


[lolMiner-GPU#00-ZergPool-Equihash1445.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2350404/lolMiner-GPU.00-ZergPool-Equihash1445.txt)

**Comment by Dewbs** [comment]
thanks for the info recreating config and checking...

**Comment by Dewbs** [comment]
yes the pool stuff seems to be cleared up using #2120 and 'new' config file (created from no config and then populated from scratch)

but this miner  still gives:

[lolMiner-GPU#01-4001_2018-09-04_23-42-21.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2350509/lolMiner-GPU.01-4001_2018-09-04_23-42-21.txt)
[lolMiner-GPU#02-4002_2018-09-04_23-42-20.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2350510/lolMiner-GPU.02-4002_2018-09-04_23-42-20.txt)
[MultiPoolMiner_2018-09-04_23-41-46.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2350511/MultiPoolMiner_2018-09-04_23-41-46.txt)
[lolMiner-GPU#00-4000_2018-09-04_23-42-21.txt](https://github.com/MultiPoolMiner/MultiPoolMiner/files/2350512/lolMiner-GPU.00-4000_2018-09-04_23-42-21.txt)

**Comment by UselessGuru** [comment]
@Dewbs

I am really puzzled. All seems ok. ??? WTF ???
The command sent to API (as seen in MPM log) is fine. It does create a functional command file:

```
lolMiner.exe -usercfg=lolMiner-GPU#01-ZergPool-Equihash1927.txt -profile=default
-------------------------------------------------
             Welcome to lolMiner 0.43

   This software is only meant for pool mining
with the Equihash 96.5, 144.5 or 192.7 algorithm

         Made by Lolliedieb, August 2018
-------------------------------------------------
lolMiner is configured to mine Zero(ZER), Equihash 192.7
Setup Miner...
Using device with id 1 (GeForce GTX 1080 Ti)
Connecting to pool...
Connected to equihash192.mine.zergpool.com:2144
Subscribed to stratum server
New target received: 001aaaaaaaaaaaab
New job received: d0f5
Authorized worker: 1GD1YxJWzne32MeDLfX5MLV6dGtT5uW4AN
Start Mining...
Submitting share
Share accepted
Average speed (10s): 18.7 sol/s
^C
```

But the error you are getting suggests that the miner does not find the config file. ???

**Comment by Dewbs** [comment]
Can't use SRB but I'm trying XmRig nvidia now.,.

**Comment by Dewbs** [comment]
I dont think it is creating the correct miner command though?

INFO: Starting miner (lolMiner-GPU#02): 'C:\MPM\Bin\AMD_NVIDIA-lolMiner\lolminer.exe {"ConfigFile":{"FileName":"lolMiner-GPU#02-ZergPool-Equihash1927.txt","Content":{"DEFAULT":{"APIPORT":"4002","COIN":"ZER","DEVICES":["2"],"POOLS":[{"POOL":"equihash192.mine.zergpool.com","PORT":2144,"USER":"1GD1YxJWzne32MeDLfX5MLV6dGtT5uW4AN","PASS":"multipoolminer,c=BTC"}],"SHORTSTATS":10}}},"Commands":"-usercfg=lolMiner-GPU#02-ZergPool-Equihash1927.txt -profile=DEFAULT -disable_memcheck=1"}'

Is all the stuff between lolminer.exe and -usercfg really supposed to be there??

**Comment by Dewbs** [comment]
If I run the following I get:

C:\MPM\Bin\AMD_NVIDIA-lolMiner>lolminer.exe usercfg=lolMiner-GPU#02-ZergPool-Equihash1927.txt -profile=DEFAULT -disable_memcheck=1
-------------------------------------------------
             Welcome to lolMiner 0.43

   This software is only meant for pool mining
with the Equihash 96.5, 144.5 or 192.7 algorithm

         Made by Lolliedieb, August 2018
-------------------------------------------------
Error: user profile DEFAULT not found in configuration file ./user_config.json

**Comment by UselessGuru** [comment]
No, currently Get-TCPResponse is only for lolMiner

**Comment by paulpoco** [comment]
Findings of this new miner on 2 x 1070 OC'd:
AMD_NVIDIA-lolMiner-GPU#00-GPU#01[1.00%]        Equihash965         35.39 KH/s
NVIDIA-EWBF2Equihash-GPU#00-GPU#01[1.00%]      Equihash965         41.65 KH/s

AMD_NVIDIA-lolMiner-GPU#00-GPU#01[2.00%]       Equihash1445         56.00  H/s (2% Dev fee, slower!)
NVIDIA-EWBF2Equihash-GPU#00-GPU#01[1.00%]    Equihash1445          82.00  H/s

AMD_NVIDIA-lolMiner-GPU#00-GPU#01[2.00%]        Equihash1927        37.00  H/s
NVIDIA-EWBF2Equihash-GPU#00-GPU#01[1.00%]     Equihash1927        39.00  H/s

Well this won't be used as it is the slowest one.

**Comment by UselessGuru** [comment]
lolMiner will be included with 3.1.0:
https://github.com/MultiPoolMiner/MultiPoolMiner/releases/tag/3.1.0

**Pull request closed without merging**
